// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/analysis_workflows.proto

package analysis_workflow

import (
	_ "github.com/nanoporetech/minknow_api/go/gen/rpc_options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyRequest_Method int32

const (
	ProxyRequest_GET    ProxyRequest_Method = 0
	ProxyRequest_POST   ProxyRequest_Method = 1
	ProxyRequest_PUT    ProxyRequest_Method = 2
	ProxyRequest_DELETE ProxyRequest_Method = 3
)

// Enum value maps for ProxyRequest_Method.
var (
	ProxyRequest_Method_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	ProxyRequest_Method_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x ProxyRequest_Method) Enum() *ProxyRequest_Method {
	p := new(ProxyRequest_Method)
	*p = x
	return p
}

func (x ProxyRequest_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyRequest_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_analysis_workflows_proto_enumTypes[0].Descriptor()
}

func (ProxyRequest_Method) Type() protoreflect.EnumType {
	return &file_minknow_api_analysis_workflows_proto_enumTypes[0]
}

func (x ProxyRequest_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ProxyRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Api         *string                `protobuf:"bytes,1,opt,name=api"`
	xxx_hidden_Method      ProxyRequest_Method    `protobuf:"varint,2,opt,name=method,enum=minknow_api.analysis_workflows.ProxyRequest_Method"`
	xxx_hidden_Headers     map[string]string      `protobuf:"bytes,4,rep,name=headers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RequestBody *string                `protobuf:"bytes,3,opt,name=request_body,json=requestBody"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_minknow_api_analysis_workflows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_analysis_workflows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProxyRequest) GetApi() string {
	if x != nil {
		if x.xxx_hidden_Api != nil {
			return *x.xxx_hidden_Api
		}
		return ""
	}
	return ""
}

func (x *ProxyRequest) GetMethod() ProxyRequest_Method {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Method
		}
	}
	return ProxyRequest_GET
}

func (x *ProxyRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.xxx_hidden_Headers
	}
	return nil
}

func (x *ProxyRequest) GetRequestBody() string {
	if x != nil {
		if x.xxx_hidden_RequestBody != nil {
			return *x.xxx_hidden_RequestBody
		}
		return ""
	}
	return ""
}

func (x *ProxyRequest) SetApi(v string) {
	x.xxx_hidden_Api = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ProxyRequest) SetMethod(v ProxyRequest_Method) {
	x.xxx_hidden_Method = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ProxyRequest) SetHeaders(v map[string]string) {
	x.xxx_hidden_Headers = v
}

func (x *ProxyRequest) SetRequestBody(v string) {
	x.xxx_hidden_RequestBody = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ProxyRequest) HasApi() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProxyRequest) HasMethod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProxyRequest) HasRequestBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ProxyRequest) ClearApi() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Api = nil
}

func (x *ProxyRequest) ClearMethod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Method = ProxyRequest_GET
}

func (x *ProxyRequest) ClearRequestBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RequestBody = nil
}

type ProxyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// with parameters but without the endpoint e.g.  for API /workflows/{id}/start:
	// "/workflows/ae088129-8767-460f-8795-7c04771dc42f/start"
	// "/workflows/epi2me-labs/wf-alignment/v1.2.8/start"
	Api         *string
	Method      *ProxyRequest_Method
	Headers     map[string]string
	RequestBody *string
}

func (b0 ProxyRequest_builder) Build() *ProxyRequest {
	m0 := &ProxyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Api != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Api = b.Api
	}
	if b.Method != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Method = *b.Method
	}
	x.xxx_hidden_Headers = b.Headers
	if b.RequestBody != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_RequestBody = b.RequestBody
	}
	return m0
}

type ProxyResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StatusCode   uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode"`
	xxx_hidden_ResponseBody *string                `protobuf:"bytes,2,opt,name=response_body,json=responseBody"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_minknow_api_analysis_workflows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_analysis_workflows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProxyResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.xxx_hidden_StatusCode
	}
	return 0
}

func (x *ProxyResponse) GetResponseBody() string {
	if x != nil {
		if x.xxx_hidden_ResponseBody != nil {
			return *x.xxx_hidden_ResponseBody
		}
		return ""
	}
	return ""
}

func (x *ProxyResponse) SetStatusCode(v uint32) {
	x.xxx_hidden_StatusCode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ProxyResponse) SetResponseBody(v string) {
	x.xxx_hidden_ResponseBody = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ProxyResponse) HasStatusCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProxyResponse) HasResponseBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProxyResponse) ClearStatusCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_StatusCode = 0
}

func (x *ProxyResponse) ClearResponseBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResponseBody = nil
}

type ProxyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StatusCode   *uint32
	ResponseBody *string
}

func (b0 ProxyResponse_builder) Build() *ProxyResponse {
	m0 := &ProxyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.StatusCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_StatusCode = *b.StatusCode
	}
	if b.ResponseBody != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ResponseBody = b.ResponseBody
	}
	return m0
}

type AnalysisWorkflowRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WorkflowId  *string                `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId"`
	xxx_hidden_Parameters  *string                `protobuf:"bytes,2,opt,name=parameters"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalysisWorkflowRequest) Reset() {
	*x = AnalysisWorkflowRequest{}
	mi := &file_minknow_api_analysis_workflows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisWorkflowRequest) ProtoMessage() {}

func (x *AnalysisWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_analysis_workflows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AnalysisWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		if x.xxx_hidden_WorkflowId != nil {
			return *x.xxx_hidden_WorkflowId
		}
		return ""
	}
	return ""
}

func (x *AnalysisWorkflowRequest) GetParameters() string {
	if x != nil {
		if x.xxx_hidden_Parameters != nil {
			return *x.xxx_hidden_Parameters
		}
		return ""
	}
	return ""
}

func (x *AnalysisWorkflowRequest) SetWorkflowId(v string) {
	x.xxx_hidden_WorkflowId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AnalysisWorkflowRequest) SetParameters(v string) {
	x.xxx_hidden_Parameters = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AnalysisWorkflowRequest) HasWorkflowId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AnalysisWorkflowRequest) HasParameters() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AnalysisWorkflowRequest) ClearWorkflowId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_WorkflowId = nil
}

func (x *AnalysisWorkflowRequest) ClearParameters() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Parameters = nil
}

type AnalysisWorkflowRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The id of the workflow to start
	WorkflowId *string
	// The parameters to send to the workflow, represented as a stringified JSON object
	Parameters *string
}

func (b0 AnalysisWorkflowRequest_builder) Build() *AnalysisWorkflowRequest {
	m0 := &AnalysisWorkflowRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.WorkflowId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_WorkflowId = b.WorkflowId
	}
	if b.Parameters != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Parameters = b.Parameters
	}
	return m0
}

var File_minknow_api_analysis_workflows_proto protoreflect.FileDescriptor

const file_minknow_api_analysis_workflows_proto_rawDesc = "" +
	"\n" +
	"$minknow_api/analysis_workflows.proto\x12\x1eminknow_api.analysis_workflows\x1a\x1dminknow_api/rpc_options.proto\"\xe5\x02\n" +
	"\fProxyRequest\x12\x16\n" +
	"\x03api\x18\x01 \x01(\tB\x04\xa0\xb5\x18\x00R\x03api\x12K\n" +
	"\x06method\x18\x02 \x01(\x0e23.minknow_api.analysis_workflows.ProxyRequest.MethodR\x06method\x12Y\n" +
	"\aheaders\x18\x04 \x03(\v29.minknow_api.analysis_workflows.ProxyRequest.HeadersEntryB\x04\xa0\xb5\x18\x00R\aheaders\x12'\n" +
	"\frequest_body\x18\x03 \x01(\tB\x04\xa0\xb5\x18\x01R\vrequestBody\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x06Method\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\"U\n" +
	"\rProxyResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12#\n" +
	"\rresponse_body\x18\x02 \x01(\tR\fresponseBody\"f\n" +
	"\x17AnalysisWorkflowRequest\x12%\n" +
	"\vworkflow_id\x18\x01 \x01(\tB\x04\xa0\xb5\x18\x00R\n" +
	"workflowId\x12$\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tB\x04\xa0\xb5\x18\x01R\n" +
	"parameters2\x88\x01\n" +
	"\x18AnalysisWorkflowsService\x12l\n" +
	"\x05proxy\x12,.minknow_api.analysis_workflows.ProxyRequest\x1a-.minknow_api.analysis_workflows.ProxyResponse\"\x04\x98\xb5\x18\x010\x01Bg\n" +
	"\x1ccom.nanoporetech.minknow_apiZ<github.com/nanoporetech/minknow_api/go/gen/analysis_workflow\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_analysis_workflows_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minknow_api_analysis_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_minknow_api_analysis_workflows_proto_goTypes = []any{
	(ProxyRequest_Method)(0),        // 0: minknow_api.analysis_workflows.ProxyRequest.Method
	(*ProxyRequest)(nil),            // 1: minknow_api.analysis_workflows.ProxyRequest
	(*ProxyResponse)(nil),           // 2: minknow_api.analysis_workflows.ProxyResponse
	(*AnalysisWorkflowRequest)(nil), // 3: minknow_api.analysis_workflows.AnalysisWorkflowRequest
	nil,                             // 4: minknow_api.analysis_workflows.ProxyRequest.HeadersEntry
}
var file_minknow_api_analysis_workflows_proto_depIdxs = []int32{
	0, // 0: minknow_api.analysis_workflows.ProxyRequest.method:type_name -> minknow_api.analysis_workflows.ProxyRequest.Method
	4, // 1: minknow_api.analysis_workflows.ProxyRequest.headers:type_name -> minknow_api.analysis_workflows.ProxyRequest.HeadersEntry
	1, // 2: minknow_api.analysis_workflows.AnalysisWorkflowsService.proxy:input_type -> minknow_api.analysis_workflows.ProxyRequest
	2, // 3: minknow_api.analysis_workflows.AnalysisWorkflowsService.proxy:output_type -> minknow_api.analysis_workflows.ProxyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_minknow_api_analysis_workflows_proto_init() }
func file_minknow_api_analysis_workflows_proto_init() {
	if File_minknow_api_analysis_workflows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_analysis_workflows_proto_rawDesc), len(file_minknow_api_analysis_workflows_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_analysis_workflows_proto_goTypes,
		DependencyIndexes: file_minknow_api_analysis_workflows_proto_depIdxs,
		EnumInfos:         file_minknow_api_analysis_workflows_proto_enumTypes,
		MessageInfos:      file_minknow_api_analysis_workflows_proto_msgTypes,
	}.Build()
	File_minknow_api_analysis_workflows_proto = out.File
	file_minknow_api_analysis_workflows_proto_goTypes = nil
	file_minknow_api_analysis_workflows_proto_depIdxs = nil
}
