// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/debug.proto

package debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasecallClientState struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasecallClientState) Reset() {
	*x = GetBasecallClientState{}
	mi := &file_minknow_api_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasecallClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasecallClientState) ProtoMessage() {}

func (x *GetBasecallClientState) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetBasecallClientState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetBasecallClientState_builder) Build() *GetBasecallClientState {
	m0 := &GetBasecallClientState{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetBasecallClientResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClientState []string               `protobuf:"bytes,1,rep,name=client_state,json=clientState"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBasecallClientResponse) Reset() {
	*x = GetBasecallClientResponse{}
	mi := &file_minknow_api_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasecallClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasecallClientResponse) ProtoMessage() {}

func (x *GetBasecallClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBasecallClientResponse) GetClientState() []string {
	if x != nil {
		return x.xxx_hidden_ClientState
	}
	return nil
}

func (x *GetBasecallClientResponse) SetClientState(v []string) {
	x.xxx_hidden_ClientState = v
}

type GetBasecallClientResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This debug string with internal debug data, in practice it generally a JSON-formatted string.
	ClientState []string
}

func (b0 GetBasecallClientResponse_builder) Build() *GetBasecallClientResponse {
	m0 := &GetBasecallClientResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClientState = b.ClientState
	return m0
}

type GetBasecallServerState struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasecallServerState) Reset() {
	*x = GetBasecallServerState{}
	mi := &file_minknow_api_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasecallServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasecallServerState) ProtoMessage() {}

func (x *GetBasecallServerState) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetBasecallServerState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetBasecallServerState_builder) Build() *GetBasecallServerState {
	m0 := &GetBasecallServerState{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetBasecallServerResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServerState *string                `protobuf:"bytes,1,opt,name=server_state,json=serverState"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBasecallServerResponse) Reset() {
	*x = GetBasecallServerResponse{}
	mi := &file_minknow_api_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasecallServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasecallServerResponse) ProtoMessage() {}

func (x *GetBasecallServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBasecallServerResponse) GetServerState() string {
	if x != nil {
		if x.xxx_hidden_ServerState != nil {
			return *x.xxx_hidden_ServerState
		}
		return ""
	}
	return ""
}

func (x *GetBasecallServerResponse) SetServerState(v string) {
	x.xxx_hidden_ServerState = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetBasecallServerResponse) HasServerState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBasecallServerResponse) ClearServerState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServerState = nil
}

type GetBasecallServerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This debug string with internal debug data, in practice it generally a JSON-formatted string.
	ServerState *string
}

func (b0 GetBasecallServerResponse_builder) Build() *GetBasecallServerResponse {
	m0 := &GetBasecallServerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServerState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServerState = b.ServerState
	}
	return m0
}

type DisconnectFlowCellRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectFlowCellRequest) Reset() {
	*x = DisconnectFlowCellRequest{}
	mi := &file_minknow_api_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectFlowCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectFlowCellRequest) ProtoMessage() {}

func (x *DisconnectFlowCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DisconnectFlowCellRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DisconnectFlowCellRequest_builder) Build() *DisconnectFlowCellRequest {
	m0 := &DisconnectFlowCellRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DisconnectFlowCellResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectFlowCellResponse) Reset() {
	*x = DisconnectFlowCellResponse{}
	mi := &file_minknow_api_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectFlowCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectFlowCellResponse) ProtoMessage() {}

func (x *DisconnectFlowCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DisconnectFlowCellResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DisconnectFlowCellResponse_builder) Build() *DisconnectFlowCellResponse {
	m0 := &DisconnectFlowCellResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConnectFlowCellRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FlowCellId      *string                `protobuf:"bytes,1,opt,name=flow_cell_id,json=flowCellId"`
	xxx_hidden_ProductCode     *string                `protobuf:"bytes,2,opt,name=product_code,json=productCode"`
	xxx_hidden_AsicIdStr       *string                `protobuf:"bytes,3,opt,name=asic_id_str,json=asicIdStr"`
	xxx_hidden_AdapterId       *string                `protobuf:"bytes,4,opt,name=adapter_id,json=adapterId"`
	xxx_hidden_UseCount        uint32                 `protobuf:"varint,5,opt,name=use_count,json=useCount"`
	xxx_hidden_FlowCellPartner *string                `protobuf:"bytes,6,opt,name=flow_cell_partner,json=flowCellPartner"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ConnectFlowCellRequest) Reset() {
	*x = ConnectFlowCellRequest{}
	mi := &file_minknow_api_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectFlowCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectFlowCellRequest) ProtoMessage() {}

func (x *ConnectFlowCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectFlowCellRequest) GetFlowCellId() string {
	if x != nil {
		if x.xxx_hidden_FlowCellId != nil {
			return *x.xxx_hidden_FlowCellId
		}
		return ""
	}
	return ""
}

func (x *ConnectFlowCellRequest) GetProductCode() string {
	if x != nil {
		if x.xxx_hidden_ProductCode != nil {
			return *x.xxx_hidden_ProductCode
		}
		return ""
	}
	return ""
}

func (x *ConnectFlowCellRequest) GetAsicIdStr() string {
	if x != nil {
		if x.xxx_hidden_AsicIdStr != nil {
			return *x.xxx_hidden_AsicIdStr
		}
		return ""
	}
	return ""
}

func (x *ConnectFlowCellRequest) GetAdapterId() string {
	if x != nil {
		if x.xxx_hidden_AdapterId != nil {
			return *x.xxx_hidden_AdapterId
		}
		return ""
	}
	return ""
}

func (x *ConnectFlowCellRequest) GetUseCount() uint32 {
	if x != nil {
		return x.xxx_hidden_UseCount
	}
	return 0
}

func (x *ConnectFlowCellRequest) GetFlowCellPartner() string {
	if x != nil {
		if x.xxx_hidden_FlowCellPartner != nil {
			return *x.xxx_hidden_FlowCellPartner
		}
		return ""
	}
	return ""
}

func (x *ConnectFlowCellRequest) SetFlowCellId(v string) {
	x.xxx_hidden_FlowCellId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ConnectFlowCellRequest) SetProductCode(v string) {
	x.xxx_hidden_ProductCode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ConnectFlowCellRequest) SetAsicIdStr(v string) {
	x.xxx_hidden_AsicIdStr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *ConnectFlowCellRequest) SetAdapterId(v string) {
	x.xxx_hidden_AdapterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ConnectFlowCellRequest) SetUseCount(v uint32) {
	x.xxx_hidden_UseCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ConnectFlowCellRequest) SetFlowCellPartner(v string) {
	x.xxx_hidden_FlowCellPartner = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ConnectFlowCellRequest) HasFlowCellId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectFlowCellRequest) HasProductCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConnectFlowCellRequest) HasAsicIdStr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ConnectFlowCellRequest) HasAdapterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ConnectFlowCellRequest) HasUseCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ConnectFlowCellRequest) HasFlowCellPartner() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ConnectFlowCellRequest) ClearFlowCellId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FlowCellId = nil
}

func (x *ConnectFlowCellRequest) ClearProductCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ProductCode = nil
}

func (x *ConnectFlowCellRequest) ClearAsicIdStr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AsicIdStr = nil
}

func (x *ConnectFlowCellRequest) ClearAdapterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AdapterId = nil
}

func (x *ConnectFlowCellRequest) ClearUseCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_UseCount = 0
}

func (x *ConnectFlowCellRequest) ClearFlowCellPartner() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_FlowCellPartner = nil
}

type ConnectFlowCellRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The unique identifier for the flow cell.
	//
	// This should be same as the value printed onto the flow cell casing. Not all flow cells will
	// have the flow cell ID recorded in a way that MinKNOW can read. In those cases, this will be an
	// empty string, even though the user may be able to see a printed identifier on the flow cell.
	FlowCellId *string
	// The product code for the flow cell.
	//
	// This should be the code displayed in the shop where the flow cell was bought. Not all
	// flow cells will have the product code recorded in a way that MinKNOW can read. In those cases,
	// this will be an empty string.
	ProductCode *string
	// The unique identifier for the ASIC (formatted as string).
	//
	// This is a value uniquely identifying the ASIC embedded in the flow cell. It will
	// always be set when a flow cell is present.
	AsicIdStr *string
	// The unique identifier of an attached flongle adapter.
	//
	// If set then the simulated device will assume an adapter is present.
	// This is ignored if not a Simulated MinION
	AdapterId *string
	// The use count for this flow cell.
	//
	// Can be set to mimic a flow cell being inserted that has exceeded the use count limit.
	UseCount *uint32
	// The partner the flow cell was produced for.
	FlowCellPartner *string
}

func (b0 ConnectFlowCellRequest_builder) Build() *ConnectFlowCellRequest {
	m0 := &ConnectFlowCellRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FlowCellId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_FlowCellId = b.FlowCellId
	}
	if b.ProductCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_ProductCode = b.ProductCode
	}
	if b.AsicIdStr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_AsicIdStr = b.AsicIdStr
	}
	if b.AdapterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_AdapterId = b.AdapterId
	}
	if b.UseCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_UseCount = *b.UseCount
	}
	if b.FlowCellPartner != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_FlowCellPartner = b.FlowCellPartner
	}
	return m0
}

type ConnectFlowCellResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectFlowCellResponse) Reset() {
	*x = ConnectFlowCellResponse{}
	mi := &file_minknow_api_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectFlowCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectFlowCellResponse) ProtoMessage() {}

func (x *ConnectFlowCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConnectFlowCellResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConnectFlowCellResponse_builder) Build() *ConnectFlowCellResponse {
	m0 := &ConnectFlowCellResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SimulateFrameLossRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FrameLossDuration *durationpb.Duration   `protobuf:"bytes,1,opt,name=frame_loss_duration,json=frameLossDuration"`
	xxx_hidden_StartFrame        uint64                 `protobuf:"varint,3,opt,name=start_frame,json=startFrame"`
	xxx_hidden_StartSection      uint64                 `protobuf:"varint,4,opt,name=start_section,json=startSection"`
	xxx_hidden_Repeats           uint64                 `protobuf:"varint,5,opt,name=repeats"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SimulateFrameLossRequest) Reset() {
	*x = SimulateFrameLossRequest{}
	mi := &file_minknow_api_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateFrameLossRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateFrameLossRequest) ProtoMessage() {}

func (x *SimulateFrameLossRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SimulateFrameLossRequest) GetFrameLossDuration() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_FrameLossDuration
	}
	return nil
}

func (x *SimulateFrameLossRequest) GetStartFrame() uint64 {
	if x != nil {
		return x.xxx_hidden_StartFrame
	}
	return 0
}

func (x *SimulateFrameLossRequest) GetStartSection() uint64 {
	if x != nil {
		return x.xxx_hidden_StartSection
	}
	return 0
}

func (x *SimulateFrameLossRequest) GetRepeats() uint64 {
	if x != nil {
		return x.xxx_hidden_Repeats
	}
	return 0
}

func (x *SimulateFrameLossRequest) SetFrameLossDuration(v *durationpb.Duration) {
	x.xxx_hidden_FrameLossDuration = v
}

func (x *SimulateFrameLossRequest) SetStartFrame(v uint64) {
	x.xxx_hidden_StartFrame = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *SimulateFrameLossRequest) SetStartSection(v uint64) {
	x.xxx_hidden_StartSection = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *SimulateFrameLossRequest) SetRepeats(v uint64) {
	x.xxx_hidden_Repeats = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *SimulateFrameLossRequest) HasFrameLossDuration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FrameLossDuration != nil
}

func (x *SimulateFrameLossRequest) HasStartFrame() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SimulateFrameLossRequest) HasStartSection() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SimulateFrameLossRequest) HasRepeats() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SimulateFrameLossRequest) ClearFrameLossDuration() {
	x.xxx_hidden_FrameLossDuration = nil
}

func (x *SimulateFrameLossRequest) ClearStartFrame() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_StartFrame = 0
}

func (x *SimulateFrameLossRequest) ClearStartSection() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_StartSection = 0
}

func (x *SimulateFrameLossRequest) ClearRepeats() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Repeats = 0
}

type SimulateFrameLossRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The duration for which the frame loss will occur.
	FrameLossDuration *durationpb.Duration
	// The frame index from which the frame loss will begin
	//
	// For simulated PromethIONs this equates to the frame index within a section
	StartFrame *uint64
	// Optional section index from which the frame loss will begin
	//
	// For simulated PromethIONs a section equates to a completed scatterlist
	StartSection *uint64
	// Optional number of times to repeat the failed transfers
	//
	// This will reset the frame loss on starting a new acquisition or
	// resuming acquisition on an existing signal reader.
	Repeats *uint64
}

func (b0 SimulateFrameLossRequest_builder) Build() *SimulateFrameLossRequest {
	m0 := &SimulateFrameLossRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FrameLossDuration = b.FrameLossDuration
	if b.StartFrame != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_StartFrame = *b.StartFrame
	}
	if b.StartSection != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_StartSection = *b.StartSection
	}
	if b.Repeats != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Repeats = *b.Repeats
	}
	return m0
}

type SimulateFrameLossResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateFrameLossResponse) Reset() {
	*x = SimulateFrameLossResponse{}
	mi := &file_minknow_api_debug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateFrameLossResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateFrameLossResponse) ProtoMessage() {}

func (x *SimulateFrameLossResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_debug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SimulateFrameLossResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SimulateFrameLossResponse_builder) Build() *SimulateFrameLossResponse {
	m0 := &SimulateFrameLossResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_minknow_api_debug_proto protoreflect.FileDescriptor

const file_minknow_api_debug_proto_rawDesc = "" +
	"\n" +
	"\x17minknow_api/debug.proto\x12\x11minknow_api.debug\x1a\x1egoogle/protobuf/duration.proto\"\x18\n" +
	"\x16GetBasecallClientState\">\n" +
	"\x19GetBasecallClientResponse\x12!\n" +
	"\fclient_state\x18\x01 \x03(\tR\vclientState\"\x18\n" +
	"\x16GetBasecallServerState\">\n" +
	"\x19GetBasecallServerResponse\x12!\n" +
	"\fserver_state\x18\x01 \x01(\tR\vserverState\"\x1b\n" +
	"\x19DisconnectFlowCellRequest\"\x1c\n" +
	"\x1aDisconnectFlowCellResponse\"\xe5\x01\n" +
	"\x16ConnectFlowCellRequest\x12 \n" +
	"\fflow_cell_id\x18\x01 \x01(\tR\n" +
	"flowCellId\x12!\n" +
	"\fproduct_code\x18\x02 \x01(\tR\vproductCode\x12\x1e\n" +
	"\vasic_id_str\x18\x03 \x01(\tR\tasicIdStr\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x04 \x01(\tR\tadapterId\x12\x1b\n" +
	"\tuse_count\x18\x05 \x01(\rR\buseCount\x12*\n" +
	"\x11flow_cell_partner\x18\x06 \x01(\tR\x0fflowCellPartner\"\x19\n" +
	"\x17ConnectFlowCellResponse\"\xc5\x01\n" +
	"\x18SimulateFrameLossRequest\x12I\n" +
	"\x13frame_loss_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11frameLossDuration\x12\x1f\n" +
	"\vstart_frame\x18\x03 \x01(\x04R\n" +
	"startFrame\x12#\n" +
	"\rstart_section\x18\x04 \x01(\x04R\fstartSection\x12\x18\n" +
	"\arepeats\x18\x05 \x01(\x04R\arepeats\"\x1b\n" +
	"\x19SimulateFrameLossResponse2\xe1\x04\n" +
	"\fDebugService\x12{\n" +
	"\x1bget_basecall_clients_states\x12).minknow_api.debug.GetBasecallClientState\x1a,.minknow_api.debug.GetBasecallClientResponse\"\x03\x90\x02\x01\x12{\n" +
	"\x1bget_basecaller_server_state\x12).minknow_api.debug.GetBasecallServerState\x1a,.minknow_api.debug.GetBasecallServerResponse\"\x03\x90\x02\x01\x12u\n" +
	"\x14disconnect_flow_cell\x12,.minknow_api.debug.DisconnectFlowCellRequest\x1a-.minknow_api.debug.DisconnectFlowCellResponse\"\x00\x12l\n" +
	"\x11connect_flow_cell\x12).minknow_api.debug.ConnectFlowCellRequest\x1a*.minknow_api.debug.ConnectFlowCellResponse\"\x00\x12r\n" +
	"\x13simulate_frame_loss\x12+.minknow_api.debug.SimulateFrameLossRequest\x1a,.minknow_api.debug.SimulateFrameLossResponse\"\x00B[\n" +
	"\x1ccom.nanoporetech.minknow_apiZ0github.com/nanoporetech/minknow_api/go/gen/debug\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_minknow_api_debug_proto_goTypes = []any{
	(*GetBasecallClientState)(nil),     // 0: minknow_api.debug.GetBasecallClientState
	(*GetBasecallClientResponse)(nil),  // 1: minknow_api.debug.GetBasecallClientResponse
	(*GetBasecallServerState)(nil),     // 2: minknow_api.debug.GetBasecallServerState
	(*GetBasecallServerResponse)(nil),  // 3: minknow_api.debug.GetBasecallServerResponse
	(*DisconnectFlowCellRequest)(nil),  // 4: minknow_api.debug.DisconnectFlowCellRequest
	(*DisconnectFlowCellResponse)(nil), // 5: minknow_api.debug.DisconnectFlowCellResponse
	(*ConnectFlowCellRequest)(nil),     // 6: minknow_api.debug.ConnectFlowCellRequest
	(*ConnectFlowCellResponse)(nil),    // 7: minknow_api.debug.ConnectFlowCellResponse
	(*SimulateFrameLossRequest)(nil),   // 8: minknow_api.debug.SimulateFrameLossRequest
	(*SimulateFrameLossResponse)(nil),  // 9: minknow_api.debug.SimulateFrameLossResponse
	(*durationpb.Duration)(nil),        // 10: google.protobuf.Duration
}
var file_minknow_api_debug_proto_depIdxs = []int32{
	10, // 0: minknow_api.debug.SimulateFrameLossRequest.frame_loss_duration:type_name -> google.protobuf.Duration
	0,  // 1: minknow_api.debug.DebugService.get_basecall_clients_states:input_type -> minknow_api.debug.GetBasecallClientState
	2,  // 2: minknow_api.debug.DebugService.get_basecaller_server_state:input_type -> minknow_api.debug.GetBasecallServerState
	4,  // 3: minknow_api.debug.DebugService.disconnect_flow_cell:input_type -> minknow_api.debug.DisconnectFlowCellRequest
	6,  // 4: minknow_api.debug.DebugService.connect_flow_cell:input_type -> minknow_api.debug.ConnectFlowCellRequest
	8,  // 5: minknow_api.debug.DebugService.simulate_frame_loss:input_type -> minknow_api.debug.SimulateFrameLossRequest
	1,  // 6: minknow_api.debug.DebugService.get_basecall_clients_states:output_type -> minknow_api.debug.GetBasecallClientResponse
	3,  // 7: minknow_api.debug.DebugService.get_basecaller_server_state:output_type -> minknow_api.debug.GetBasecallServerResponse
	5,  // 8: minknow_api.debug.DebugService.disconnect_flow_cell:output_type -> minknow_api.debug.DisconnectFlowCellResponse
	7,  // 9: minknow_api.debug.DebugService.connect_flow_cell:output_type -> minknow_api.debug.ConnectFlowCellResponse
	9,  // 10: minknow_api.debug.DebugService.simulate_frame_loss:output_type -> minknow_api.debug.SimulateFrameLossResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_minknow_api_debug_proto_init() }
func file_minknow_api_debug_proto_init() {
	if File_minknow_api_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_debug_proto_rawDesc), len(file_minknow_api_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_debug_proto_goTypes,
		DependencyIndexes: file_minknow_api_debug_proto_depIdxs,
		MessageInfos:      file_minknow_api_debug_proto_msgTypes,
	}.Build()
	File_minknow_api_debug_proto = out.File
	file_minknow_api_debug_proto_goTypes = nil
	file_minknow_api_debug_proto_depIdxs = nil
}
