// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/hardware_check.proto

package hardware_check

import (
	device "github.com/nanoporetech/minknow_api/go/gen/device"
	protocol "github.com/nanoporetech/minknow_api/go/gen/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardwareCheckState int32

const (
	// The hardware check is running
	HardwareCheckState_HARDWARE_CHECK_RUNNING HardwareCheckState = 0
	// The hardware check has finished successfully
	HardwareCheckState_HARDWARE_CHECK_COMPLETED HardwareCheckState = 1
	// The hardware check was cancelled/stopped by the user
	HardwareCheckState_HARDWARE_CHECK_STOPPED HardwareCheckState = 2
	// Failed to get the exit status of the python executor
	HardwareCheckState_HARDWARE_CHECK_FINISHED_WITH_ERROR_COULD_NOT_OBTAIN_EXIT_CODE HardwareCheckState = 3
	// The python executor returned an error code on start-up
	HardwareCheckState_HARDWARE_CHECK_FINISHED_WITH_ERROR_PYTHON_EXECUTOR_DID_NOT_START HardwareCheckState = 4
	// The python script finished with an error code
	HardwareCheckState_HARDWARE_CHECK_FINISHED_WITH_ERROR_SCRIPT_ERROR_CODE HardwareCheckState = 5
	// Clean-up encountered a lingering run
	HardwareCheckState_HARDWARE_CHECK_FINISHED_WITH_ERROR_LINGERING_RUN HardwareCheckState = 6
)

// Enum value maps for HardwareCheckState.
var (
	HardwareCheckState_name = map[int32]string{
		0: "HARDWARE_CHECK_RUNNING",
		1: "HARDWARE_CHECK_COMPLETED",
		2: "HARDWARE_CHECK_STOPPED",
		3: "HARDWARE_CHECK_FINISHED_WITH_ERROR_COULD_NOT_OBTAIN_EXIT_CODE",
		4: "HARDWARE_CHECK_FINISHED_WITH_ERROR_PYTHON_EXECUTOR_DID_NOT_START",
		5: "HARDWARE_CHECK_FINISHED_WITH_ERROR_SCRIPT_ERROR_CODE",
		6: "HARDWARE_CHECK_FINISHED_WITH_ERROR_LINGERING_RUN",
	}
	HardwareCheckState_value = map[string]int32{
		"HARDWARE_CHECK_RUNNING":   0,
		"HARDWARE_CHECK_COMPLETED": 1,
		"HARDWARE_CHECK_STOPPED":   2,
		"HARDWARE_CHECK_FINISHED_WITH_ERROR_COULD_NOT_OBTAIN_EXIT_CODE":    3,
		"HARDWARE_CHECK_FINISHED_WITH_ERROR_PYTHON_EXECUTOR_DID_NOT_START": 4,
		"HARDWARE_CHECK_FINISHED_WITH_ERROR_SCRIPT_ERROR_CODE":             5,
		"HARDWARE_CHECK_FINISHED_WITH_ERROR_LINGERING_RUN":                 6,
	}
)

func (x HardwareCheckState) Enum() *HardwareCheckState {
	p := new(HardwareCheckState)
	*p = x
	return p
}

func (x HardwareCheckState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HardwareCheckState) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_hardware_check_proto_enumTypes[0].Descriptor()
}

func (HardwareCheckState) Type() protoreflect.EnumType {
	return &file_minknow_api_hardware_check_proto_enumTypes[0]
}

func (x HardwareCheckState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type StartHardwareCheckRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PositionIds []string               `protobuf:"bytes,1,rep,name=position_ids,json=positionIds"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartHardwareCheckRequest) Reset() {
	*x = StartHardwareCheckRequest{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHardwareCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHardwareCheckRequest) ProtoMessage() {}

func (x *StartHardwareCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartHardwareCheckRequest) GetPositionIds() []string {
	if x != nil {
		return x.xxx_hidden_PositionIds
	}
	return nil
}

func (x *StartHardwareCheckRequest) SetPositionIds(v []string) {
	x.xxx_hidden_PositionIds = v
}

type StartHardwareCheckRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of position IDs to start a hardware check on
	// e.g. `['X1', X2', 'X5']`.
	PositionIds []string
}

func (b0 StartHardwareCheckRequest_builder) Build() *StartHardwareCheckRequest {
	m0 := &StartHardwareCheckRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PositionIds = b.PositionIds
	return m0
}

type StartHardwareCheckResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId *string                `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StartHardwareCheckResponse) Reset() {
	*x = StartHardwareCheckResponse{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHardwareCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHardwareCheckResponse) ProtoMessage() {}

func (x *StartHardwareCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartHardwareCheckResponse) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *StartHardwareCheckResponse) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StartHardwareCheckResponse) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartHardwareCheckResponse) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

type StartHardwareCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The unique ID for the newly created hardware check.
	HardwareCheckId *string
}

func (b0 StartHardwareCheckResponse_builder) Build() *StartHardwareCheckResponse {
	m0 := &StartHardwareCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	return m0
}

type StopHardwareCheckRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId *string                `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StopHardwareCheckRequest) Reset() {
	*x = StopHardwareCheckRequest{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHardwareCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHardwareCheckRequest) ProtoMessage() {}

func (x *StopHardwareCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopHardwareCheckRequest) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *StopHardwareCheckRequest) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StopHardwareCheckRequest) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StopHardwareCheckRequest) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

type StopHardwareCheckRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The unique ID for a hardware check.
	HardwareCheckId *string
}

func (b0 StopHardwareCheckRequest_builder) Build() *StopHardwareCheckRequest {
	m0 := &StopHardwareCheckRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	return m0
}

type StopHardwareCheckResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopHardwareCheckResponse) Reset() {
	*x = StopHardwareCheckResponse{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHardwareCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHardwareCheckResponse) ProtoMessage() {}

func (x *StopHardwareCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StopHardwareCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StopHardwareCheckResponse_builder) Build() *StopHardwareCheckResponse {
	m0 := &StopHardwareCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Each position result
type PositionCheckResult struct {
	state                          protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_PositionId          *string                                 `protobuf:"bytes,1,opt,name=position_id,json=positionId"`
	xxx_hidden_DeviceType          device.GetDeviceInfoResponse_DeviceType `protobuf:"varint,2,opt,name=device_type,json=deviceType,enum=minknow_api.device.GetDeviceInfoResponse_DeviceType"`
	xxx_hidden_HardwareCheckResult *protocol.HardwareCheckResult           `protobuf:"bytes,3,opt,name=hardware_check_result,json=hardwareCheckResult"`
	xxx_hidden_AdapterId           *string                                 `protobuf:"bytes,4,opt,name=adapter_id,json=adapterId"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PositionCheckResult) Reset() {
	*x = PositionCheckResult{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionCheckResult) ProtoMessage() {}

func (x *PositionCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PositionCheckResult) GetPositionId() string {
	if x != nil {
		if x.xxx_hidden_PositionId != nil {
			return *x.xxx_hidden_PositionId
		}
		return ""
	}
	return ""
}

func (x *PositionCheckResult) GetDeviceType() device.GetDeviceInfoResponse_DeviceType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_DeviceType
		}
	}
	return device.GetDeviceInfoResponse_DeviceType(0)
}

func (x *PositionCheckResult) GetHardwareCheckResult() *protocol.HardwareCheckResult {
	if x != nil {
		return x.xxx_hidden_HardwareCheckResult
	}
	return nil
}

func (x *PositionCheckResult) GetAdapterId() string {
	if x != nil {
		if x.xxx_hidden_AdapterId != nil {
			return *x.xxx_hidden_AdapterId
		}
		return ""
	}
	return ""
}

func (x *PositionCheckResult) SetPositionId(v string) {
	x.xxx_hidden_PositionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *PositionCheckResult) SetDeviceType(v device.GetDeviceInfoResponse_DeviceType) {
	x.xxx_hidden_DeviceType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *PositionCheckResult) SetHardwareCheckResult(v *protocol.HardwareCheckResult) {
	x.xxx_hidden_HardwareCheckResult = v
}

func (x *PositionCheckResult) SetAdapterId(v string) {
	x.xxx_hidden_AdapterId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *PositionCheckResult) HasPositionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PositionCheckResult) HasDeviceType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PositionCheckResult) HasHardwareCheckResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HardwareCheckResult != nil
}

func (x *PositionCheckResult) HasAdapterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PositionCheckResult) ClearPositionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PositionId = nil
}

func (x *PositionCheckResult) ClearDeviceType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DeviceType = device.GetDeviceInfoResponse_MINION
}

func (x *PositionCheckResult) ClearHardwareCheckResult() {
	x.xxx_hidden_HardwareCheckResult = nil
}

func (x *PositionCheckResult) ClearAdapterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AdapterId = nil
}

type PositionCheckResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the position that performed the hardware check.
	PositionId *string
	// The type of the device the hardware check is running on.
	DeviceType *device.GetDeviceInfoResponse_DeviceType
	// The position hardware check result
	// This is the HardwareCheckResult message from the protocol
	HardwareCheckResult *protocol.HardwareCheckResult
	// The unique identifier of an attached flongle adapter.
	// This should be same as the value printed onto the adapter casing.
	AdapterId *string
}

func (b0 PositionCheckResult_builder) Build() *PositionCheckResult {
	m0 := &PositionCheckResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PositionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_PositionId = b.PositionId
	}
	if b.DeviceType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_DeviceType = *b.DeviceType
	}
	x.xxx_hidden_HardwareCheckResult = b.HardwareCheckResult
	if b.AdapterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_AdapterId = b.AdapterId
	}
	return m0
}

// The data received from the hardware check script
type HardwareCheckScriptData struct {
	state                           protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_PositionCheckResults *[]*PositionCheckResult `protobuf:"bytes,1,rep,name=position_check_results,json=positionCheckResults"`
	xxx_hidden_ProgressPercent      uint32                  `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent"`
	xxx_hidden_ProgressEtaSeconds   uint32                  `protobuf:"varint,3,opt,name=progress_eta_seconds,json=progressEtaSeconds"`
	xxx_hidden_OverallResult        bool                    `protobuf:"varint,5,opt,name=overall_result,json=overallResult"`
	xxx_hidden_ProtocolRunIds       []string                `protobuf:"bytes,6,rep,name=protocol_run_ids,json=protocolRunIds"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *HardwareCheckScriptData) Reset() {
	*x = HardwareCheckScriptData{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareCheckScriptData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareCheckScriptData) ProtoMessage() {}

func (x *HardwareCheckScriptData) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HardwareCheckScriptData) GetPositionCheckResults() []*PositionCheckResult {
	if x != nil {
		if x.xxx_hidden_PositionCheckResults != nil {
			return *x.xxx_hidden_PositionCheckResults
		}
	}
	return nil
}

func (x *HardwareCheckScriptData) GetProgressPercent() uint32 {
	if x != nil {
		return x.xxx_hidden_ProgressPercent
	}
	return 0
}

func (x *HardwareCheckScriptData) GetProgressEtaSeconds() uint32 {
	if x != nil {
		return x.xxx_hidden_ProgressEtaSeconds
	}
	return 0
}

func (x *HardwareCheckScriptData) GetOverallResult() bool {
	if x != nil {
		return x.xxx_hidden_OverallResult
	}
	return false
}

func (x *HardwareCheckScriptData) GetProtocolRunIds() []string {
	if x != nil {
		return x.xxx_hidden_ProtocolRunIds
	}
	return nil
}

func (x *HardwareCheckScriptData) SetPositionCheckResults(v []*PositionCheckResult) {
	x.xxx_hidden_PositionCheckResults = &v
}

func (x *HardwareCheckScriptData) SetProgressPercent(v uint32) {
	x.xxx_hidden_ProgressPercent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *HardwareCheckScriptData) SetProgressEtaSeconds(v uint32) {
	x.xxx_hidden_ProgressEtaSeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *HardwareCheckScriptData) SetOverallResult(v bool) {
	x.xxx_hidden_OverallResult = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *HardwareCheckScriptData) SetProtocolRunIds(v []string) {
	x.xxx_hidden_ProtocolRunIds = v
}

func (x *HardwareCheckScriptData) HasProgressPercent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HardwareCheckScriptData) HasProgressEtaSeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HardwareCheckScriptData) HasOverallResult() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HardwareCheckScriptData) ClearProgressPercent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ProgressPercent = 0
}

func (x *HardwareCheckScriptData) ClearProgressEtaSeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ProgressEtaSeconds = 0
}

func (x *HardwareCheckScriptData) ClearOverallResult() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OverallResult = false
}

type HardwareCheckScriptData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of results for each position.
	PositionCheckResults []*PositionCheckResult
	// Indicates progress of the overall hardware check procedure.
	//
	// This field will always have values between 0 and 100 (inclusive), and the value will increase
	// over time. It is intended for displaying a progress bar or similar.
	//
	// When the hardware check has completed this value will be 100.
	ProgressPercent *uint32
	// Indicates roughly how much time is remaining for the hardware check.
	//
	// If no ETA can be calculated, or the hardware check is complete, this will be zero.
	//
	// Note that it is always an estimate - it is recommended to round larger values, like "about 2
	// minutes remaining".
	ProgressEtaSeconds *uint32
	// Final overall pass/fail across all tests and positions
	OverallResult *bool
	// protocol_run_ids that have been started by the hardware check
	//
	// If any protocol listed here is still running when the hardware check finishes, that protocol
	// will be stopped.
	ProtocolRunIds []string
}

func (b0 HardwareCheckScriptData_builder) Build() *HardwareCheckScriptData {
	m0 := &HardwareCheckScriptData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PositionCheckResults = &b.PositionCheckResults
	if b.ProgressPercent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_ProgressPercent = *b.ProgressPercent
	}
	if b.ProgressEtaSeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ProgressEtaSeconds = *b.ProgressEtaSeconds
	}
	if b.OverallResult != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_OverallResult = *b.OverallResult
	}
	x.xxx_hidden_ProtocolRunIds = b.ProtocolRunIds
	return m0
}

type UpdateHardwareCheckResultsRequest struct {
	state                              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId         *string                  `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	xxx_hidden_HardwareCheckScriptData *HardwareCheckScriptData `protobuf:"bytes,2,opt,name=hardware_check_script_data,json=hardwareCheckScriptData"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *UpdateHardwareCheckResultsRequest) Reset() {
	*x = UpdateHardwareCheckResultsRequest{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHardwareCheckResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHardwareCheckResultsRequest) ProtoMessage() {}

func (x *UpdateHardwareCheckResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateHardwareCheckResultsRequest) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *UpdateHardwareCheckResultsRequest) GetHardwareCheckScriptData() *HardwareCheckScriptData {
	if x != nil {
		return x.xxx_hidden_HardwareCheckScriptData
	}
	return nil
}

func (x *UpdateHardwareCheckResultsRequest) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateHardwareCheckResultsRequest) SetHardwareCheckScriptData(v *HardwareCheckScriptData) {
	x.xxx_hidden_HardwareCheckScriptData = v
}

func (x *UpdateHardwareCheckResultsRequest) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateHardwareCheckResultsRequest) HasHardwareCheckScriptData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HardwareCheckScriptData != nil
}

func (x *UpdateHardwareCheckResultsRequest) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

func (x *UpdateHardwareCheckResultsRequest) ClearHardwareCheckScriptData() {
	x.xxx_hidden_HardwareCheckScriptData = nil
}

type UpdateHardwareCheckResultsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The unique ID for a hardware check.
	HardwareCheckId *string
	// The data from the hardware check script
	HardwareCheckScriptData *HardwareCheckScriptData
}

func (b0 UpdateHardwareCheckResultsRequest_builder) Build() *UpdateHardwareCheckResultsRequest {
	m0 := &UpdateHardwareCheckResultsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	x.xxx_hidden_HardwareCheckScriptData = b.HardwareCheckScriptData
	return m0
}

type UpdateHardwareCheckResultsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHardwareCheckResultsResponse) Reset() {
	*x = UpdateHardwareCheckResultsResponse{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHardwareCheckResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHardwareCheckResultsResponse) ProtoMessage() {}

func (x *UpdateHardwareCheckResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateHardwareCheckResultsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateHardwareCheckResultsResponse_builder) Build() *UpdateHardwareCheckResultsResponse {
	m0 := &UpdateHardwareCheckResultsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type StreamHardwareCheckResultsRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId *string                `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	xxx_hidden_Count           uint64                 `protobuf:"varint,2,opt,name=count"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StreamHardwareCheckResultsRequest) Reset() {
	*x = StreamHardwareCheckResultsRequest{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHardwareCheckResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHardwareCheckResultsRequest) ProtoMessage() {}

func (x *StreamHardwareCheckResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamHardwareCheckResultsRequest) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *StreamHardwareCheckResultsRequest) GetCount() uint64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *StreamHardwareCheckResultsRequest) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StreamHardwareCheckResultsRequest) SetCount(v uint64) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StreamHardwareCheckResultsRequest) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamHardwareCheckResultsRequest) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StreamHardwareCheckResultsRequest) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

func (x *StreamHardwareCheckResultsRequest) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Count = 0
}

type StreamHardwareCheckResultsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Filter the response by a specific hardware check ID.
	//
	// If this is empty, then:
	//   - HardwareCheckResults for existing hardware checks will be streamed immediately
	//   - Up to `count` newest hardware check results will be returned
	//   - The stream will remain open
	//   - Any subsequent hardware check updates will also be streamed, including those for
	//     any hardware checks that are started after the `stream_hardware_check_results()`
	//     call was made.
	//
	// Otherwise, if this is non-empty, then:
	//   - The HardwareCheckResult for the corresponding hardware check will be returned
	//   - If that hardware check is still in progress, then the stream will remain open and
	//     any updates for that hardware check will be returned.
	//   - The stream will be closed if/when the specified hardware check finishes
	//   - This will be immediately after returning the first response if the hardware
	//     check was already finished when the call was made
	//   - If the specified `hardware_check_id` doesn't correspond to a valid hardware check,
	//     an INVALID_ARGUMENT status will be returned.
	HardwareCheckId *string
	// The maximum number of records to return initially
	//
	// Since HardwareCheckResults are returned newest-to-oldest, this provides a way to get
	// information only for the newest hardware checks
	//
	// (Note that subsequent updates will also be streamed, and so more than `count` responses may
	// be returned on the stream)
	//
	// If `count` is `0` (the default) then all matching records will be returned
	Count *uint64
}

func (b0 StreamHardwareCheckResultsRequest_builder) Build() *StreamHardwareCheckResultsRequest {
	m0 := &StreamHardwareCheckResultsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Count = *b.Count
	}
	return m0
}

// The data sent to the UI
type HardwareCheckResult struct {
	state                              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId         *string                  `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	xxx_hidden_StartTime               *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=start_time,json=startTime"`
	xxx_hidden_EndTime                 *timestamppb.Timestamp   `protobuf:"bytes,3,opt,name=end_time,json=endTime"`
	xxx_hidden_HardwareCheckScriptData *HardwareCheckScriptData `protobuf:"bytes,4,opt,name=hardware_check_script_data,json=hardwareCheckScriptData"`
	xxx_hidden_State                   HardwareCheckState       `protobuf:"varint,5,opt,name=state,enum=minknow_api.hardware_check.HardwareCheckState"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *HardwareCheckResult) Reset() {
	*x = HardwareCheckResult{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareCheckResult) ProtoMessage() {}

func (x *HardwareCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HardwareCheckResult) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *HardwareCheckResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *HardwareCheckResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndTime
	}
	return nil
}

func (x *HardwareCheckResult) GetHardwareCheckScriptData() *HardwareCheckScriptData {
	if x != nil {
		return x.xxx_hidden_HardwareCheckScriptData
	}
	return nil
}

func (x *HardwareCheckResult) GetState() HardwareCheckState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_State
		}
	}
	return HardwareCheckState_HARDWARE_CHECK_RUNNING
}

func (x *HardwareCheckResult) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *HardwareCheckResult) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *HardwareCheckResult) SetEndTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndTime = v
}

func (x *HardwareCheckResult) SetHardwareCheckScriptData(v *HardwareCheckScriptData) {
	x.xxx_hidden_HardwareCheckScriptData = v
}

func (x *HardwareCheckResult) SetState(v HardwareCheckState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *HardwareCheckResult) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HardwareCheckResult) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *HardwareCheckResult) HasEndTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndTime != nil
}

func (x *HardwareCheckResult) HasHardwareCheckScriptData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HardwareCheckScriptData != nil
}

func (x *HardwareCheckResult) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *HardwareCheckResult) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

func (x *HardwareCheckResult) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

func (x *HardwareCheckResult) ClearEndTime() {
	x.xxx_hidden_EndTime = nil
}

func (x *HardwareCheckResult) ClearHardwareCheckScriptData() {
	x.xxx_hidden_HardwareCheckScriptData = nil
}

func (x *HardwareCheckResult) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_State = HardwareCheckState_HARDWARE_CHECK_RUNNING
}

type HardwareCheckResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of this hardware check result.
	HardwareCheckId *string
	// The time (UTC) when the hardware check was started.
	StartTime *timestamppb.Timestamp
	// The time (UTC) when the hardware check completed.
	//
	// Unset if the check is still running.
	EndTime *timestamppb.Timestamp
	// The data from the hardware check script
	HardwareCheckScriptData *HardwareCheckScriptData
	// Indicates the current state of the hardware check run.
	State *HardwareCheckState
}

func (b0 HardwareCheckResult_builder) Build() *HardwareCheckResult {
	m0 := &HardwareCheckResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	x.xxx_hidden_StartTime = b.StartTime
	x.xxx_hidden_EndTime = b.EndTime
	x.xxx_hidden_HardwareCheckScriptData = b.HardwareCheckScriptData
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_State = *b.State
	}
	return m0
}

type StreamHardwareCheckResultsResponse struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckResult *HardwareCheckResult   `protobuf:"bytes,1,opt,name=hardware_check_result,json=hardwareCheckResult"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *StreamHardwareCheckResultsResponse) Reset() {
	*x = StreamHardwareCheckResultsResponse{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHardwareCheckResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHardwareCheckResultsResponse) ProtoMessage() {}

func (x *StreamHardwareCheckResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamHardwareCheckResultsResponse) GetHardwareCheckResult() *HardwareCheckResult {
	if x != nil {
		return x.xxx_hidden_HardwareCheckResult
	}
	return nil
}

func (x *StreamHardwareCheckResultsResponse) SetHardwareCheckResult(v *HardwareCheckResult) {
	x.xxx_hidden_HardwareCheckResult = v
}

func (x *StreamHardwareCheckResultsResponse) HasHardwareCheckResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HardwareCheckResult != nil
}

func (x *StreamHardwareCheckResultsResponse) ClearHardwareCheckResult() {
	x.xxx_hidden_HardwareCheckResult = nil
}

type StreamHardwareCheckResultsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Returns the hardware check results.
	//
	// If no ID is provided, returns persisted hardware check results, if persisted results exist.
	// It will then stay connected, and any newly started hardware checks, triggered via
	// `start_hardware_check`, will be sent individually, as well as any progress updates.
	//
	// If an ID is provided for a persisted record, it will return the result and end.
	// If an ID is provided for the current hardware check, it will stay connected for new updates
	// and end when the check is completed.
	//
	// Each result will be returned individually.
	HardwareCheckResult *HardwareCheckResult
}

func (b0 StreamHardwareCheckResultsResponse_builder) Build() *StreamHardwareCheckResultsResponse {
	m0 := &StreamHardwareCheckResultsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HardwareCheckResult = b.HardwareCheckResult
	return m0
}

type GenerateHardwareCheckReportRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId *string                `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GenerateHardwareCheckReportRequest) Reset() {
	*x = GenerateHardwareCheckReportRequest{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHardwareCheckReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHardwareCheckReportRequest) ProtoMessage() {}

func (x *GenerateHardwareCheckReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenerateHardwareCheckReportRequest) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *GenerateHardwareCheckReportRequest) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GenerateHardwareCheckReportRequest) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenerateHardwareCheckReportRequest) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

type GenerateHardwareCheckReportRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the hardware check to generate a report for.
	HardwareCheckId *string
}

func (b0 GenerateHardwareCheckReportRequest_builder) Build() *GenerateHardwareCheckReportRequest {
	m0 := &GenerateHardwareCheckReportRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	return m0
}

type GenerateHardwareCheckReportResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HardwareCheckId *string                `protobuf:"bytes,1,opt,name=hardware_check_id,json=hardwareCheckId"`
	xxx_hidden_ReportData      *string                `protobuf:"bytes,2,opt,name=report_data,json=reportData"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GenerateHardwareCheckReportResponse) Reset() {
	*x = GenerateHardwareCheckReportResponse{}
	mi := &file_minknow_api_hardware_check_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHardwareCheckReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHardwareCheckReportResponse) ProtoMessage() {}

func (x *GenerateHardwareCheckReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_hardware_check_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenerateHardwareCheckReportResponse) GetHardwareCheckId() string {
	if x != nil {
		if x.xxx_hidden_HardwareCheckId != nil {
			return *x.xxx_hidden_HardwareCheckId
		}
		return ""
	}
	return ""
}

func (x *GenerateHardwareCheckReportResponse) GetReportData() string {
	if x != nil {
		if x.xxx_hidden_ReportData != nil {
			return *x.xxx_hidden_ReportData
		}
		return ""
	}
	return ""
}

func (x *GenerateHardwareCheckReportResponse) SetHardwareCheckId(v string) {
	x.xxx_hidden_HardwareCheckId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GenerateHardwareCheckReportResponse) SetReportData(v string) {
	x.xxx_hidden_ReportData = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GenerateHardwareCheckReportResponse) HasHardwareCheckId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenerateHardwareCheckReportResponse) HasReportData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GenerateHardwareCheckReportResponse) ClearHardwareCheckId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HardwareCheckId = nil
}

func (x *GenerateHardwareCheckReportResponse) ClearReportData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ReportData = nil
}

type GenerateHardwareCheckReportResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the hardware check the report is for.
	HardwareCheckId *string
	// A section of the hardware check report data (note the api to return this data may stream back several sections).
	ReportData *string
}

func (b0 GenerateHardwareCheckReportResponse_builder) Build() *GenerateHardwareCheckReportResponse {
	m0 := &GenerateHardwareCheckReportResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HardwareCheckId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_HardwareCheckId = b.HardwareCheckId
	}
	if b.ReportData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ReportData = b.ReportData
	}
	return m0
}

var File_minknow_api_hardware_check_proto protoreflect.FileDescriptor

const file_minknow_api_hardware_check_proto_rawDesc = "" +
	"\n" +
	" minknow_api/hardware_check.proto\x12\x1aminknow_api.hardware_check\x1a\x18minknow_api/device.proto\x1a\x1aminknow_api/protocol.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x19StartHardwareCheckRequest\x12!\n" +
	"\fposition_ids\x18\x01 \x03(\tR\vpositionIds\"H\n" +
	"\x1aStartHardwareCheckResponse\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\"F\n" +
	"\x18StopHardwareCheckRequest\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\"\x1b\n" +
	"\x19StopHardwareCheckResponse\"\x8b\x02\n" +
	"\x13PositionCheckResult\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12U\n" +
	"\vdevice_type\x18\x02 \x01(\x0e24.minknow_api.device.GetDeviceInfoResponse.DeviceTypeR\n" +
	"deviceType\x12]\n" +
	"\x15hardware_check_result\x18\x03 \x01(\v2).minknow_api.protocol.HardwareCheckResultR\x13hardwareCheckResult\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x04 \x01(\tR\tadapterId\"\xae\x02\n" +
	"\x17HardwareCheckScriptData\x12e\n" +
	"\x16position_check_results\x18\x01 \x03(\v2/.minknow_api.hardware_check.PositionCheckResultR\x14positionCheckResults\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\rR\x0fprogressPercent\x120\n" +
	"\x14progress_eta_seconds\x18\x03 \x01(\rR\x12progressEtaSeconds\x12%\n" +
	"\x0eoverall_result\x18\x05 \x01(\bR\roverallResult\x12(\n" +
	"\x10protocol_run_ids\x18\x06 \x03(\tR\x0eprotocolRunIds\"\xc1\x01\n" +
	"!UpdateHardwareCheckResultsRequest\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\x12p\n" +
	"\x1ahardware_check_script_data\x18\x02 \x01(\v23.minknow_api.hardware_check.HardwareCheckScriptDataR\x17hardwareCheckScriptData\"$\n" +
	"\"UpdateHardwareCheckResultsResponse\"e\n" +
	"!StreamHardwareCheckResultsRequest\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xeb\x02\n" +
	"\x13HardwareCheckResult\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12p\n" +
	"\x1ahardware_check_script_data\x18\x04 \x01(\v23.minknow_api.hardware_check.HardwareCheckScriptDataR\x17hardwareCheckScriptData\x12D\n" +
	"\x05state\x18\x05 \x01(\x0e2..minknow_api.hardware_check.HardwareCheckStateR\x05state\"\x89\x01\n" +
	"\"StreamHardwareCheckResultsResponse\x12c\n" +
	"\x15hardware_check_result\x18\x01 \x01(\v2/.minknow_api.hardware_check.HardwareCheckResultR\x13hardwareCheckResult\"P\n" +
	"\"GenerateHardwareCheckReportRequest\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\"r\n" +
	"#GenerateHardwareCheckReportResponse\x12*\n" +
	"\x11hardware_check_id\x18\x01 \x01(\tR\x0fhardwareCheckId\x12\x1f\n" +
	"\vreport_data\x18\x02 \x01(\tR\n" +
	"reportData*\xe3\x02\n" +
	"\x12HardwareCheckState\x12\x1a\n" +
	"\x16HARDWARE_CHECK_RUNNING\x10\x00\x12\x1c\n" +
	"\x18HARDWARE_CHECK_COMPLETED\x10\x01\x12\x1a\n" +
	"\x16HARDWARE_CHECK_STOPPED\x10\x02\x12A\n" +
	"=HARDWARE_CHECK_FINISHED_WITH_ERROR_COULD_NOT_OBTAIN_EXIT_CODE\x10\x03\x12D\n" +
	"@HARDWARE_CHECK_FINISHED_WITH_ERROR_PYTHON_EXECUTOR_DID_NOT_START\x10\x04\x128\n" +
	"4HARDWARE_CHECK_FINISHED_WITH_ERROR_SCRIPT_ERROR_CODE\x10\x05\x124\n" +
	"0HARDWARE_CHECK_FINISHED_WITH_ERROR_LINGERING_RUN\x10\x062\xa6\x06\n" +
	"\x14HardwareCheckService\x12\x8a\x01\n" +
	"\x14start_hardware_check\x125.minknow_api.hardware_check.StartHardwareCheckRequest\x1a6.minknow_api.hardware_check.StartHardwareCheckResponse\"\x03\x90\x02\x02\x12\x87\x01\n" +
	"\x13stop_hardware_check\x124.minknow_api.hardware_check.StopHardwareCheckRequest\x1a5.minknow_api.hardware_check.StopHardwareCheckResponse\"\x03\x90\x02\x02\x12\xa3\x01\n" +
	"\x1dupdate_hardware_check_results\x12=.minknow_api.hardware_check.UpdateHardwareCheckResultsRequest\x1a>.minknow_api.hardware_check.UpdateHardwareCheckResultsResponse\"\x03\x90\x02\x02\x12\xa5\x01\n" +
	"\x1dstream_hardware_check_results\x12=.minknow_api.hardware_check.StreamHardwareCheckResultsRequest\x1a>.minknow_api.hardware_check.StreamHardwareCheckResultsResponse\"\x03\x90\x02\x010\x01\x12\xa8\x01\n" +
	"\x1egenerate_hardware_check_report\x12>.minknow_api.hardware_check.GenerateHardwareCheckReportRequest\x1a?.minknow_api.hardware_check.GenerateHardwareCheckReportResponse\"\x03\x90\x02\x020\x01Bd\n" +
	"\x1ccom.nanoporetech.minknow_apiZ9github.com/nanoporetech/minknow_api/go/gen/hardware_check\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_hardware_check_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minknow_api_hardware_check_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_minknow_api_hardware_check_proto_goTypes = []any{
	(HardwareCheckState)(0),                      // 0: minknow_api.hardware_check.HardwareCheckState
	(*StartHardwareCheckRequest)(nil),            // 1: minknow_api.hardware_check.StartHardwareCheckRequest
	(*StartHardwareCheckResponse)(nil),           // 2: minknow_api.hardware_check.StartHardwareCheckResponse
	(*StopHardwareCheckRequest)(nil),             // 3: minknow_api.hardware_check.StopHardwareCheckRequest
	(*StopHardwareCheckResponse)(nil),            // 4: minknow_api.hardware_check.StopHardwareCheckResponse
	(*PositionCheckResult)(nil),                  // 5: minknow_api.hardware_check.PositionCheckResult
	(*HardwareCheckScriptData)(nil),              // 6: minknow_api.hardware_check.HardwareCheckScriptData
	(*UpdateHardwareCheckResultsRequest)(nil),    // 7: minknow_api.hardware_check.UpdateHardwareCheckResultsRequest
	(*UpdateHardwareCheckResultsResponse)(nil),   // 8: minknow_api.hardware_check.UpdateHardwareCheckResultsResponse
	(*StreamHardwareCheckResultsRequest)(nil),    // 9: minknow_api.hardware_check.StreamHardwareCheckResultsRequest
	(*HardwareCheckResult)(nil),                  // 10: minknow_api.hardware_check.HardwareCheckResult
	(*StreamHardwareCheckResultsResponse)(nil),   // 11: minknow_api.hardware_check.StreamHardwareCheckResultsResponse
	(*GenerateHardwareCheckReportRequest)(nil),   // 12: minknow_api.hardware_check.GenerateHardwareCheckReportRequest
	(*GenerateHardwareCheckReportResponse)(nil),  // 13: minknow_api.hardware_check.GenerateHardwareCheckReportResponse
	(device.GetDeviceInfoResponse_DeviceType)(0), // 14: minknow_api.device.GetDeviceInfoResponse.DeviceType
	(*protocol.HardwareCheckResult)(nil),         // 15: minknow_api.protocol.HardwareCheckResult
	(*timestamppb.Timestamp)(nil),                // 16: google.protobuf.Timestamp
}
var file_minknow_api_hardware_check_proto_depIdxs = []int32{
	14, // 0: minknow_api.hardware_check.PositionCheckResult.device_type:type_name -> minknow_api.device.GetDeviceInfoResponse.DeviceType
	15, // 1: minknow_api.hardware_check.PositionCheckResult.hardware_check_result:type_name -> minknow_api.protocol.HardwareCheckResult
	5,  // 2: minknow_api.hardware_check.HardwareCheckScriptData.position_check_results:type_name -> minknow_api.hardware_check.PositionCheckResult
	6,  // 3: minknow_api.hardware_check.UpdateHardwareCheckResultsRequest.hardware_check_script_data:type_name -> minknow_api.hardware_check.HardwareCheckScriptData
	16, // 4: minknow_api.hardware_check.HardwareCheckResult.start_time:type_name -> google.protobuf.Timestamp
	16, // 5: minknow_api.hardware_check.HardwareCheckResult.end_time:type_name -> google.protobuf.Timestamp
	6,  // 6: minknow_api.hardware_check.HardwareCheckResult.hardware_check_script_data:type_name -> minknow_api.hardware_check.HardwareCheckScriptData
	0,  // 7: minknow_api.hardware_check.HardwareCheckResult.state:type_name -> minknow_api.hardware_check.HardwareCheckState
	10, // 8: minknow_api.hardware_check.StreamHardwareCheckResultsResponse.hardware_check_result:type_name -> minknow_api.hardware_check.HardwareCheckResult
	1,  // 9: minknow_api.hardware_check.HardwareCheckService.start_hardware_check:input_type -> minknow_api.hardware_check.StartHardwareCheckRequest
	3,  // 10: minknow_api.hardware_check.HardwareCheckService.stop_hardware_check:input_type -> minknow_api.hardware_check.StopHardwareCheckRequest
	7,  // 11: minknow_api.hardware_check.HardwareCheckService.update_hardware_check_results:input_type -> minknow_api.hardware_check.UpdateHardwareCheckResultsRequest
	9,  // 12: minknow_api.hardware_check.HardwareCheckService.stream_hardware_check_results:input_type -> minknow_api.hardware_check.StreamHardwareCheckResultsRequest
	12, // 13: minknow_api.hardware_check.HardwareCheckService.generate_hardware_check_report:input_type -> minknow_api.hardware_check.GenerateHardwareCheckReportRequest
	2,  // 14: minknow_api.hardware_check.HardwareCheckService.start_hardware_check:output_type -> minknow_api.hardware_check.StartHardwareCheckResponse
	4,  // 15: minknow_api.hardware_check.HardwareCheckService.stop_hardware_check:output_type -> minknow_api.hardware_check.StopHardwareCheckResponse
	8,  // 16: minknow_api.hardware_check.HardwareCheckService.update_hardware_check_results:output_type -> minknow_api.hardware_check.UpdateHardwareCheckResultsResponse
	11, // 17: minknow_api.hardware_check.HardwareCheckService.stream_hardware_check_results:output_type -> minknow_api.hardware_check.StreamHardwareCheckResultsResponse
	13, // 18: minknow_api.hardware_check.HardwareCheckService.generate_hardware_check_report:output_type -> minknow_api.hardware_check.GenerateHardwareCheckReportResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_minknow_api_hardware_check_proto_init() }
func file_minknow_api_hardware_check_proto_init() {
	if File_minknow_api_hardware_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_hardware_check_proto_rawDesc), len(file_minknow_api_hardware_check_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_hardware_check_proto_goTypes,
		DependencyIndexes: file_minknow_api_hardware_check_proto_depIdxs,
		EnumInfos:         file_minknow_api_hardware_check_proto_enumTypes,
		MessageInfos:      file_minknow_api_hardware_check_proto_msgTypes,
	}.Build()
	File_minknow_api_hardware_check_proto = out.File
	file_minknow_api_hardware_check_proto_goTypes = nil
	file_minknow_api_hardware_check_proto_depIdxs = nil
}
