// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/instance.proto

package instance

import (
	acquisition "github.com/nanoporetech/minknow_api/go/gen/acquisition"
	device "github.com/nanoporetech/minknow_api/go/gen/device"
	protocol "github.com/nanoporetech/minknow_api/go/gen/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionInfoResponse_DistributionStatus int32

const (
	GetVersionInfoResponse_UNKNOWN GetVersionInfoResponse_DistributionStatus = 0 // The distribution status is unknown or can not be determined
	GetVersionInfoResponse_STABLE  GetVersionInfoResponse_DistributionStatus = 1 // Released software in that same configuration in which
	// it was distributed.
	GetVersionInfoResponse_UNSTABLE GetVersionInfoResponse_DistributionStatus = 2 // Pre-release or release-candidate software that has not
	// been fully tested, but has not been modified from how it
	// was distributed.
	GetVersionInfoResponse_MODIFIED GetVersionInfoResponse_DistributionStatus = 3 // Some or all components have been replaced after distribution
)

// Enum value maps for GetVersionInfoResponse_DistributionStatus.
var (
	GetVersionInfoResponse_DistributionStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "STABLE",
		2: "UNSTABLE",
		3: "MODIFIED",
	}
	GetVersionInfoResponse_DistributionStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"STABLE":   1,
		"UNSTABLE": 2,
		"MODIFIED": 3,
	}
)

func (x GetVersionInfoResponse_DistributionStatus) Enum() *GetVersionInfoResponse_DistributionStatus {
	p := new(GetVersionInfoResponse_DistributionStatus)
	*p = x
	return p
}

func (x GetVersionInfoResponse_DistributionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetVersionInfoResponse_DistributionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_instance_proto_enumTypes[0].Descriptor()
}

func (GetVersionInfoResponse_DistributionStatus) Type() protoreflect.EnumType {
	return &file_minknow_api_instance_proto_enumTypes[0]
}

func (x GetVersionInfoResponse_DistributionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GetVersionInfoResponse_InstallationType int32

const (
	// For internal release. production.proto will be enabled for this type
	GetVersionInfoResponse_ONT GetVersionInfoResponse_InstallationType = 0
	// For customer releases
	GetVersionInfoResponse_NC GetVersionInfoResponse_InstallationType = 1
	// For production release. production.proto will be enabled for this type
	GetVersionInfoResponse_PROD GetVersionInfoResponse_InstallationType = 2
	// For Q releases (nanopore long term support release)
	GetVersionInfoResponse_Q_RELEASE GetVersionInfoResponse_InstallationType = 3
	// Oxford Nanopore Diagnostic
	GetVersionInfoResponse_OND_RELEASE GetVersionInfoResponse_InstallationType = 4
)

// Enum value maps for GetVersionInfoResponse_InstallationType.
var (
	GetVersionInfoResponse_InstallationType_name = map[int32]string{
		0: "ONT",
		1: "NC",
		2: "PROD",
		3: "Q_RELEASE",
		4: "OND_RELEASE",
	}
	GetVersionInfoResponse_InstallationType_value = map[string]int32{
		"ONT":         0,
		"NC":          1,
		"PROD":        2,
		"Q_RELEASE":   3,
		"OND_RELEASE": 4,
	}
)

func (x GetVersionInfoResponse_InstallationType) Enum() *GetVersionInfoResponse_InstallationType {
	p := new(GetVersionInfoResponse_InstallationType)
	*p = x
	return p
}

func (x GetVersionInfoResponse_InstallationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetVersionInfoResponse_InstallationType) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_instance_proto_enumTypes[1].Descriptor()
}

func (GetVersionInfoResponse_InstallationType) Type() protoreflect.EnumType {
	return &file_minknow_api_instance_proto_enumTypes[1]
}

func (x GetVersionInfoResponse_InstallationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GetVersionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionInfoRequest) Reset() {
	*x = GetVersionInfoRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionInfoRequest) ProtoMessage() {}

func (x *GetVersionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetVersionInfoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetVersionInfoRequest_builder) Build() *GetVersionInfoRequest {
	m0 := &GetVersionInfoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetVersionInfoResponse struct {
	state                                 protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_Minknow                    *GetVersionInfoResponse_MinknowVersion    `protobuf:"bytes,1,opt,name=minknow"`
	xxx_hidden_Bream                      *string                                   `protobuf:"bytes,2,opt,name=bream"`
	xxx_hidden_DistributionVersion        *string                                   `protobuf:"bytes,3,opt,name=distribution_version,json=distributionVersion"`
	xxx_hidden_DistributionStatus         GetVersionInfoResponse_DistributionStatus `protobuf:"varint,4,opt,name=distribution_status,json=distributionStatus,enum=minknow_api.instance.GetVersionInfoResponse_DistributionStatus"`
	xxx_hidden_ProtocolConfiguration      *string                                   `protobuf:"bytes,5,opt,name=protocol_configuration,json=protocolConfiguration"`
	xxx_hidden_InstallationType           GetVersionInfoResponse_InstallationType   `protobuf:"varint,6,opt,name=installation_type,json=installationType,enum=minknow_api.instance.GetVersionInfoResponse_InstallationType"`
	xxx_hidden_BasecallerBuildVersion     *string                                   `protobuf:"bytes,9,opt,name=basecaller_build_version,json=basecallerBuildVersion"`
	xxx_hidden_BasecallerConnectedVersion *string                                   `protobuf:"bytes,10,opt,name=basecaller_connected_version,json=basecallerConnectedVersion"`
	XXX_raceDetectHookData                protoimpl.RaceDetectHookData
	XXX_presence                          [1]uint32
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *GetVersionInfoResponse) Reset() {
	*x = GetVersionInfoResponse{}
	mi := &file_minknow_api_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionInfoResponse) ProtoMessage() {}

func (x *GetVersionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetVersionInfoResponse) GetMinknow() *GetVersionInfoResponse_MinknowVersion {
	if x != nil {
		return x.xxx_hidden_Minknow
	}
	return nil
}

func (x *GetVersionInfoResponse) GetBream() string {
	if x != nil {
		if x.xxx_hidden_Bream != nil {
			return *x.xxx_hidden_Bream
		}
		return ""
	}
	return ""
}

func (x *GetVersionInfoResponse) GetDistributionVersion() string {
	if x != nil {
		if x.xxx_hidden_DistributionVersion != nil {
			return *x.xxx_hidden_DistributionVersion
		}
		return ""
	}
	return ""
}

func (x *GetVersionInfoResponse) GetDistributionStatus() GetVersionInfoResponse_DistributionStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_DistributionStatus
		}
	}
	return GetVersionInfoResponse_UNKNOWN
}

func (x *GetVersionInfoResponse) GetProtocolConfiguration() string {
	if x != nil {
		if x.xxx_hidden_ProtocolConfiguration != nil {
			return *x.xxx_hidden_ProtocolConfiguration
		}
		return ""
	}
	return ""
}

func (x *GetVersionInfoResponse) GetInstallationType() GetVersionInfoResponse_InstallationType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_InstallationType
		}
	}
	return GetVersionInfoResponse_ONT
}

func (x *GetVersionInfoResponse) GetBasecallerBuildVersion() string {
	if x != nil {
		if x.xxx_hidden_BasecallerBuildVersion != nil {
			return *x.xxx_hidden_BasecallerBuildVersion
		}
		return ""
	}
	return ""
}

func (x *GetVersionInfoResponse) GetBasecallerConnectedVersion() string {
	if x != nil {
		if x.xxx_hidden_BasecallerConnectedVersion != nil {
			return *x.xxx_hidden_BasecallerConnectedVersion
		}
		return ""
	}
	return ""
}

func (x *GetVersionInfoResponse) SetMinknow(v *GetVersionInfoResponse_MinknowVersion) {
	x.xxx_hidden_Minknow = v
}

func (x *GetVersionInfoResponse) SetBream(v string) {
	x.xxx_hidden_Bream = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *GetVersionInfoResponse) SetDistributionVersion(v string) {
	x.xxx_hidden_DistributionVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *GetVersionInfoResponse) SetDistributionStatus(v GetVersionInfoResponse_DistributionStatus) {
	x.xxx_hidden_DistributionStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *GetVersionInfoResponse) SetProtocolConfiguration(v string) {
	x.xxx_hidden_ProtocolConfiguration = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *GetVersionInfoResponse) SetInstallationType(v GetVersionInfoResponse_InstallationType) {
	x.xxx_hidden_InstallationType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *GetVersionInfoResponse) SetBasecallerBuildVersion(v string) {
	x.xxx_hidden_BasecallerBuildVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *GetVersionInfoResponse) SetBasecallerConnectedVersion(v string) {
	x.xxx_hidden_BasecallerConnectedVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *GetVersionInfoResponse) HasMinknow() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Minknow != nil
}

func (x *GetVersionInfoResponse) HasBream() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetVersionInfoResponse) HasDistributionVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetVersionInfoResponse) HasDistributionStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetVersionInfoResponse) HasProtocolConfiguration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GetVersionInfoResponse) HasInstallationType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GetVersionInfoResponse) HasBasecallerBuildVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *GetVersionInfoResponse) HasBasecallerConnectedVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *GetVersionInfoResponse) ClearMinknow() {
	x.xxx_hidden_Minknow = nil
}

func (x *GetVersionInfoResponse) ClearBream() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Bream = nil
}

func (x *GetVersionInfoResponse) ClearDistributionVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_DistributionVersion = nil
}

func (x *GetVersionInfoResponse) ClearDistributionStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_DistributionStatus = GetVersionInfoResponse_UNKNOWN
}

func (x *GetVersionInfoResponse) ClearProtocolConfiguration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ProtocolConfiguration = nil
}

func (x *GetVersionInfoResponse) ClearInstallationType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_InstallationType = GetVersionInfoResponse_ONT
}

func (x *GetVersionInfoResponse) ClearBasecallerBuildVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_BasecallerBuildVersion = nil
}

func (x *GetVersionInfoResponse) ClearBasecallerConnectedVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_BasecallerConnectedVersion = nil
}

type GetVersionInfoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What minknow version is installed. Split into major, minor and patch versions
	// Also includes the full version as a string, which contain the major, minor and patch numbers
	// as well as if the version is pre-release version (~pre), whether it is a release candidate (~rc#)
	// or whether it is a variant version (i.e. for conferences) (-variant). For non-release builds it also
	// includes the hash of the commit it is based on, and whether the working copy is different from that has (-dirty)
	Minknow *GetVersionInfoResponse_MinknowVersion
	// The version of Bream that is installed.
	//
	// An invalid installation will cause this to return "0.0.0".
	//
	// Prior to 5.0, this field was called "protocols".
	//
	// Since 5.0
	Bream *string
	// Describes the distribution that this MinKNOW installation is part of, usually
	// this will be the Metapackage version number/identity, this will be "unknown"
	// if the distribution-version hasn't been set. This information is also communicated
	// in the Manager's DaemonMessage in daemon.proto
	DistributionVersion *string
	// Indicates if the MinKNOW distribution including components such as Bream
	// are stable, unstable or have been modified.
	DistributionStatus *GetVersionInfoResponse_DistributionStatus
	// The version of the protocol configuration files that is installed.
	//
	// An invalid installation will cause this to return "0.0.0".
	//
	// Prior to 5.0, this field was called "configuration".
	//
	// Since 5.0
	ProtocolConfiguration *string
	// The installation type of MinKNOW.
	//
	// The installation type may affect the available features, or the update process.
	//
	// Since 4.1
	InstallationType           *GetVersionInfoResponse_InstallationType
	BasecallerBuildVersion     *string
	BasecallerConnectedVersion *string
}

func (b0 GetVersionInfoResponse_builder) Build() *GetVersionInfoResponse {
	m0 := &GetVersionInfoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Minknow = b.Minknow
	if b.Bream != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Bream = b.Bream
	}
	if b.DistributionVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_DistributionVersion = b.DistributionVersion
	}
	if b.DistributionStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_DistributionStatus = *b.DistributionStatus
	}
	if b.ProtocolConfiguration != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_ProtocolConfiguration = b.ProtocolConfiguration
	}
	if b.InstallationType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_InstallationType = *b.InstallationType
	}
	if b.BasecallerBuildVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_BasecallerBuildVersion = b.BasecallerBuildVersion
	}
	if b.BasecallerConnectedVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_BasecallerConnectedVersion = b.BasecallerConnectedVersion
	}
	return m0
}

type GetOutputDirectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutputDirectoriesRequest) Reset() {
	*x = GetOutputDirectoriesRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutputDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutputDirectoriesRequest) ProtoMessage() {}

func (x *GetOutputDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetOutputDirectoriesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetOutputDirectoriesRequest_builder) Build() *GetOutputDirectoriesRequest {
	m0 := &GetOutputDirectoriesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type OutputDirectories struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Output      *string                `protobuf:"bytes,1,opt,name=output"`
	xxx_hidden_Log         *string                `protobuf:"bytes,2,opt,name=log"`
	xxx_hidden_Reads       *string                `protobuf:"bytes,3,opt,name=reads"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OutputDirectories) Reset() {
	*x = OutputDirectories{}
	mi := &file_minknow_api_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputDirectories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputDirectories) ProtoMessage() {}

func (x *OutputDirectories) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OutputDirectories) GetOutput() string {
	if x != nil {
		if x.xxx_hidden_Output != nil {
			return *x.xxx_hidden_Output
		}
		return ""
	}
	return ""
}

func (x *OutputDirectories) GetLog() string {
	if x != nil {
		if x.xxx_hidden_Log != nil {
			return *x.xxx_hidden_Log
		}
		return ""
	}
	return ""
}

func (x *OutputDirectories) GetReads() string {
	if x != nil {
		if x.xxx_hidden_Reads != nil {
			return *x.xxx_hidden_Reads
		}
		return ""
	}
	return ""
}

func (x *OutputDirectories) SetOutput(v string) {
	x.xxx_hidden_Output = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *OutputDirectories) SetLog(v string) {
	x.xxx_hidden_Log = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *OutputDirectories) SetReads(v string) {
	x.xxx_hidden_Reads = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *OutputDirectories) HasOutput() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OutputDirectories) HasLog() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OutputDirectories) HasReads() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OutputDirectories) ClearOutput() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Output = nil
}

func (x *OutputDirectories) ClearLog() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Log = nil
}

func (x *OutputDirectories) ClearReads() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Reads = nil
}

type OutputDirectories_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The base output directory. Anything that is output to files is branched from this directory.
	Output *string
	// Directory where logs will be stored.
	Log *string
	// Base directory where reads will be outputted.
	Reads *string
}

func (b0 OutputDirectories_builder) Build() *OutputDirectories {
	m0 := &OutputDirectories{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Output != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Output = b.Output
	}
	if b.Log != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Log = b.Log
	}
	if b.Reads != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Reads = b.Reads
	}
	return m0
}

type GetDefaultOutputDirectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultOutputDirectoriesRequest) Reset() {
	*x = GetDefaultOutputDirectoriesRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultOutputDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultOutputDirectoriesRequest) ProtoMessage() {}

func (x *GetDefaultOutputDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetDefaultOutputDirectoriesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetDefaultOutputDirectoriesRequest_builder) Build() *GetDefaultOutputDirectoriesRequest {
	m0 := &GetDefaultOutputDirectoriesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetOutputDirectoryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,1,opt,name=path"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetOutputDirectoryRequest) Reset() {
	*x = SetOutputDirectoryRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputDirectoryRequest) ProtoMessage() {}

func (x *SetOutputDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetOutputDirectoryRequest) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *SetOutputDirectoryRequest) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SetOutputDirectoryRequest) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetOutputDirectoryRequest) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

type SetOutputDirectoryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path *string
}

func (b0 SetOutputDirectoryRequest_builder) Build() *SetOutputDirectoryRequest {
	m0 := &SetOutputDirectoryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Path = b.Path
	}
	return m0
}

type SetOutputDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutputDirectoryResponse) Reset() {
	*x = SetOutputDirectoryResponse{}
	mi := &file_minknow_api_instance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputDirectoryResponse) ProtoMessage() {}

func (x *SetOutputDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetOutputDirectoryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetOutputDirectoryResponse_builder) Build() *SetOutputDirectoryResponse {
	m0 := &SetOutputDirectoryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetReadsDirectoryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,1,opt,name=path"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetReadsDirectoryRequest) Reset() {
	*x = SetReadsDirectoryRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadsDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadsDirectoryRequest) ProtoMessage() {}

func (x *SetReadsDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetReadsDirectoryRequest) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *SetReadsDirectoryRequest) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SetReadsDirectoryRequest) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetReadsDirectoryRequest) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

type SetReadsDirectoryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path *string
}

func (b0 SetReadsDirectoryRequest_builder) Build() *SetReadsDirectoryRequest {
	m0 := &SetReadsDirectoryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Path = b.Path
	}
	return m0
}

type SetReadsDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReadsDirectoryResponse) Reset() {
	*x = SetReadsDirectoryResponse{}
	mi := &file_minknow_api_instance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadsDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadsDirectoryResponse) ProtoMessage() {}

func (x *SetReadsDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetReadsDirectoryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetReadsDirectoryResponse_builder) Build() *SetReadsDirectoryResponse {
	m0 := &SetReadsDirectoryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// disk-usage information for one file-system
type FilesystemDiskSpaceInfo struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FilesystemId         *string                `protobuf:"bytes,1,opt,name=filesystem_id,json=filesystemId"`
	xxx_hidden_BytesAvailable       uint64                 `protobuf:"varint,2,opt,name=bytes_available,json=bytesAvailable"`
	xxx_hidden_BytesCapacity        uint64                 `protobuf:"varint,3,opt,name=bytes_capacity,json=bytesCapacity"`
	xxx_hidden_What                 []string               `protobuf:"bytes,4,rep,name=what"`
	xxx_hidden_BytesToStopCleanly   uint64                 `protobuf:"varint,5,opt,name=bytes_to_stop_cleanly,json=bytesToStopCleanly"`
	xxx_hidden_BytesWhenAlertIssued uint64                 `protobuf:"varint,6,opt,name=bytes_when_alert_issued,json=bytesWhenAlertIssued"`
	xxx_hidden_RecommendAlert       bool                   `protobuf:"varint,7,opt,name=recommend_alert,json=recommendAlert"`
	xxx_hidden_RecommendStop        bool                   `protobuf:"varint,8,opt,name=recommend_stop,json=recommendStop"`
	xxx_hidden_BytesPerSecond       int64                  `protobuf:"varint,9,opt,name=bytes_per_second,json=bytesPerSecond"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *FilesystemDiskSpaceInfo) Reset() {
	*x = FilesystemDiskSpaceInfo{}
	mi := &file_minknow_api_instance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemDiskSpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemDiskSpaceInfo) ProtoMessage() {}

func (x *FilesystemDiskSpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FilesystemDiskSpaceInfo) GetFilesystemId() string {
	if x != nil {
		if x.xxx_hidden_FilesystemId != nil {
			return *x.xxx_hidden_FilesystemId
		}
		return ""
	}
	return ""
}

func (x *FilesystemDiskSpaceInfo) GetBytesAvailable() uint64 {
	if x != nil {
		return x.xxx_hidden_BytesAvailable
	}
	return 0
}

func (x *FilesystemDiskSpaceInfo) GetBytesCapacity() uint64 {
	if x != nil {
		return x.xxx_hidden_BytesCapacity
	}
	return 0
}

func (x *FilesystemDiskSpaceInfo) GetWhat() []string {
	if x != nil {
		return x.xxx_hidden_What
	}
	return nil
}

func (x *FilesystemDiskSpaceInfo) GetBytesToStopCleanly() uint64 {
	if x != nil {
		return x.xxx_hidden_BytesToStopCleanly
	}
	return 0
}

func (x *FilesystemDiskSpaceInfo) GetBytesWhenAlertIssued() uint64 {
	if x != nil {
		return x.xxx_hidden_BytesWhenAlertIssued
	}
	return 0
}

func (x *FilesystemDiskSpaceInfo) GetRecommendAlert() bool {
	if x != nil {
		return x.xxx_hidden_RecommendAlert
	}
	return false
}

func (x *FilesystemDiskSpaceInfo) GetRecommendStop() bool {
	if x != nil {
		return x.xxx_hidden_RecommendStop
	}
	return false
}

func (x *FilesystemDiskSpaceInfo) GetBytesPerSecond() int64 {
	if x != nil {
		return x.xxx_hidden_BytesPerSecond
	}
	return 0
}

func (x *FilesystemDiskSpaceInfo) SetFilesystemId(v string) {
	x.xxx_hidden_FilesystemId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *FilesystemDiskSpaceInfo) SetBytesAvailable(v uint64) {
	x.xxx_hidden_BytesAvailable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *FilesystemDiskSpaceInfo) SetBytesCapacity(v uint64) {
	x.xxx_hidden_BytesCapacity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *FilesystemDiskSpaceInfo) SetWhat(v []string) {
	x.xxx_hidden_What = v
}

func (x *FilesystemDiskSpaceInfo) SetBytesToStopCleanly(v uint64) {
	x.xxx_hidden_BytesToStopCleanly = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *FilesystemDiskSpaceInfo) SetBytesWhenAlertIssued(v uint64) {
	x.xxx_hidden_BytesWhenAlertIssued = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *FilesystemDiskSpaceInfo) SetRecommendAlert(v bool) {
	x.xxx_hidden_RecommendAlert = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *FilesystemDiskSpaceInfo) SetRecommendStop(v bool) {
	x.xxx_hidden_RecommendStop = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *FilesystemDiskSpaceInfo) SetBytesPerSecond(v int64) {
	x.xxx_hidden_BytesPerSecond = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *FilesystemDiskSpaceInfo) HasFilesystemId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FilesystemDiskSpaceInfo) HasBytesAvailable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FilesystemDiskSpaceInfo) HasBytesCapacity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FilesystemDiskSpaceInfo) HasBytesToStopCleanly() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *FilesystemDiskSpaceInfo) HasBytesWhenAlertIssued() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *FilesystemDiskSpaceInfo) HasRecommendAlert() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *FilesystemDiskSpaceInfo) HasRecommendStop() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *FilesystemDiskSpaceInfo) HasBytesPerSecond() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *FilesystemDiskSpaceInfo) ClearFilesystemId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FilesystemId = nil
}

func (x *FilesystemDiskSpaceInfo) ClearBytesAvailable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BytesAvailable = 0
}

func (x *FilesystemDiskSpaceInfo) ClearBytesCapacity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_BytesCapacity = 0
}

func (x *FilesystemDiskSpaceInfo) ClearBytesToStopCleanly() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_BytesToStopCleanly = 0
}

func (x *FilesystemDiskSpaceInfo) ClearBytesWhenAlertIssued() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_BytesWhenAlertIssued = 0
}

func (x *FilesystemDiskSpaceInfo) ClearRecommendAlert() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_RecommendAlert = false
}

func (x *FilesystemDiskSpaceInfo) ClearRecommendStop() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_RecommendStop = false
}

func (x *FilesystemDiskSpaceInfo) ClearBytesPerSecond() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_BytesPerSecond = 0
}

type FilesystemDiskSpaceInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the file-system
	FilesystemId *string
	// How much space is left on the file-system
	BytesAvailable *uint64
	// The total capacity of the file-system when empty.
	BytesCapacity *uint64
	// A list of what MinKNOW stores on this file-system, eg: reads, logs,
	// intermediate-files
	What []string
	// MinKNOW needs this much space to stop an experiment. If bytes_available
	// goes below this number, data could be lost!
	BytesToStopCleanly *uint64
	// The amount of space left on the file-system when recommend_alert
	// was set true.
	BytesWhenAlertIssued *uint64
	// MinKNOW recommends that you alert someone about the disk-usage
	RecommendAlert *bool
	// MinKNOW recommends that you stop the experiment due to disk-usage
	// concerns
	RecommendStop *bool
	// Rate of change in bytes_available (per second) +'ve numbers indicate
	// that bytes_available is decreasing and space is being used
	// A value of 0 can indicate that this has not applicable or not available.
	BytesPerSecond *int64
}

func (b0 FilesystemDiskSpaceInfo_builder) Build() *FilesystemDiskSpaceInfo {
	m0 := &FilesystemDiskSpaceInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FilesystemId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_FilesystemId = b.FilesystemId
	}
	if b.BytesAvailable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_BytesAvailable = *b.BytesAvailable
	}
	if b.BytesCapacity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_BytesCapacity = *b.BytesCapacity
	}
	x.xxx_hidden_What = b.What
	if b.BytesToStopCleanly != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_BytesToStopCleanly = *b.BytesToStopCleanly
	}
	if b.BytesWhenAlertIssued != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_BytesWhenAlertIssued = *b.BytesWhenAlertIssued
	}
	if b.RecommendAlert != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_RecommendAlert = *b.RecommendAlert
	}
	if b.RecommendStop != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_RecommendStop = *b.RecommendStop
	}
	if b.BytesPerSecond != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_BytesPerSecond = *b.BytesPerSecond
	}
	return m0
}

type GetDiskSpaceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceInfoRequest) Reset() {
	*x = GetDiskSpaceInfoRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceInfoRequest) ProtoMessage() {}

func (x *GetDiskSpaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetDiskSpaceInfoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetDiskSpaceInfoRequest_builder) Build() *GetDiskSpaceInfoRequest {
	m0 := &GetDiskSpaceInfoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type StreamDiskSpaceInfoRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Period      uint32                 `protobuf:"varint,1,opt,name=period"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamDiskSpaceInfoRequest) Reset() {
	*x = StreamDiskSpaceInfoRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDiskSpaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDiskSpaceInfoRequest) ProtoMessage() {}

func (x *StreamDiskSpaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamDiskSpaceInfoRequest) GetPeriod() uint32 {
	if x != nil {
		return x.xxx_hidden_Period
	}
	return 0
}

func (x *StreamDiskSpaceInfoRequest) SetPeriod(v uint32) {
	x.xxx_hidden_Period = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StreamDiskSpaceInfoRequest) HasPeriod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamDiskSpaceInfoRequest) ClearPeriod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Period = 0
}

type StreamDiskSpaceInfoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Disk space information will be streamed with this value determining the
	// period in seconds between updates.
	// A period of 0 is invalid
	Period *uint32
}

func (b0 StreamDiskSpaceInfoRequest_builder) Build() *StreamDiskSpaceInfoRequest {
	m0 := &StreamDiskSpaceInfoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Period != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Period = *b.Period
	}
	return m0
}

type GetDiskSpaceInfoResponse struct {
	state                              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_FilesystemDiskSpaceInfo *[]*FilesystemDiskSpaceInfo `protobuf:"bytes,1,rep,name=filesystem_disk_space_info,json=filesystemDiskSpaceInfo"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *GetDiskSpaceInfoResponse) Reset() {
	*x = GetDiskSpaceInfoResponse{}
	mi := &file_minknow_api_instance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceInfoResponse) ProtoMessage() {}

func (x *GetDiskSpaceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDiskSpaceInfoResponse) GetFilesystemDiskSpaceInfo() []*FilesystemDiskSpaceInfo {
	if x != nil {
		if x.xxx_hidden_FilesystemDiskSpaceInfo != nil {
			return *x.xxx_hidden_FilesystemDiskSpaceInfo
		}
	}
	return nil
}

func (x *GetDiskSpaceInfoResponse) SetFilesystemDiskSpaceInfo(v []*FilesystemDiskSpaceInfo) {
	x.xxx_hidden_FilesystemDiskSpaceInfo = &v
}

type GetDiskSpaceInfoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FilesystemDiskSpaceInfo []*FilesystemDiskSpaceInfo
}

func (b0 GetDiskSpaceInfoResponse_builder) Build() *GetDiskSpaceInfoResponse {
	m0 := &GetDiskSpaceInfoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FilesystemDiskSpaceInfo = &b.FilesystemDiskSpaceInfo
	return m0
}

type GetMachineIdRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineIdRequest) Reset() {
	*x = GetMachineIdRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineIdRequest) ProtoMessage() {}

func (x *GetMachineIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetMachineIdRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetMachineIdRequest_builder) Build() *GetMachineIdRequest {
	m0 := &GetMachineIdRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetMachineIdResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MachineId   *string                `protobuf:"bytes,1,opt,name=machine_id,json=machineId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetMachineIdResponse) Reset() {
	*x = GetMachineIdResponse{}
	mi := &file_minknow_api_instance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineIdResponse) ProtoMessage() {}

func (x *GetMachineIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMachineIdResponse) GetMachineId() string {
	if x != nil {
		if x.xxx_hidden_MachineId != nil {
			return *x.xxx_hidden_MachineId
		}
		return ""
	}
	return ""
}

func (x *GetMachineIdResponse) SetMachineId(v string) {
	x.xxx_hidden_MachineId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetMachineIdResponse) HasMachineId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetMachineIdResponse) ClearMachineId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MachineId = nil
}

type GetMachineIdResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The machine_id MinKNOW uses for this host.
	MachineId *string
}

func (b0 GetMachineIdResponse_builder) Build() *GetMachineIdResponse {
	m0 := &GetMachineIdResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MachineId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_MachineId = b.MachineId
	}
	return m0
}

type StreamInstanceActivityRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInstanceActivityRequest) Reset() {
	*x = StreamInstanceActivityRequest{}
	mi := &file_minknow_api_instance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInstanceActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInstanceActivityRequest) ProtoMessage() {}

func (x *StreamInstanceActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StreamInstanceActivityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StreamInstanceActivityRequest_builder) Build() *StreamInstanceActivityRequest {
	m0 := &StreamInstanceActivityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeviceInfo struct {
	state                  protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_DeviceState device.GetDeviceStateResponse_DeviceState `protobuf:"varint,1,opt,name=device_state,json=deviceState,enum=minknow_api.device.GetDeviceStateResponse_DeviceState"`
	xxx_hidden_DeviceInfo  *device.GetDeviceInfoResponse             `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_minknow_api_instance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeviceInfo) GetDeviceState() device.GetDeviceStateResponse_DeviceState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_DeviceState
		}
	}
	return device.GetDeviceStateResponse_DeviceState(0)
}

func (x *DeviceInfo) GetDeviceInfo() *device.GetDeviceInfoResponse {
	if x != nil {
		return x.xxx_hidden_DeviceInfo
	}
	return nil
}

func (x *DeviceInfo) SetDeviceState(v device.GetDeviceStateResponse_DeviceState) {
	x.xxx_hidden_DeviceState = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeviceInfo) SetDeviceInfo(v *device.GetDeviceInfoResponse) {
	x.xxx_hidden_DeviceInfo = v
}

func (x *DeviceInfo) HasDeviceState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeviceInfo) HasDeviceInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeviceInfo != nil
}

func (x *DeviceInfo) ClearDeviceState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DeviceState = device.GetDeviceStateResponse_DEVICE_DISCONNECTED
}

func (x *DeviceInfo) ClearDeviceInfo() {
	x.xxx_hidden_DeviceInfo = nil
}

type DeviceInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The current state of the device
	DeviceState *device.GetDeviceStateResponse_DeviceState
	// Information about the connected device (or no content if disconnected see: device_state)
	DeviceInfo *device.GetDeviceInfoResponse
}

func (b0 DeviceInfo_builder) Build() *DeviceInfo {
	m0 := &DeviceInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeviceState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_DeviceState = *b.DeviceState
	}
	x.xxx_hidden_DeviceInfo = b.DeviceInfo
	return m0
}

type BasecallSpeed struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MeanBasecallSpeed float32                `protobuf:"fixed32,1,opt,name=mean_basecall_speed,json=meanBasecallSpeed"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *BasecallSpeed) Reset() {
	*x = BasecallSpeed{}
	mi := &file_minknow_api_instance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasecallSpeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasecallSpeed) ProtoMessage() {}

func (x *BasecallSpeed) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BasecallSpeed) GetMeanBasecallSpeed() float32 {
	if x != nil {
		return x.xxx_hidden_MeanBasecallSpeed
	}
	return 0
}

func (x *BasecallSpeed) SetMeanBasecallSpeed(v float32) {
	x.xxx_hidden_MeanBasecallSpeed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *BasecallSpeed) HasMeanBasecallSpeed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BasecallSpeed) ClearMeanBasecallSpeed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MeanBasecallSpeed = 0
}

type BasecallSpeed_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Mean basecall speed, in bases per second.
	//
	// This value is only streamed for acquisitions where basecalling is enabled.
	//
	// The value reported here is the value stored in last completed basecall boxplot bucket
	// Each boxplot bucket covers a duration of `boxplot_time_coverage_in_minutes`
	MeanBasecallSpeed *float32
}

func (b0 BasecallSpeed_builder) Build() *BasecallSpeed {
	m0 := &BasecallSpeed{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MeanBasecallSpeed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_MeanBasecallSpeed = *b.MeanBasecallSpeed
	}
	return m0
}

type N50 struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_N50          float32                `protobuf:"fixed32,1,opt,name=n50"`
	xxx_hidden_EstimatedN50 float32                `protobuf:"fixed32,2,opt,name=estimated_n50,json=estimatedN50"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *N50) Reset() {
	*x = N50{}
	mi := &file_minknow_api_instance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N50) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N50) ProtoMessage() {}

func (x *N50) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *N50) GetN50() float32 {
	if x != nil {
		return x.xxx_hidden_N50
	}
	return 0
}

func (x *N50) GetEstimatedN50() float32 {
	if x != nil {
		return x.xxx_hidden_EstimatedN50
	}
	return 0
}

func (x *N50) SetN50(v float32) {
	x.xxx_hidden_N50 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *N50) SetEstimatedN50(v float32) {
	x.xxx_hidden_EstimatedN50 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *N50) HasN50() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *N50) HasEstimatedN50() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *N50) ClearN50() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_N50 = 0
}

func (x *N50) ClearEstimatedN50() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EstimatedN50 = 0
}

type N50_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// N50 data, in basecalled bases
	//
	// This value is only streamed for acquisitions where basecalling is enabled.
	//
	// The latest value is sent once per minute
	N50 *float32
	// N50 data, in estimated bases
	//
	// The latest value is sent once per minute
	EstimatedN50 *float32
}

func (b0 N50_builder) Build() *N50 {
	m0 := &N50{}
	b, x := &b0, m0
	_, _ = b, x
	if b.N50 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_N50 = *b.N50
	}
	if b.EstimatedN50 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_EstimatedN50 = *b.EstimatedN50
	}
	return m0
}

type StreamInstanceActivityResponse struct {
	state                  protoimpl.MessageState                       `protogen:"opaque.v1"`
	xxx_hidden_StreamValue isStreamInstanceActivityResponse_StreamValue `protobuf_oneof:"stream_value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamInstanceActivityResponse) Reset() {
	*x = StreamInstanceActivityResponse{}
	mi := &file_minknow_api_instance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInstanceActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInstanceActivityResponse) ProtoMessage() {}

func (x *StreamInstanceActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamInstanceActivityResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_DeviceInfo); ok {
			return x.DeviceInfo
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetFlowCellInfo() *device.GetFlowCellInfoResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_FlowCellInfo); ok {
			return x.FlowCellInfo
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetProtocolRunInfo() *protocol.ProtocolRunInfo {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_ProtocolRunInfo); ok {
			return x.ProtocolRunInfo
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetAcquisitionRunInfo() *acquisition.AcquisitionRunInfo {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_AcquisitionRunInfo); ok {
			return x.AcquisitionRunInfo
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetFlowCellHealth() *StreamInstanceActivityResponse_FlowCellHealth {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_FlowCellHealth_); ok {
			return x.FlowCellHealth
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetYieldSummary() *acquisition.AcquisitionYieldSummary {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_YieldSummary); ok {
			return x.YieldSummary
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetBasecallSpeed() *BasecallSpeed {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_BasecallSpeed); ok {
			return x.BasecallSpeed
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) GetN50() *N50 {
	if x != nil {
		if x, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_N50); ok {
			return x.N50
		}
	}
	return nil
}

func (x *StreamInstanceActivityResponse) SetDeviceInfo(v *DeviceInfo) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_DeviceInfo{v}
}

func (x *StreamInstanceActivityResponse) SetFlowCellInfo(v *device.GetFlowCellInfoResponse) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_FlowCellInfo{v}
}

func (x *StreamInstanceActivityResponse) SetProtocolRunInfo(v *protocol.ProtocolRunInfo) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_ProtocolRunInfo{v}
}

func (x *StreamInstanceActivityResponse) SetAcquisitionRunInfo(v *acquisition.AcquisitionRunInfo) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_AcquisitionRunInfo{v}
}

func (x *StreamInstanceActivityResponse) SetFlowCellHealth(v *StreamInstanceActivityResponse_FlowCellHealth) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_FlowCellHealth_{v}
}

func (x *StreamInstanceActivityResponse) SetYieldSummary(v *acquisition.AcquisitionYieldSummary) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_YieldSummary{v}
}

func (x *StreamInstanceActivityResponse) SetBasecallSpeed(v *BasecallSpeed) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_BasecallSpeed{v}
}

func (x *StreamInstanceActivityResponse) SetN50(v *N50) {
	if v == nil {
		x.xxx_hidden_StreamValue = nil
		return
	}
	x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_N50{v}
}

func (x *StreamInstanceActivityResponse) HasStreamValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StreamValue != nil
}

func (x *StreamInstanceActivityResponse) HasDeviceInfo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_DeviceInfo)
	return ok
}

func (x *StreamInstanceActivityResponse) HasFlowCellInfo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_FlowCellInfo)
	return ok
}

func (x *StreamInstanceActivityResponse) HasProtocolRunInfo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_ProtocolRunInfo)
	return ok
}

func (x *StreamInstanceActivityResponse) HasAcquisitionRunInfo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_AcquisitionRunInfo)
	return ok
}

func (x *StreamInstanceActivityResponse) HasFlowCellHealth() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_FlowCellHealth_)
	return ok
}

func (x *StreamInstanceActivityResponse) HasYieldSummary() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_YieldSummary)
	return ok
}

func (x *StreamInstanceActivityResponse) HasBasecallSpeed() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_BasecallSpeed)
	return ok
}

func (x *StreamInstanceActivityResponse) HasN50() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_N50)
	return ok
}

func (x *StreamInstanceActivityResponse) ClearStreamValue() {
	x.xxx_hidden_StreamValue = nil
}

func (x *StreamInstanceActivityResponse) ClearDeviceInfo() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_DeviceInfo); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearFlowCellInfo() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_FlowCellInfo); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearProtocolRunInfo() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_ProtocolRunInfo); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearAcquisitionRunInfo() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_AcquisitionRunInfo); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearFlowCellHealth() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_FlowCellHealth_); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearYieldSummary() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_YieldSummary); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearBasecallSpeed() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_BasecallSpeed); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

func (x *StreamInstanceActivityResponse) ClearN50() {
	if _, ok := x.xxx_hidden_StreamValue.(*streamInstanceActivityResponse_N50); ok {
		x.xxx_hidden_StreamValue = nil
	}
}

const StreamInstanceActivityResponse_StreamValue_not_set_case case_StreamInstanceActivityResponse_StreamValue = 0
const StreamInstanceActivityResponse_DeviceInfo_case case_StreamInstanceActivityResponse_StreamValue = 1
const StreamInstanceActivityResponse_FlowCellInfo_case case_StreamInstanceActivityResponse_StreamValue = 2
const StreamInstanceActivityResponse_ProtocolRunInfo_case case_StreamInstanceActivityResponse_StreamValue = 3
const StreamInstanceActivityResponse_AcquisitionRunInfo_case case_StreamInstanceActivityResponse_StreamValue = 4
const StreamInstanceActivityResponse_FlowCellHealth_case case_StreamInstanceActivityResponse_StreamValue = 5
const StreamInstanceActivityResponse_YieldSummary_case case_StreamInstanceActivityResponse_StreamValue = 6
const StreamInstanceActivityResponse_BasecallSpeed_case case_StreamInstanceActivityResponse_StreamValue = 7
const StreamInstanceActivityResponse_N50_case case_StreamInstanceActivityResponse_StreamValue = 8

func (x *StreamInstanceActivityResponse) WhichStreamValue() case_StreamInstanceActivityResponse_StreamValue {
	if x == nil {
		return StreamInstanceActivityResponse_StreamValue_not_set_case
	}
	switch x.xxx_hidden_StreamValue.(type) {
	case *streamInstanceActivityResponse_DeviceInfo:
		return StreamInstanceActivityResponse_DeviceInfo_case
	case *streamInstanceActivityResponse_FlowCellInfo:
		return StreamInstanceActivityResponse_FlowCellInfo_case
	case *streamInstanceActivityResponse_ProtocolRunInfo:
		return StreamInstanceActivityResponse_ProtocolRunInfo_case
	case *streamInstanceActivityResponse_AcquisitionRunInfo:
		return StreamInstanceActivityResponse_AcquisitionRunInfo_case
	case *streamInstanceActivityResponse_FlowCellHealth_:
		return StreamInstanceActivityResponse_FlowCellHealth_case
	case *streamInstanceActivityResponse_YieldSummary:
		return StreamInstanceActivityResponse_YieldSummary_case
	case *streamInstanceActivityResponse_BasecallSpeed:
		return StreamInstanceActivityResponse_BasecallSpeed_case
	case *streamInstanceActivityResponse_N50:
		return StreamInstanceActivityResponse_N50_case
	default:
		return StreamInstanceActivityResponse_StreamValue_not_set_case
	}
}

type StreamInstanceActivityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_StreamValue:
	// Information about whether the device is connected or not, and if it is, gives
	// information about the connected device
	DeviceInfo *DeviceInfo
	// Information about the currently connected flow cell
	//
	// Note: if no flow cell is connected this [flow_cell_info.has_flow_cell] will be false
	FlowCellInfo *device.GetFlowCellInfoResponse
	// Information about the in progress protocol.
	//
	// Note if no protocol is active this message will not be present.
	ProtocolRunInfo *protocol.ProtocolRunInfo
	// Information about the current acquisition run
	//
	// Note if no acquisition is active the message will not be present.
	AcquisitionRunInfo *acquisition.AcquisitionRunInfo
	// Information about the health of the flow cell within the current run
	//
	// Note: only available if a run is in progress
	FlowCellHealth *StreamInstanceActivityResponse_FlowCellHealth
	// Acquisition yield information. Describes information such as number of reads,
	// what number of those reads have passed or failed basecalling etc. Rate
	// limited to 1 second per update
	YieldSummary *acquisition.AcquisitionYieldSummary
	// Basecall speed information
	// Note: only available if an acquisition with basecalling enabled is in progress
	BasecallSpeed *BasecallSpeed
	// n50 information
	//
	// # Contains the n50 value, measured in basecalled bases and estimated bases
	//
	// Note: basecalled bases only available if an acquisition with basecalling enabled is in progress
	N50 *N50
	// -- end of xxx_hidden_StreamValue
}

func (b0 StreamInstanceActivityResponse_builder) Build() *StreamInstanceActivityResponse {
	m0 := &StreamInstanceActivityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeviceInfo != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_DeviceInfo{b.DeviceInfo}
	}
	if b.FlowCellInfo != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_FlowCellInfo{b.FlowCellInfo}
	}
	if b.ProtocolRunInfo != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_ProtocolRunInfo{b.ProtocolRunInfo}
	}
	if b.AcquisitionRunInfo != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_AcquisitionRunInfo{b.AcquisitionRunInfo}
	}
	if b.FlowCellHealth != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_FlowCellHealth_{b.FlowCellHealth}
	}
	if b.YieldSummary != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_YieldSummary{b.YieldSummary}
	}
	if b.BasecallSpeed != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_BasecallSpeed{b.BasecallSpeed}
	}
	if b.N50 != nil {
		x.xxx_hidden_StreamValue = &streamInstanceActivityResponse_N50{b.N50}
	}
	return m0
}

type case_StreamInstanceActivityResponse_StreamValue protoreflect.FieldNumber

func (x case_StreamInstanceActivityResponse_StreamValue) String() string {
	md := file_minknow_api_instance_proto_msgTypes[19].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStreamInstanceActivityResponse_StreamValue interface {
	isStreamInstanceActivityResponse_StreamValue()
}

type streamInstanceActivityResponse_DeviceInfo struct {
	// Information about whether the device is connected or not, and if it is, gives
	// information about the connected device
	DeviceInfo *DeviceInfo `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,oneof"`
}

type streamInstanceActivityResponse_FlowCellInfo struct {
	// Information about the currently connected flow cell
	//
	// Note: if no flow cell is connected this [flow_cell_info.has_flow_cell] will be false
	FlowCellInfo *device.GetFlowCellInfoResponse `protobuf:"bytes,2,opt,name=flow_cell_info,json=flowCellInfo,oneof"`
}

type streamInstanceActivityResponse_ProtocolRunInfo struct {
	// Information about the in progress protocol.
	//
	// Note if no protocol is active this message will not be present.
	ProtocolRunInfo *protocol.ProtocolRunInfo `protobuf:"bytes,3,opt,name=protocol_run_info,json=protocolRunInfo,oneof"`
}

type streamInstanceActivityResponse_AcquisitionRunInfo struct {
	// Information about the current acquisition run
	//
	// Note if no acquisition is active the message will not be present.
	AcquisitionRunInfo *acquisition.AcquisitionRunInfo `protobuf:"bytes,4,opt,name=acquisition_run_info,json=acquisitionRunInfo,oneof"`
}

type streamInstanceActivityResponse_FlowCellHealth_ struct {
	// Information about the health of the flow cell within the current run
	//
	// Note: only available if a run is in progress
	FlowCellHealth *StreamInstanceActivityResponse_FlowCellHealth `protobuf:"bytes,5,opt,name=flow_cell_health,json=flowCellHealth,oneof"`
}

type streamInstanceActivityResponse_YieldSummary struct {
	// Acquisition yield information. Describes information such as number of reads,
	// what number of those reads have passed or failed basecalling etc. Rate
	// limited to 1 second per update
	YieldSummary *acquisition.AcquisitionYieldSummary `protobuf:"bytes,6,opt,name=yield_summary,json=yieldSummary,oneof"`
}

type streamInstanceActivityResponse_BasecallSpeed struct {
	// Basecall speed information
	// Note: only available if an acquisition with basecalling enabled is in progress
	BasecallSpeed *BasecallSpeed `protobuf:"bytes,7,opt,name=basecall_speed,json=basecallSpeed,oneof"`
}

type streamInstanceActivityResponse_N50 struct {
	// n50 information
	//
	// # Contains the n50 value, measured in basecalled bases and estimated bases
	//
	// Note: basecalled bases only available if an acquisition with basecalling enabled is in progress
	N50 *N50 `protobuf:"bytes,8,opt,name=n50,oneof"`
}

func (*streamInstanceActivityResponse_DeviceInfo) isStreamInstanceActivityResponse_StreamValue() {}

func (*streamInstanceActivityResponse_FlowCellInfo) isStreamInstanceActivityResponse_StreamValue() {}

func (*streamInstanceActivityResponse_ProtocolRunInfo) isStreamInstanceActivityResponse_StreamValue() {
}

func (*streamInstanceActivityResponse_AcquisitionRunInfo) isStreamInstanceActivityResponse_StreamValue() {
}

func (*streamInstanceActivityResponse_FlowCellHealth_) isStreamInstanceActivityResponse_StreamValue() {
}

func (*streamInstanceActivityResponse_YieldSummary) isStreamInstanceActivityResponse_StreamValue() {}

func (*streamInstanceActivityResponse_BasecallSpeed) isStreamInstanceActivityResponse_StreamValue() {}

func (*streamInstanceActivityResponse_N50) isStreamInstanceActivityResponse_StreamValue() {}

type GetVersionInfoResponse_MinknowVersion struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Major       int32                  `protobuf:"varint,1,opt,name=major"`
	xxx_hidden_Minor       int32                  `protobuf:"varint,2,opt,name=minor"`
	xxx_hidden_Patch       int32                  `protobuf:"varint,3,opt,name=patch"`
	xxx_hidden_Full        *string                `protobuf:"bytes,4,opt,name=full"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetVersionInfoResponse_MinknowVersion) Reset() {
	*x = GetVersionInfoResponse_MinknowVersion{}
	mi := &file_minknow_api_instance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionInfoResponse_MinknowVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionInfoResponse_MinknowVersion) ProtoMessage() {}

func (x *GetVersionInfoResponse_MinknowVersion) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetVersionInfoResponse_MinknowVersion) GetMajor() int32 {
	if x != nil {
		return x.xxx_hidden_Major
	}
	return 0
}

func (x *GetVersionInfoResponse_MinknowVersion) GetMinor() int32 {
	if x != nil {
		return x.xxx_hidden_Minor
	}
	return 0
}

func (x *GetVersionInfoResponse_MinknowVersion) GetPatch() int32 {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return 0
}

func (x *GetVersionInfoResponse_MinknowVersion) GetFull() string {
	if x != nil {
		if x.xxx_hidden_Full != nil {
			return *x.xxx_hidden_Full
		}
		return ""
	}
	return ""
}

func (x *GetVersionInfoResponse_MinknowVersion) SetMajor(v int32) {
	x.xxx_hidden_Major = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *GetVersionInfoResponse_MinknowVersion) SetMinor(v int32) {
	x.xxx_hidden_Minor = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *GetVersionInfoResponse_MinknowVersion) SetPatch(v int32) {
	x.xxx_hidden_Patch = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *GetVersionInfoResponse_MinknowVersion) SetFull(v string) {
	x.xxx_hidden_Full = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *GetVersionInfoResponse_MinknowVersion) HasMajor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetVersionInfoResponse_MinknowVersion) HasMinor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetVersionInfoResponse_MinknowVersion) HasPatch() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetVersionInfoResponse_MinknowVersion) HasFull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetVersionInfoResponse_MinknowVersion) ClearMajor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Major = 0
}

func (x *GetVersionInfoResponse_MinknowVersion) ClearMinor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Minor = 0
}

func (x *GetVersionInfoResponse_MinknowVersion) ClearPatch() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Patch = 0
}

func (x *GetVersionInfoResponse_MinknowVersion) ClearFull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Full = nil
}

type GetVersionInfoResponse_MinknowVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Major *int32
	Minor *int32
	Patch *int32
	Full  *string
}

func (b0 GetVersionInfoResponse_MinknowVersion_builder) Build() *GetVersionInfoResponse_MinknowVersion {
	m0 := &GetVersionInfoResponse_MinknowVersion{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Major != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Major = *b.Major
	}
	if b.Minor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Minor = *b.Minor
	}
	if b.Patch != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Patch = *b.Patch
	}
	if b.Full != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Full = b.Full
	}
	return m0
}

type StreamInstanceActivityResponse_FlowCellHealth struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChannelStatePercentages map[string]float32     `protobuf:"bytes,1,rep,name=channel_state_percentages,json=channelStatePercentages" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *StreamInstanceActivityResponse_FlowCellHealth) Reset() {
	*x = StreamInstanceActivityResponse_FlowCellHealth{}
	mi := &file_minknow_api_instance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInstanceActivityResponse_FlowCellHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInstanceActivityResponse_FlowCellHealth) ProtoMessage() {}

func (x *StreamInstanceActivityResponse_FlowCellHealth) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_instance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamInstanceActivityResponse_FlowCellHealth) GetChannelStatePercentages() map[string]float32 {
	if x != nil {
		return x.xxx_hidden_ChannelStatePercentages
	}
	return nil
}

func (x *StreamInstanceActivityResponse_FlowCellHealth) SetChannelStatePercentages(v map[string]float32) {
	x.xxx_hidden_ChannelStatePercentages = v
}

type StreamInstanceActivityResponse_FlowCellHealth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Map between channel state name and a percentage of how much time that state has been active with respect to all other channel states
	//
	// This is over one minute of time this is calculated over
	ChannelStatePercentages map[string]float32
}

func (b0 StreamInstanceActivityResponse_FlowCellHealth_builder) Build() *StreamInstanceActivityResponse_FlowCellHealth {
	m0 := &StreamInstanceActivityResponse_FlowCellHealth{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ChannelStatePercentages = b.ChannelStatePercentages
	return m0
}

var File_minknow_api_instance_proto protoreflect.FileDescriptor

const file_minknow_api_instance_proto_rawDesc = "" +
	"\n" +
	"\x1aminknow_api/instance.proto\x12\x14minknow_api.instance\x1a\x1dminknow_api/acquisition.proto\x1a\x18minknow_api/device.proto\x1a\x1aminknow_api/protocol.proto\"\x17\n" +
	"\x15GetVersionInfoRequest\"\xd7\x06\n" +
	"\x16GetVersionInfoResponse\x12U\n" +
	"\aminknow\x18\x01 \x01(\v2;.minknow_api.instance.GetVersionInfoResponse.MinknowVersionR\aminknow\x12\x14\n" +
	"\x05bream\x18\x02 \x01(\tR\x05bream\x121\n" +
	"\x14distribution_version\x18\x03 \x01(\tR\x13distributionVersion\x12p\n" +
	"\x13distribution_status\x18\x04 \x01(\x0e2?.minknow_api.instance.GetVersionInfoResponse.DistributionStatusR\x12distributionStatus\x125\n" +
	"\x16protocol_configuration\x18\x05 \x01(\tR\x15protocolConfiguration\x12j\n" +
	"\x11installation_type\x18\x06 \x01(\x0e2=.minknow_api.instance.GetVersionInfoResponse.InstallationTypeR\x10installationType\x128\n" +
	"\x18basecaller_build_version\x18\t \x01(\tR\x16basecallerBuildVersion\x12@\n" +
	"\x1cbasecaller_connected_version\x18\n" +
	" \x01(\tR\x1abasecallerConnectedVersion\x1af\n" +
	"\x0eMinknowVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\x05R\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\x05R\x05patch\x12\x12\n" +
	"\x04full\x18\x04 \x01(\tR\x04full\"I\n" +
	"\x12DistributionStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06STABLE\x10\x01\x12\f\n" +
	"\bUNSTABLE\x10\x02\x12\f\n" +
	"\bMODIFIED\x10\x03\"M\n" +
	"\x10InstallationType\x12\a\n" +
	"\x03ONT\x10\x00\x12\x06\n" +
	"\x02NC\x10\x01\x12\b\n" +
	"\x04PROD\x10\x02\x12\r\n" +
	"\tQ_RELEASE\x10\x03\x12\x0f\n" +
	"\vOND_RELEASE\x10\x04J\x04\b\a\x10\bJ\x04\b\b\x10\t\"\x1d\n" +
	"\x1bGetOutputDirectoriesRequest\"S\n" +
	"\x11OutputDirectories\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x10\n" +
	"\x03log\x18\x02 \x01(\tR\x03log\x12\x14\n" +
	"\x05reads\x18\x03 \x01(\tR\x05reads\"$\n" +
	"\"GetDefaultOutputDirectoriesRequest\"/\n" +
	"\x19SetOutputDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1c\n" +
	"\x1aSetOutputDirectoryResponse\".\n" +
	"\x18SetReadsDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1b\n" +
	"\x19SetReadsDirectoryResponse\"\x86\x03\n" +
	"\x17FilesystemDiskSpaceInfo\x12#\n" +
	"\rfilesystem_id\x18\x01 \x01(\tR\ffilesystemId\x12'\n" +
	"\x0fbytes_available\x18\x02 \x01(\x04R\x0ebytesAvailable\x12%\n" +
	"\x0ebytes_capacity\x18\x03 \x01(\x04R\rbytesCapacity\x12\x12\n" +
	"\x04what\x18\x04 \x03(\tR\x04what\x121\n" +
	"\x15bytes_to_stop_cleanly\x18\x05 \x01(\x04R\x12bytesToStopCleanly\x125\n" +
	"\x17bytes_when_alert_issued\x18\x06 \x01(\x04R\x14bytesWhenAlertIssued\x12'\n" +
	"\x0frecommend_alert\x18\a \x01(\bR\x0erecommendAlert\x12%\n" +
	"\x0erecommend_stop\x18\b \x01(\bR\rrecommendStop\x12(\n" +
	"\x10bytes_per_second\x18\t \x01(\x03R\x0ebytesPerSecond\"\x19\n" +
	"\x17GetDiskSpaceInfoRequest\"4\n" +
	"\x1aStreamDiskSpaceInfoRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\rR\x06period\"\x86\x01\n" +
	"\x18GetDiskSpaceInfoResponse\x12j\n" +
	"\x1afilesystem_disk_space_info\x18\x01 \x03(\v2-.minknow_api.instance.FilesystemDiskSpaceInfoR\x17filesystemDiskSpaceInfo\"\x15\n" +
	"\x13GetMachineIdRequest\"5\n" +
	"\x14GetMachineIdResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"\x1f\n" +
	"\x1dStreamInstanceActivityRequest\"\xb3\x01\n" +
	"\n" +
	"DeviceInfo\x12Y\n" +
	"\fdevice_state\x18\x01 \x01(\x0e26.minknow_api.device.GetDeviceStateResponse.DeviceStateR\vdeviceState\x12J\n" +
	"\vdevice_info\x18\x02 \x01(\v2).minknow_api.device.GetDeviceInfoResponseR\n" +
	"deviceInfo\"?\n" +
	"\rBasecallSpeed\x12.\n" +
	"\x13mean_basecall_speed\x18\x01 \x01(\x02R\x11meanBasecallSpeed\"<\n" +
	"\x03N50\x12\x10\n" +
	"\x03n50\x18\x01 \x01(\x02R\x03n50\x12#\n" +
	"\restimated_n50\x18\x02 \x01(\x02R\festimatedN50\"\xc5\a\n" +
	"\x1eStreamInstanceActivityResponse\x12C\n" +
	"\vdevice_info\x18\x01 \x01(\v2 .minknow_api.instance.DeviceInfoH\x00R\n" +
	"deviceInfo\x12S\n" +
	"\x0eflow_cell_info\x18\x02 \x01(\v2+.minknow_api.device.GetFlowCellInfoResponseH\x00R\fflowCellInfo\x12S\n" +
	"\x11protocol_run_info\x18\x03 \x01(\v2%.minknow_api.protocol.ProtocolRunInfoH\x00R\x0fprotocolRunInfo\x12_\n" +
	"\x14acquisition_run_info\x18\x04 \x01(\v2+.minknow_api.acquisition.AcquisitionRunInfoH\x00R\x12acquisitionRunInfo\x12o\n" +
	"\x10flow_cell_health\x18\x05 \x01(\v2C.minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealthH\x00R\x0eflowCellHealth\x12W\n" +
	"\ryield_summary\x18\x06 \x01(\v20.minknow_api.acquisition.AcquisitionYieldSummaryH\x00R\fyieldSummary\x12L\n" +
	"\x0ebasecall_speed\x18\a \x01(\v2#.minknow_api.instance.BasecallSpeedH\x00R\rbasecallSpeed\x12-\n" +
	"\x03n50\x18\b \x01(\v2\x19.minknow_api.instance.N50H\x00R\x03n50\x1a\xfb\x01\n" +
	"\x0eFlowCellHealth\x12\x9c\x01\n" +
	"\x19channel_state_percentages\x18\x01 \x03(\v2`.minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealth.ChannelStatePercentagesEntryR\x17channelStatePercentages\x1aJ\n" +
	"\x1cChannelStatePercentagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01B\x0e\n" +
	"\fstream_value2\x8a\t\n" +
	"\x0fInstanceService\x12r\n" +
	"\x10get_version_info\x12+.minknow_api.instance.GetVersionInfoRequest\x1a,.minknow_api.instance.GetVersionInfoResponse\"\x03\x90\x02\x01\x12y\n" +
	"\x16get_output_directories\x121.minknow_api.instance.GetOutputDirectoriesRequest\x1a'.minknow_api.instance.OutputDirectories\"\x03\x90\x02\x01\x12\x88\x01\n" +
	"\x1eget_default_output_directories\x128.minknow_api.instance.GetDefaultOutputDirectoriesRequest\x1a'.minknow_api.instance.OutputDirectories\"\x03\x90\x02\x01\x12~\n" +
	"\x14set_output_directory\x12/.minknow_api.instance.SetOutputDirectoryRequest\x1a0.minknow_api.instance.SetOutputDirectoryResponse\"\x03\x90\x02\x02\x12{\n" +
	"\x13set_reads_directory\x12..minknow_api.instance.SetReadsDirectoryRequest\x1a/.minknow_api.instance.SetReadsDirectoryResponse\"\x03\x90\x02\x02\x12|\n" +
	"\x13get_disk_space_info\x12-.minknow_api.instance.GetDiskSpaceInfoRequest\x1a..minknow_api.instance.GetDiskSpaceInfoResponse\"\x06\x88\x02\x01\x90\x02\x01\x12\x84\x01\n" +
	"\x16stream_disk_space_info\x120.minknow_api.instance.StreamDiskSpaceInfoRequest\x1a..minknow_api.instance.GetDiskSpaceInfoResponse\"\x06\x88\x02\x01\x90\x02\x010\x01\x12l\n" +
	"\x0eget_machine_id\x12).minknow_api.instance.GetMachineIdRequest\x1a*.minknow_api.instance.GetMachineIdResponse\"\x03\x90\x02\x01\x12\x8c\x01\n" +
	"\x18stream_instance_activity\x123.minknow_api.instance.StreamInstanceActivityRequest\x1a4.minknow_api.instance.StreamInstanceActivityResponse\"\x03\x90\x02\x010\x01B^\n" +
	"\x1ccom.nanoporetech.minknow_apiZ3github.com/nanoporetech/minknow_api/go/gen/instance\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_minknow_api_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_minknow_api_instance_proto_goTypes = []any{
	(GetVersionInfoResponse_DistributionStatus)(0),        // 0: minknow_api.instance.GetVersionInfoResponse.DistributionStatus
	(GetVersionInfoResponse_InstallationType)(0),          // 1: minknow_api.instance.GetVersionInfoResponse.InstallationType
	(*GetVersionInfoRequest)(nil),                         // 2: minknow_api.instance.GetVersionInfoRequest
	(*GetVersionInfoResponse)(nil),                        // 3: minknow_api.instance.GetVersionInfoResponse
	(*GetOutputDirectoriesRequest)(nil),                   // 4: minknow_api.instance.GetOutputDirectoriesRequest
	(*OutputDirectories)(nil),                             // 5: minknow_api.instance.OutputDirectories
	(*GetDefaultOutputDirectoriesRequest)(nil),            // 6: minknow_api.instance.GetDefaultOutputDirectoriesRequest
	(*SetOutputDirectoryRequest)(nil),                     // 7: minknow_api.instance.SetOutputDirectoryRequest
	(*SetOutputDirectoryResponse)(nil),                    // 8: minknow_api.instance.SetOutputDirectoryResponse
	(*SetReadsDirectoryRequest)(nil),                      // 9: minknow_api.instance.SetReadsDirectoryRequest
	(*SetReadsDirectoryResponse)(nil),                     // 10: minknow_api.instance.SetReadsDirectoryResponse
	(*FilesystemDiskSpaceInfo)(nil),                       // 11: minknow_api.instance.FilesystemDiskSpaceInfo
	(*GetDiskSpaceInfoRequest)(nil),                       // 12: minknow_api.instance.GetDiskSpaceInfoRequest
	(*StreamDiskSpaceInfoRequest)(nil),                    // 13: minknow_api.instance.StreamDiskSpaceInfoRequest
	(*GetDiskSpaceInfoResponse)(nil),                      // 14: minknow_api.instance.GetDiskSpaceInfoResponse
	(*GetMachineIdRequest)(nil),                           // 15: minknow_api.instance.GetMachineIdRequest
	(*GetMachineIdResponse)(nil),                          // 16: minknow_api.instance.GetMachineIdResponse
	(*StreamInstanceActivityRequest)(nil),                 // 17: minknow_api.instance.StreamInstanceActivityRequest
	(*DeviceInfo)(nil),                                    // 18: minknow_api.instance.DeviceInfo
	(*BasecallSpeed)(nil),                                 // 19: minknow_api.instance.BasecallSpeed
	(*N50)(nil),                                           // 20: minknow_api.instance.N50
	(*StreamInstanceActivityResponse)(nil),                // 21: minknow_api.instance.StreamInstanceActivityResponse
	(*GetVersionInfoResponse_MinknowVersion)(nil),         // 22: minknow_api.instance.GetVersionInfoResponse.MinknowVersion
	(*StreamInstanceActivityResponse_FlowCellHealth)(nil), // 23: minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealth
	nil, // 24: minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealth.ChannelStatePercentagesEntry
	(device.GetDeviceStateResponse_DeviceState)(0), // 25: minknow_api.device.GetDeviceStateResponse.DeviceState
	(*device.GetDeviceInfoResponse)(nil),           // 26: minknow_api.device.GetDeviceInfoResponse
	(*device.GetFlowCellInfoResponse)(nil),         // 27: minknow_api.device.GetFlowCellInfoResponse
	(*protocol.ProtocolRunInfo)(nil),               // 28: minknow_api.protocol.ProtocolRunInfo
	(*acquisition.AcquisitionRunInfo)(nil),         // 29: minknow_api.acquisition.AcquisitionRunInfo
	(*acquisition.AcquisitionYieldSummary)(nil),    // 30: minknow_api.acquisition.AcquisitionYieldSummary
}
var file_minknow_api_instance_proto_depIdxs = []int32{
	22, // 0: minknow_api.instance.GetVersionInfoResponse.minknow:type_name -> minknow_api.instance.GetVersionInfoResponse.MinknowVersion
	0,  // 1: minknow_api.instance.GetVersionInfoResponse.distribution_status:type_name -> minknow_api.instance.GetVersionInfoResponse.DistributionStatus
	1,  // 2: minknow_api.instance.GetVersionInfoResponse.installation_type:type_name -> minknow_api.instance.GetVersionInfoResponse.InstallationType
	11, // 3: minknow_api.instance.GetDiskSpaceInfoResponse.filesystem_disk_space_info:type_name -> minknow_api.instance.FilesystemDiskSpaceInfo
	25, // 4: minknow_api.instance.DeviceInfo.device_state:type_name -> minknow_api.device.GetDeviceStateResponse.DeviceState
	26, // 5: minknow_api.instance.DeviceInfo.device_info:type_name -> minknow_api.device.GetDeviceInfoResponse
	18, // 6: minknow_api.instance.StreamInstanceActivityResponse.device_info:type_name -> minknow_api.instance.DeviceInfo
	27, // 7: minknow_api.instance.StreamInstanceActivityResponse.flow_cell_info:type_name -> minknow_api.device.GetFlowCellInfoResponse
	28, // 8: minknow_api.instance.StreamInstanceActivityResponse.protocol_run_info:type_name -> minknow_api.protocol.ProtocolRunInfo
	29, // 9: minknow_api.instance.StreamInstanceActivityResponse.acquisition_run_info:type_name -> minknow_api.acquisition.AcquisitionRunInfo
	23, // 10: minknow_api.instance.StreamInstanceActivityResponse.flow_cell_health:type_name -> minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealth
	30, // 11: minknow_api.instance.StreamInstanceActivityResponse.yield_summary:type_name -> minknow_api.acquisition.AcquisitionYieldSummary
	19, // 12: minknow_api.instance.StreamInstanceActivityResponse.basecall_speed:type_name -> minknow_api.instance.BasecallSpeed
	20, // 13: minknow_api.instance.StreamInstanceActivityResponse.n50:type_name -> minknow_api.instance.N50
	24, // 14: minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealth.channel_state_percentages:type_name -> minknow_api.instance.StreamInstanceActivityResponse.FlowCellHealth.ChannelStatePercentagesEntry
	2,  // 15: minknow_api.instance.InstanceService.get_version_info:input_type -> minknow_api.instance.GetVersionInfoRequest
	4,  // 16: minknow_api.instance.InstanceService.get_output_directories:input_type -> minknow_api.instance.GetOutputDirectoriesRequest
	6,  // 17: minknow_api.instance.InstanceService.get_default_output_directories:input_type -> minknow_api.instance.GetDefaultOutputDirectoriesRequest
	7,  // 18: minknow_api.instance.InstanceService.set_output_directory:input_type -> minknow_api.instance.SetOutputDirectoryRequest
	9,  // 19: minknow_api.instance.InstanceService.set_reads_directory:input_type -> minknow_api.instance.SetReadsDirectoryRequest
	12, // 20: minknow_api.instance.InstanceService.get_disk_space_info:input_type -> minknow_api.instance.GetDiskSpaceInfoRequest
	13, // 21: minknow_api.instance.InstanceService.stream_disk_space_info:input_type -> minknow_api.instance.StreamDiskSpaceInfoRequest
	15, // 22: minknow_api.instance.InstanceService.get_machine_id:input_type -> minknow_api.instance.GetMachineIdRequest
	17, // 23: minknow_api.instance.InstanceService.stream_instance_activity:input_type -> minknow_api.instance.StreamInstanceActivityRequest
	3,  // 24: minknow_api.instance.InstanceService.get_version_info:output_type -> minknow_api.instance.GetVersionInfoResponse
	5,  // 25: minknow_api.instance.InstanceService.get_output_directories:output_type -> minknow_api.instance.OutputDirectories
	5,  // 26: minknow_api.instance.InstanceService.get_default_output_directories:output_type -> minknow_api.instance.OutputDirectories
	8,  // 27: minknow_api.instance.InstanceService.set_output_directory:output_type -> minknow_api.instance.SetOutputDirectoryResponse
	10, // 28: minknow_api.instance.InstanceService.set_reads_directory:output_type -> minknow_api.instance.SetReadsDirectoryResponse
	14, // 29: minknow_api.instance.InstanceService.get_disk_space_info:output_type -> minknow_api.instance.GetDiskSpaceInfoResponse
	14, // 30: minknow_api.instance.InstanceService.stream_disk_space_info:output_type -> minknow_api.instance.GetDiskSpaceInfoResponse
	16, // 31: minknow_api.instance.InstanceService.get_machine_id:output_type -> minknow_api.instance.GetMachineIdResponse
	21, // 32: minknow_api.instance.InstanceService.stream_instance_activity:output_type -> minknow_api.instance.StreamInstanceActivityResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_minknow_api_instance_proto_init() }
func file_minknow_api_instance_proto_init() {
	if File_minknow_api_instance_proto != nil {
		return
	}
	file_minknow_api_instance_proto_msgTypes[19].OneofWrappers = []any{
		(*streamInstanceActivityResponse_DeviceInfo)(nil),
		(*streamInstanceActivityResponse_FlowCellInfo)(nil),
		(*streamInstanceActivityResponse_ProtocolRunInfo)(nil),
		(*streamInstanceActivityResponse_AcquisitionRunInfo)(nil),
		(*streamInstanceActivityResponse_FlowCellHealth_)(nil),
		(*streamInstanceActivityResponse_YieldSummary)(nil),
		(*streamInstanceActivityResponse_BasecallSpeed)(nil),
		(*streamInstanceActivityResponse_N50)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_instance_proto_rawDesc), len(file_minknow_api_instance_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_instance_proto_goTypes,
		DependencyIndexes: file_minknow_api_instance_proto_depIdxs,
		EnumInfos:         file_minknow_api_instance_proto_enumTypes,
		MessageInfos:      file_minknow_api_instance_proto_msgTypes,
	}.Build()
	File_minknow_api_instance_proto = out.File
	file_minknow_api_instance_proto_goTypes = nil
	file_minknow_api_instance_proto_depIdxs = nil
}
