// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/keystore.proto

package keystore

import (
	_ "github.com/nanoporetech/minknow_api/go/gen/rpc_options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control for the lifetime of a stored value.
//
// When storing values in the manager, the only valid values are `UNTIL_INSTANCE_END` and
// `PERSIST_ACROSS_RESTARTS`.
type Lifetime int32

const (
	// Automatically remove the value next time a protocol starts.
	Lifetime_UNTIL_NEXT_PROTOCOL_START Lifetime = 0
	// Automatically remove the value next time a protocol ends.
	Lifetime_UNTIL_PROTOCOL_END Lifetime = 1
	// Keep the value until the MinKNOW instance terminates.
	//
	// Be careful when using this value, as there is a maximum amount of data that can be stored.
	Lifetime_UNTIL_INSTANCE_END Lifetime = 2
	// Persist the value between MinKNOW instance restarts
	//
	// Be very careful when using this value, as all of these values will be persisted to disk,
	// and loaded when MinKNOW restarts
	Lifetime_PERSIST_ACROSS_RESTARTS Lifetime = 3
)

// Enum value maps for Lifetime.
var (
	Lifetime_name = map[int32]string{
		0: "UNTIL_NEXT_PROTOCOL_START",
		1: "UNTIL_PROTOCOL_END",
		2: "UNTIL_INSTANCE_END",
		3: "PERSIST_ACROSS_RESTARTS",
	}
	Lifetime_value = map[string]int32{
		"UNTIL_NEXT_PROTOCOL_START": 0,
		"UNTIL_PROTOCOL_END":        1,
		"UNTIL_INSTANCE_END":        2,
		"PERSIST_ACROSS_RESTARTS":   3,
	}
)

func (x Lifetime) Enum() *Lifetime {
	p := new(Lifetime)
	*p = x
	return p
}

func (x Lifetime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifetime) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_keystore_proto_enumTypes[0].Descriptor()
}

func (Lifetime) Type() protoreflect.EnumType {
	return &file_minknow_api_keystore_proto_enumTypes[0]
}

func (x Lifetime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type StoreRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values      map[string]*anypb.Any  `protobuf:"bytes,1,rep,name=values" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Lifetime    Lifetime               `protobuf:"varint,2,opt,name=lifetime,enum=minknow_api.keystore.Lifetime"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_minknow_api_keystore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreRequest) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *StoreRequest) GetLifetime() Lifetime {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Lifetime
		}
	}
	return Lifetime_UNTIL_NEXT_PROTOCOL_START
}

func (x *StoreRequest) SetValues(v map[string]*anypb.Any) {
	x.xxx_hidden_Values = v
}

func (x *StoreRequest) SetLifetime(v Lifetime) {
	x.xxx_hidden_Lifetime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StoreRequest) HasLifetime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreRequest) ClearLifetime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Lifetime = Lifetime_UNTIL_NEXT_PROTOCOL_START
}

type StoreRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The values to store.
	//
	// See the notes in the KeyStore service documentation about names - in short, for any values
	// not documented elsewhere, you should be prefixing the name with "<product>:", where <product>
	// is the name of your software product.
	Values map[string]*anypb.Any
	// Specify the lifetime of a value.
	//
	// When storing values in the manager, the only valid values are `UNTIL_INSTANCE_END` and
	// `PERSIST_ACROSS_RESTARTS`.  Using any other value will cause the call to fail with
	// `INVALID_ARGUMENT`
	//
	// Note that calling remove() will remove the value regardless of this setting.
	Lifetime *Lifetime
}

func (b0 StoreRequest_builder) Build() *StoreRequest {
	m0 := &StoreRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	if b.Lifetime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Lifetime = *b.Lifetime
	}
	return m0
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_minknow_api_keystore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StoreResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StoreResponse_builder) Build() *StoreResponse {
	m0 := &StoreResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RemoveRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names        []string               `protobuf:"bytes,1,rep,name=names"`
	xxx_hidden_AllowMissing bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_minknow_api_keystore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *RemoveRequest) GetAllowMissing() bool {
	if x != nil {
		return x.xxx_hidden_AllowMissing
	}
	return false
}

func (x *RemoveRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

func (x *RemoveRequest) SetAllowMissing(v bool) {
	x.xxx_hidden_AllowMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RemoveRequest) HasAllowMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RemoveRequest) ClearAllowMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllowMissing = false
}

type RemoveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The names of the values you wish to remove.
	Names []string
	// Whether to allow missing values.
	//
	// If set, names that are not present in the store will be ignored, but any present values will
	// still be removed. Otherwise, missing values will cause an error to be returned (in which case
	// nothing will be removed).
	//
	// Defaults to 'false'
	AllowMissing *bool
}

func (b0 RemoveRequest_builder) Build() *RemoveRequest {
	m0 := &RemoveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	if b.AllowMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AllowMissing = *b.AllowMissing
	}
	return m0
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_minknow_api_keystore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RemoveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RemoveResponse_builder) Build() *RemoveResponse {
	m0 := &RemoveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetOneRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_minknow_api_keystore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOneRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *GetOneRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetOneRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetOneRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type GetOneRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the value to fetch.
	Name *string
}

func (b0 GetOneRequest_builder) Build() *GetOneRequest {
	m0 := &GetOneRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type GetOneResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value *anypb.Any             `protobuf:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOneResponse) Reset() {
	*x = GetOneResponse{}
	mi := &file_minknow_api_keystore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneResponse) ProtoMessage() {}

func (x *GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOneResponse) GetValue() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetOneResponse) SetValue(v *anypb.Any) {
	x.xxx_hidden_Value = v
}

func (x *GetOneResponse) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *GetOneResponse) ClearValue() {
	x.xxx_hidden_Value = nil
}

type GetOneResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The requested value.
	Value *anypb.Any
}

func (b0 GetOneResponse_builder) Build() *GetOneResponse {
	m0 := &GetOneResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type GetRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names        []string               `protobuf:"bytes,1,rep,name=names"`
	xxx_hidden_AllowMissing bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_minknow_api_keystore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *GetRequest) GetAllowMissing() bool {
	if x != nil {
		return x.xxx_hidden_AllowMissing
	}
	return false
}

func (x *GetRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

func (x *GetRequest) SetAllowMissing(v bool) {
	x.xxx_hidden_AllowMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetRequest) HasAllowMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetRequest) ClearAllowMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllowMissing = false
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The names of the values you wish to fetch.
	Names []string
	// Whether to allow missing values.
	//
	// If set, names that are not present in the store will simply be omitted from the response.
	// Otherwise, missing values will cause an error to be returned.
	//
	// Defaults to 'false'
	AllowMissing *bool
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	if b.AllowMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AllowMissing = *b.AllowMissing
	}
	return m0
}

type GetResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values map[string]*anypb.Any  `protobuf:"bytes,1,rep,name=values" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_minknow_api_keystore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *GetResponse) SetValues(v map[string]*anypb.Any) {
	x.xxx_hidden_Values = v
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The requested values.
	Values map[string]*anypb.Any
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

type WatchRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names        []string               `protobuf:"bytes,1,rep,name=names"`
	xxx_hidden_AllowMissing bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_minknow_api_keystore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WatchRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *WatchRequest) GetAllowMissing() bool {
	if x != nil {
		return x.xxx_hidden_AllowMissing
	}
	return false
}

func (x *WatchRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

func (x *WatchRequest) SetAllowMissing(v bool) {
	x.xxx_hidden_AllowMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *WatchRequest) HasAllowMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *WatchRequest) ClearAllowMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllowMissing = false
}

type WatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The names of the values you wish to watch.
	Names []string
	// Whether to allow missing values.
	//
	// If set, names that are not present in the store will be omitted from the first response, but
	// will still be watched. If and when they are added, a message will be sent with the set
	// values. Otherwise, missing values will cause an immediate error.
	//
	// Defaults to 'false'
	AllowMissing *bool
}

func (b0 WatchRequest_builder) Build() *WatchRequest {
	m0 := &WatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	if b.AllowMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AllowMissing = *b.AllowMissing
	}
	return m0
}

type WatchResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values        map[string]*anypb.Any  `protobuf:"bytes,1,rep,name=values" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RemovedValues []string               `protobuf:"bytes,2,rep,name=removed_values,json=removedValues"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_minknow_api_keystore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_keystore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WatchResponse) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *WatchResponse) GetRemovedValues() []string {
	if x != nil {
		return x.xxx_hidden_RemovedValues
	}
	return nil
}

func (x *WatchResponse) SetValues(v map[string]*anypb.Any) {
	x.xxx_hidden_Values = v
}

func (x *WatchResponse) SetRemovedValues(v []string) {
	x.xxx_hidden_RemovedValues = v
}

type WatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The values that have changed.
	//
	// The first received message will contain the current state of all the watched values.
	// Subsequent messages will only contain the values that changed.
	Values map[string]*anypb.Any
	// The values that have been removed.
	RemovedValues []string
}

func (b0 WatchResponse_builder) Build() *WatchResponse {
	m0 := &WatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	x.xxx_hidden_RemovedValues = b.RemovedValues
	return m0
}

var File_minknow_api_keystore_proto protoreflect.FileDescriptor

const file_minknow_api_keystore_proto_rawDesc = "" +
	"\n" +
	"\x1aminknow_api/keystore.proto\x12\x14minknow_api.keystore\x1a\x19google/protobuf/any.proto\x1a\x1dminknow_api/rpc_options.proto\"\xe9\x01\n" +
	"\fStoreRequest\x12L\n" +
	"\x06values\x18\x01 \x03(\v2..minknow_api.keystore.StoreRequest.ValuesEntryB\x04\x88\xb5\x18\x01R\x06values\x12:\n" +
	"\blifetime\x18\x02 \x01(\x0e2\x1e.minknow_api.keystore.LifetimeR\blifetime\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x0f\n" +
	"\rStoreResponse\"P\n" +
	"\rRemoveRequest\x12\x1a\n" +
	"\x05names\x18\x01 \x03(\tB\x04\x88\xb5\x18\x01R\x05names\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\x10\n" +
	"\x0eRemoveResponse\")\n" +
	"\rGetOneRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\x04name\"<\n" +
	"\x0eGetOneResponse\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"G\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\xa5\x01\n" +
	"\vGetResponse\x12E\n" +
	"\x06values\x18\x01 \x03(\v2-.minknow_api.keystore.GetResponse.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"O\n" +
	"\fWatchRequest\x12\x1a\n" +
	"\x05names\x18\x01 \x03(\tB\x04\x88\xb5\x18\x01R\x05names\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\xd0\x01\n" +
	"\rWatchResponse\x12G\n" +
	"\x06values\x18\x01 \x03(\v2/.minknow_api.keystore.WatchResponse.ValuesEntryR\x06values\x12%\n" +
	"\x0eremoved_values\x18\x02 \x03(\tR\rremovedValues\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01*v\n" +
	"\bLifetime\x12\x1d\n" +
	"\x19UNTIL_NEXT_PROTOCOL_START\x10\x00\x12\x16\n" +
	"\x12UNTIL_PROTOCOL_END\x10\x01\x12\x16\n" +
	"\x12UNTIL_INSTANCE_END\x10\x02\x12\x1b\n" +
	"\x17PERSIST_ACROSS_RESTARTS\x10\x032\xc1\x03\n" +
	"\x0fKeyStoreService\x12R\n" +
	"\x05store\x12\".minknow_api.keystore.StoreRequest\x1a#.minknow_api.keystore.StoreResponse\"\x00\x12U\n" +
	"\x06remove\x12#.minknow_api.keystore.RemoveRequest\x1a$.minknow_api.keystore.RemoveResponse\"\x00\x12Y\n" +
	"\aget_one\x12#.minknow_api.keystore.GetOneRequest\x1a$.minknow_api.keystore.GetOneResponse\"\x03\x90\x02\x01\x12O\n" +
	"\x03get\x12 .minknow_api.keystore.GetRequest\x1a!.minknow_api.keystore.GetResponse\"\x03\x90\x02\x01\x12W\n" +
	"\x05watch\x12\".minknow_api.keystore.WatchRequest\x1a#.minknow_api.keystore.WatchResponse\"\x03\x90\x02\x010\x01B^\n" +
	"\x1ccom.nanoporetech.minknow_apiZ3github.com/nanoporetech/minknow_api/go/gen/keystore\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_keystore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minknow_api_keystore_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_minknow_api_keystore_proto_goTypes = []any{
	(Lifetime)(0),          // 0: minknow_api.keystore.Lifetime
	(*StoreRequest)(nil),   // 1: minknow_api.keystore.StoreRequest
	(*StoreResponse)(nil),  // 2: minknow_api.keystore.StoreResponse
	(*RemoveRequest)(nil),  // 3: minknow_api.keystore.RemoveRequest
	(*RemoveResponse)(nil), // 4: minknow_api.keystore.RemoveResponse
	(*GetOneRequest)(nil),  // 5: minknow_api.keystore.GetOneRequest
	(*GetOneResponse)(nil), // 6: minknow_api.keystore.GetOneResponse
	(*GetRequest)(nil),     // 7: minknow_api.keystore.GetRequest
	(*GetResponse)(nil),    // 8: minknow_api.keystore.GetResponse
	(*WatchRequest)(nil),   // 9: minknow_api.keystore.WatchRequest
	(*WatchResponse)(nil),  // 10: minknow_api.keystore.WatchResponse
	nil,                    // 11: minknow_api.keystore.StoreRequest.ValuesEntry
	nil,                    // 12: minknow_api.keystore.GetResponse.ValuesEntry
	nil,                    // 13: minknow_api.keystore.WatchResponse.ValuesEntry
	(*anypb.Any)(nil),      // 14: google.protobuf.Any
}
var file_minknow_api_keystore_proto_depIdxs = []int32{
	11, // 0: minknow_api.keystore.StoreRequest.values:type_name -> minknow_api.keystore.StoreRequest.ValuesEntry
	0,  // 1: minknow_api.keystore.StoreRequest.lifetime:type_name -> minknow_api.keystore.Lifetime
	14, // 2: minknow_api.keystore.GetOneResponse.value:type_name -> google.protobuf.Any
	12, // 3: minknow_api.keystore.GetResponse.values:type_name -> minknow_api.keystore.GetResponse.ValuesEntry
	13, // 4: minknow_api.keystore.WatchResponse.values:type_name -> minknow_api.keystore.WatchResponse.ValuesEntry
	14, // 5: minknow_api.keystore.StoreRequest.ValuesEntry.value:type_name -> google.protobuf.Any
	14, // 6: minknow_api.keystore.GetResponse.ValuesEntry.value:type_name -> google.protobuf.Any
	14, // 7: minknow_api.keystore.WatchResponse.ValuesEntry.value:type_name -> google.protobuf.Any
	1,  // 8: minknow_api.keystore.KeyStoreService.store:input_type -> minknow_api.keystore.StoreRequest
	3,  // 9: minknow_api.keystore.KeyStoreService.remove:input_type -> minknow_api.keystore.RemoveRequest
	5,  // 10: minknow_api.keystore.KeyStoreService.get_one:input_type -> minknow_api.keystore.GetOneRequest
	7,  // 11: minknow_api.keystore.KeyStoreService.get:input_type -> minknow_api.keystore.GetRequest
	9,  // 12: minknow_api.keystore.KeyStoreService.watch:input_type -> minknow_api.keystore.WatchRequest
	2,  // 13: minknow_api.keystore.KeyStoreService.store:output_type -> minknow_api.keystore.StoreResponse
	4,  // 14: minknow_api.keystore.KeyStoreService.remove:output_type -> minknow_api.keystore.RemoveResponse
	6,  // 15: minknow_api.keystore.KeyStoreService.get_one:output_type -> minknow_api.keystore.GetOneResponse
	8,  // 16: minknow_api.keystore.KeyStoreService.get:output_type -> minknow_api.keystore.GetResponse
	10, // 17: minknow_api.keystore.KeyStoreService.watch:output_type -> minknow_api.keystore.WatchResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_minknow_api_keystore_proto_init() }
func file_minknow_api_keystore_proto_init() {
	if File_minknow_api_keystore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_keystore_proto_rawDesc), len(file_minknow_api_keystore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_keystore_proto_goTypes,
		DependencyIndexes: file_minknow_api_keystore_proto_depIdxs,
		EnumInfos:         file_minknow_api_keystore_proto_enumTypes,
		MessageInfos:      file_minknow_api_keystore_proto_msgTypes,
	}.Build()
	File_minknow_api_keystore_proto = out.File
	file_minknow_api_keystore_proto_goTypes = nil
	file_minknow_api_keystore_proto_depIdxs = nil
}
