// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/log.proto

package log

import (
	_ "github.com/nanoporetech/minknow_api/go/gen/rpc_options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	// A debugging message
	Severity_MESSAGE_SEVERITY_TRACE Severity = 0
	// An informative user message
	Severity_MESSAGE_SEVERITY_INFO Severity = 1
	// A warning message
	Severity_MESSAGE_SEVERITY_WARNING Severity = 2
	// An error message
	Severity_MESSAGE_SEVERITY_ERROR Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "MESSAGE_SEVERITY_TRACE",
		1: "MESSAGE_SEVERITY_INFO",
		2: "MESSAGE_SEVERITY_WARNING",
		3: "MESSAGE_SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"MESSAGE_SEVERITY_TRACE":   0,
		"MESSAGE_SEVERITY_INFO":    1,
		"MESSAGE_SEVERITY_WARNING": 2,
		"MESSAGE_SEVERITY_ERROR":   3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_log_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_minknow_api_log_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CollectPingsStage int32

const (
	CollectPingsStage_PAUSING_PING_SERVICE         CollectPingsStage = 0
	CollectPingsStage_LOOKING_FOR_PING_FILES       CollectPingsStage = 1
	CollectPingsStage_CREATING_ARCHIVE             CollectPingsStage = 2
	CollectPingsStage_ADDING_PING_FILES_TO_ARCHIVE CollectPingsStage = 3
	CollectPingsStage_RESTARTING_PING_SERVICE      CollectPingsStage = 4
	CollectPingsStage_COMPLETE                     CollectPingsStage = 5
)

// Enum value maps for CollectPingsStage.
var (
	CollectPingsStage_name = map[int32]string{
		0: "PAUSING_PING_SERVICE",
		1: "LOOKING_FOR_PING_FILES",
		2: "CREATING_ARCHIVE",
		3: "ADDING_PING_FILES_TO_ARCHIVE",
		4: "RESTARTING_PING_SERVICE",
		5: "COMPLETE",
	}
	CollectPingsStage_value = map[string]int32{
		"PAUSING_PING_SERVICE":         0,
		"LOOKING_FOR_PING_FILES":       1,
		"CREATING_ARCHIVE":             2,
		"ADDING_PING_FILES_TO_ARCHIVE": 3,
		"RESTARTING_PING_SERVICE":      4,
		"COMPLETE":                     5,
	}
)

func (x CollectPingsStage) Enum() *CollectPingsStage {
	p := new(CollectPingsStage)
	*p = x
	return p
}

func (x CollectPingsStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectPingsStage) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_log_proto_enumTypes[1].Descriptor()
}

func (CollectPingsStage) Type() protoreflect.EnumType {
	return &file_minknow_api_log_proto_enumTypes[1]
}

func (x CollectPingsStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GetUserMessagesRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IncludeOldMessages bool                   `protobuf:"varint,1,opt,name=include_old_messages,json=includeOldMessages"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetUserMessagesRequest) Reset() {
	*x = GetUserMessagesRequest{}
	mi := &file_minknow_api_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessagesRequest) ProtoMessage() {}

func (x *GetUserMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetUserMessagesRequest) GetIncludeOldMessages() bool {
	if x != nil {
		return x.xxx_hidden_IncludeOldMessages
	}
	return false
}

func (x *GetUserMessagesRequest) SetIncludeOldMessages(v bool) {
	x.xxx_hidden_IncludeOldMessages = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetUserMessagesRequest) HasIncludeOldMessages() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetUserMessagesRequest) ClearIncludeOldMessages() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_IncludeOldMessages = false
}

type GetUserMessagesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// If set, any messages which have already been sent to listeners
	// will be sent to the new stream again, before new messages are sent.
	//
	// If not specified - the default will not send messages that were sent previously.
	//
	// note: there is a limit on how many messages are recorded for replay.
	IncludeOldMessages *bool
}

func (b0 GetUserMessagesRequest_builder) Build() *GetUserMessagesRequest {
	m0 := &GetUserMessagesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.IncludeOldMessages != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_IncludeOldMessages = *b.IncludeOldMessages
	}
	return m0
}

type UserMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Time        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time"`
	xxx_hidden_Severity    Severity               `protobuf:"varint,2,opt,name=severity,enum=minknow_api.log.Severity"`
	xxx_hidden_Identifier  *string                `protobuf:"bytes,3,opt,name=identifier"`
	xxx_hidden_UserMessage *string                `protobuf:"bytes,4,opt,name=user_message,json=userMessage"`
	xxx_hidden_ExtraData   map[string]string      `protobuf:"bytes,5,rep,name=extra_data,json=extraData" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_minknow_api_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *UserMessage) GetSeverity() Severity {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Severity
		}
	}
	return Severity_MESSAGE_SEVERITY_TRACE
}

func (x *UserMessage) GetIdentifier() string {
	if x != nil {
		if x.xxx_hidden_Identifier != nil {
			return *x.xxx_hidden_Identifier
		}
		return ""
	}
	return ""
}

func (x *UserMessage) GetUserMessage() string {
	if x != nil {
		if x.xxx_hidden_UserMessage != nil {
			return *x.xxx_hidden_UserMessage
		}
		return ""
	}
	return ""
}

func (x *UserMessage) GetExtraData() map[string]string {
	if x != nil {
		return x.xxx_hidden_ExtraData
	}
	return nil
}

func (x *UserMessage) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *UserMessage) SetSeverity(v Severity) {
	x.xxx_hidden_Severity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *UserMessage) SetIdentifier(v string) {
	x.xxx_hidden_Identifier = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *UserMessage) SetUserMessage(v string) {
	x.xxx_hidden_UserMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *UserMessage) SetExtraData(v map[string]string) {
	x.xxx_hidden_ExtraData = v
}

func (x *UserMessage) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *UserMessage) HasSeverity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserMessage) HasIdentifier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserMessage) HasUserMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserMessage) ClearTime() {
	x.xxx_hidden_Time = nil
}

func (x *UserMessage) ClearSeverity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Severity = Severity_MESSAGE_SEVERITY_TRACE
}

func (x *UserMessage) ClearIdentifier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Identifier = nil
}

func (x *UserMessage) ClearUserMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_UserMessage = nil
}

type UserMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Timestamp for when the log message was emitted
	Time *timestamppb.Timestamp
	// The severity of the message
	Severity *Severity
	// A short unique textual identifier for the message
	// Used to identify the message for translation purposes
	Identifier *string
	// A long user readable description of the message
	UserMessage *string
	// Any extra data associated with the user message, as a map from key to data.
	ExtraData map[string]string
}

func (b0 UserMessage_builder) Build() *UserMessage {
	m0 := &UserMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Time = b.Time
	if b.Severity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Severity = *b.Severity
	}
	if b.Identifier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Identifier = b.Identifier
	}
	if b.UserMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_UserMessage = b.UserMessage
	}
	x.xxx_hidden_ExtraData = b.ExtraData
	return m0
}

type SendUserMessageRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Severity    Severity               `protobuf:"varint,2,opt,name=severity,enum=minknow_api.log.Severity"`
	xxx_hidden_Identifier  *string                `protobuf:"bytes,3,opt,name=identifier"`
	xxx_hidden_UserMessage *string                `protobuf:"bytes,1,opt,name=user_message,json=userMessage"`
	xxx_hidden_ExtraData   map[string]string      `protobuf:"bytes,4,rep,name=extra_data,json=extraData" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SendUserMessageRequest) Reset() {
	*x = SendUserMessageRequest{}
	mi := &file_minknow_api_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMessageRequest) ProtoMessage() {}

func (x *SendUserMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SendUserMessageRequest) GetSeverity() Severity {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Severity
		}
	}
	return Severity_MESSAGE_SEVERITY_TRACE
}

func (x *SendUserMessageRequest) GetIdentifier() string {
	if x != nil {
		if x.xxx_hidden_Identifier != nil {
			return *x.xxx_hidden_Identifier
		}
		return ""
	}
	return ""
}

func (x *SendUserMessageRequest) GetUserMessage() string {
	if x != nil {
		if x.xxx_hidden_UserMessage != nil {
			return *x.xxx_hidden_UserMessage
		}
		return ""
	}
	return ""
}

func (x *SendUserMessageRequest) GetExtraData() map[string]string {
	if x != nil {
		return x.xxx_hidden_ExtraData
	}
	return nil
}

func (x *SendUserMessageRequest) SetSeverity(v Severity) {
	x.xxx_hidden_Severity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *SendUserMessageRequest) SetIdentifier(v string) {
	x.xxx_hidden_Identifier = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *SendUserMessageRequest) SetUserMessage(v string) {
	x.xxx_hidden_UserMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *SendUserMessageRequest) SetExtraData(v map[string]string) {
	x.xxx_hidden_ExtraData = v
}

func (x *SendUserMessageRequest) HasSeverity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SendUserMessageRequest) HasIdentifier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SendUserMessageRequest) HasUserMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SendUserMessageRequest) ClearSeverity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Severity = Severity_MESSAGE_SEVERITY_TRACE
}

func (x *SendUserMessageRequest) ClearIdentifier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Identifier = nil
}

func (x *SendUserMessageRequest) ClearUserMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UserMessage = nil
}

type SendUserMessageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The severity of the message to send
	//
	// note: TRACE messages cannot be sent using this interface (will throw an error).
	Severity *Severity
	// A short unique textual identifier for the message
	// Used to identify the message for translation purposes
	Identifier *string
	// The user message to send to any listeners.
	UserMessage *string
	// Any extra data associated with the user message, as a map from key to data.
	ExtraData map[string]string
}

func (b0 SendUserMessageRequest_builder) Build() *SendUserMessageRequest {
	m0 := &SendUserMessageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Severity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Severity = *b.Severity
	}
	if b.Identifier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Identifier = b.Identifier
	}
	if b.UserMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_UserMessage = b.UserMessage
	}
	x.xxx_hidden_ExtraData = b.ExtraData
	return m0
}

type SendUserMessageResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserMessageResponse) Reset() {
	*x = SendUserMessageResponse{}
	mi := &file_minknow_api_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMessageResponse) ProtoMessage() {}

func (x *SendUserMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SendUserMessageResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SendUserMessageResponse_builder) Build() *SendUserMessageResponse {
	m0 := &SendUserMessageResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SendPingRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PingData        *string                `protobuf:"bytes,1,opt,name=ping_data,json=pingData"`
	xxx_hidden_DaysUntilExpiry uint64                 `protobuf:"varint,2,opt,name=days_until_expiry,json=daysUntilExpiry"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SendPingRequest) Reset() {
	*x = SendPingRequest{}
	mi := &file_minknow_api_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPingRequest) ProtoMessage() {}

func (x *SendPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SendPingRequest) GetPingData() string {
	if x != nil {
		if x.xxx_hidden_PingData != nil {
			return *x.xxx_hidden_PingData
		}
		return ""
	}
	return ""
}

func (x *SendPingRequest) GetDaysUntilExpiry() uint64 {
	if x != nil {
		return x.xxx_hidden_DaysUntilExpiry
	}
	return 0
}

func (x *SendPingRequest) SetPingData(v string) {
	x.xxx_hidden_PingData = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SendPingRequest) SetDaysUntilExpiry(v uint64) {
	x.xxx_hidden_DaysUntilExpiry = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SendPingRequest) HasPingData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SendPingRequest) HasDaysUntilExpiry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SendPingRequest) ClearPingData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PingData = nil
}

func (x *SendPingRequest) ClearDaysUntilExpiry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DaysUntilExpiry = 0
}

type SendPingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The json data to send as a ping.
	//
	// note: if this string is not a valid json object, an error will be raised.
	PingData *string
	// Should the ping fail to send, the number of days the ping will be stored
	// before being cleaned up.
	DaysUntilExpiry *uint64
}

func (b0 SendPingRequest_builder) Build() *SendPingRequest {
	m0 := &SendPingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PingData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PingData = b.PingData
	}
	if b.DaysUntilExpiry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DaysUntilExpiry = *b.DaysUntilExpiry
	}
	return m0
}

type SendPingResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPingResponse) Reset() {
	*x = SendPingResponse{}
	mi := &file_minknow_api_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPingResponse) ProtoMessage() {}

func (x *SendPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SendPingResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SendPingResponse_builder) Build() *SendPingResponse {
	m0 := &SendPingResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CollectPingsRequest struct {
	state                                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CollectedPingFile              *string                `protobuf:"bytes,1,opt,name=collected_ping_file,json=collectedPingFile"`
	xxx_hidden_IncludePreviouslyCollecedPings bool                   `protobuf:"varint,2,opt,name=include_previously_colleced_pings,json=includePreviouslyCollecedPings"`
	XXX_raceDetectHookData                    protoimpl.RaceDetectHookData
	XXX_presence                              [1]uint32
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *CollectPingsRequest) Reset() {
	*x = CollectPingsRequest{}
	mi := &file_minknow_api_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPingsRequest) ProtoMessage() {}

func (x *CollectPingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CollectPingsRequest) GetCollectedPingFile() string {
	if x != nil {
		if x.xxx_hidden_CollectedPingFile != nil {
			return *x.xxx_hidden_CollectedPingFile
		}
		return ""
	}
	return ""
}

func (x *CollectPingsRequest) GetIncludePreviouslyCollecedPings() bool {
	if x != nil {
		return x.xxx_hidden_IncludePreviouslyCollecedPings
	}
	return false
}

func (x *CollectPingsRequest) SetCollectedPingFile(v string) {
	x.xxx_hidden_CollectedPingFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CollectPingsRequest) SetIncludePreviouslyCollecedPings(v bool) {
	x.xxx_hidden_IncludePreviouslyCollecedPings = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CollectPingsRequest) HasCollectedPingFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CollectPingsRequest) HasIncludePreviouslyCollecedPings() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CollectPingsRequest) ClearCollectedPingFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CollectedPingFile = nil
}

func (x *CollectPingsRequest) ClearIncludePreviouslyCollecedPings() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IncludePreviouslyCollecedPings = false
}

type CollectPingsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Any pings that are queued to be sent will be collected into a zip file
	// and written to this location. This location must be in a folder writable
	// by minknow. If the file name does not end with ".zip", minknow will
	// append ".zip" to the provided file name.
	CollectedPingFile *string
	// Normally previously collected pings are ignored, but by setting this they
	// will be included. Defaults to False.
	IncludePreviouslyCollecedPings *bool
}

func (b0 CollectPingsRequest_builder) Build() *CollectPingsRequest {
	m0 := &CollectPingsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CollectedPingFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_CollectedPingFile = b.CollectedPingFile
	}
	if b.IncludePreviouslyCollecedPings != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_IncludePreviouslyCollecedPings = *b.IncludePreviouslyCollecedPings
	}
	return m0
}

type CollectPingsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stage       CollectPingsStage      `protobuf:"varint,1,opt,name=stage,enum=minknow_api.log.CollectPingsStage"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CollectPingsResponse) Reset() {
	*x = CollectPingsResponse{}
	mi := &file_minknow_api_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPingsResponse) ProtoMessage() {}

func (x *CollectPingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CollectPingsResponse) GetStage() CollectPingsStage {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Stage
		}
	}
	return CollectPingsStage_PAUSING_PING_SERVICE
}

func (x *CollectPingsResponse) SetStage(v CollectPingsStage) {
	x.xxx_hidden_Stage = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CollectPingsResponse) HasStage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CollectPingsResponse) ClearStage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Stage = CollectPingsStage_PAUSING_PING_SERVICE
}

type CollectPingsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stage *CollectPingsStage
}

func (b0 CollectPingsResponse_builder) Build() *CollectPingsResponse {
	m0 := &CollectPingsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Stage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Stage = *b.Stage
	}
	return m0
}

var File_minknow_api_log_proto protoreflect.FileDescriptor

const file_minknow_api_log_proto_rawDesc = "" +
	"\n" +
	"\x15minknow_api/log.proto\x12\x0fminknow_api.log\x1a\x1dminknow_api/rpc_options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x16GetUserMessagesRequest\x120\n" +
	"\x14include_old_messages\x18\x01 \x01(\bR\x12includeOldMessages\"\xd3\x02\n" +
	"\vUserMessage\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x125\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x19.minknow_api.log.SeverityR\bseverity\x12$\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tB\x04\xa0\xb5\x18\x00R\n" +
	"identifier\x12'\n" +
	"\fuser_message\x18\x04 \x01(\tB\x04\xa0\xb5\x18\x01R\vuserMessage\x12P\n" +
	"\n" +
	"extra_data\x18\x05 \x03(\v2+.minknow_api.log.UserMessage.ExtraDataEntryB\x04\xa0\xb5\x18\x01R\textraData\x1a<\n" +
	"\x0eExtraDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\x16SendUserMessageRequest\x12;\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x19.minknow_api.log.SeverityB\x04\x88\xb5\x18\x01R\bseverity\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\x12'\n" +
	"\fuser_message\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\vuserMessage\x12U\n" +
	"\n" +
	"extra_data\x18\x04 \x03(\v26.minknow_api.log.SendUserMessageRequest.ExtraDataEntryR\textraData\x1a<\n" +
	"\x0eExtraDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17SendUserMessageResponse\"`\n" +
	"\x0fSendPingRequest\x12!\n" +
	"\tping_data\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\bpingData\x12*\n" +
	"\x11days_until_expiry\x18\x02 \x01(\x04R\x0fdaysUntilExpiry\"\x12\n" +
	"\x10SendPingResponse\"\x96\x01\n" +
	"\x13CollectPingsRequest\x124\n" +
	"\x13collected_ping_file\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\x11collectedPingFile\x12I\n" +
	"!include_previously_colleced_pings\x18\x02 \x01(\bR\x1eincludePreviouslyCollecedPings\"P\n" +
	"\x14CollectPingsResponse\x128\n" +
	"\x05stage\x18\x01 \x01(\x0e2\".minknow_api.log.CollectPingsStageR\x05stage*{\n" +
	"\bSeverity\x12\x1a\n" +
	"\x16MESSAGE_SEVERITY_TRACE\x10\x00\x12\x19\n" +
	"\x15MESSAGE_SEVERITY_INFO\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_SEVERITY_WARNING\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_SEVERITY_ERROR\x10\x03*\xac\x01\n" +
	"\x11CollectPingsStage\x12\x18\n" +
	"\x14PAUSING_PING_SERVICE\x10\x00\x12\x1a\n" +
	"\x16LOOKING_FOR_PING_FILES\x10\x01\x12\x14\n" +
	"\x10CREATING_ARCHIVE\x10\x02\x12 \n" +
	"\x1cADDING_PING_FILES_TO_ARCHIVE\x10\x03\x12\x1b\n" +
	"\x17RESTARTING_PING_SERVICE\x10\x04\x12\f\n" +
	"\bCOMPLETE\x10\x052\x8c\x03\n" +
	"\n" +
	"LogService\x12^\n" +
	"\x11get_user_messages\x12'.minknow_api.log.GetUserMessagesRequest\x1a\x1c.minknow_api.log.UserMessage\"\x000\x01\x12h\n" +
	"\x11send_user_message\x12'.minknow_api.log.SendUserMessageRequest\x1a(.minknow_api.log.SendUserMessageResponse\"\x00\x12R\n" +
	"\tsend_ping\x12 .minknow_api.log.SendPingRequest\x1a!.minknow_api.log.SendPingResponse\"\x00\x12`\n" +
	"\rcollect_pings\x12$.minknow_api.log.CollectPingsRequest\x1a%.minknow_api.log.CollectPingsResponse\"\x000\x01BY\n" +
	"\x1ccom.nanoporetech.minknow_apiZ.github.com/nanoporetech/minknow_api/go/gen/log\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_log_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_minknow_api_log_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_minknow_api_log_proto_goTypes = []any{
	(Severity)(0),                   // 0: minknow_api.log.Severity
	(CollectPingsStage)(0),          // 1: minknow_api.log.CollectPingsStage
	(*GetUserMessagesRequest)(nil),  // 2: minknow_api.log.GetUserMessagesRequest
	(*UserMessage)(nil),             // 3: minknow_api.log.UserMessage
	(*SendUserMessageRequest)(nil),  // 4: minknow_api.log.SendUserMessageRequest
	(*SendUserMessageResponse)(nil), // 5: minknow_api.log.SendUserMessageResponse
	(*SendPingRequest)(nil),         // 6: minknow_api.log.SendPingRequest
	(*SendPingResponse)(nil),        // 7: minknow_api.log.SendPingResponse
	(*CollectPingsRequest)(nil),     // 8: minknow_api.log.CollectPingsRequest
	(*CollectPingsResponse)(nil),    // 9: minknow_api.log.CollectPingsResponse
	nil,                             // 10: minknow_api.log.UserMessage.ExtraDataEntry
	nil,                             // 11: minknow_api.log.SendUserMessageRequest.ExtraDataEntry
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_minknow_api_log_proto_depIdxs = []int32{
	12, // 0: minknow_api.log.UserMessage.time:type_name -> google.protobuf.Timestamp
	0,  // 1: minknow_api.log.UserMessage.severity:type_name -> minknow_api.log.Severity
	10, // 2: minknow_api.log.UserMessage.extra_data:type_name -> minknow_api.log.UserMessage.ExtraDataEntry
	0,  // 3: minknow_api.log.SendUserMessageRequest.severity:type_name -> minknow_api.log.Severity
	11, // 4: minknow_api.log.SendUserMessageRequest.extra_data:type_name -> minknow_api.log.SendUserMessageRequest.ExtraDataEntry
	1,  // 5: minknow_api.log.CollectPingsResponse.stage:type_name -> minknow_api.log.CollectPingsStage
	2,  // 6: minknow_api.log.LogService.get_user_messages:input_type -> minknow_api.log.GetUserMessagesRequest
	4,  // 7: minknow_api.log.LogService.send_user_message:input_type -> minknow_api.log.SendUserMessageRequest
	6,  // 8: minknow_api.log.LogService.send_ping:input_type -> minknow_api.log.SendPingRequest
	8,  // 9: minknow_api.log.LogService.collect_pings:input_type -> minknow_api.log.CollectPingsRequest
	3,  // 10: minknow_api.log.LogService.get_user_messages:output_type -> minknow_api.log.UserMessage
	5,  // 11: minknow_api.log.LogService.send_user_message:output_type -> minknow_api.log.SendUserMessageResponse
	7,  // 12: minknow_api.log.LogService.send_ping:output_type -> minknow_api.log.SendPingResponse
	9,  // 13: minknow_api.log.LogService.collect_pings:output_type -> minknow_api.log.CollectPingsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_minknow_api_log_proto_init() }
func file_minknow_api_log_proto_init() {
	if File_minknow_api_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_log_proto_rawDesc), len(file_minknow_api_log_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_log_proto_goTypes,
		DependencyIndexes: file_minknow_api_log_proto_depIdxs,
		EnumInfos:         file_minknow_api_log_proto_enumTypes,
		MessageInfos:      file_minknow_api_log_proto_msgTypes,
	}.Build()
	File_minknow_api_log_proto = out.File
	file_minknow_api_log_proto_goTypes = nil
	file_minknow_api_log_proto_depIdxs = nil
}
