// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/minion_device.proto

package minion_device

import (
	_ "github.com/nanoporetech/minknow_api/go/gen/rpc_options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Linting ignored for historical reasons.
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
type SamplingFrequencyParameters_ClockSpeed int32

const (
	SamplingFrequencyParameters_CLOCK_128MHz SamplingFrequencyParameters_ClockSpeed = 0
	SamplingFrequencyParameters_CLOCK_64MHz  SamplingFrequencyParameters_ClockSpeed = 1
	SamplingFrequencyParameters_CLOCK_32MHz  SamplingFrequencyParameters_ClockSpeed = 2
	SamplingFrequencyParameters_CLOCK_16MHz  SamplingFrequencyParameters_ClockSpeed = 3
	SamplingFrequencyParameters_CLOCK_8MHz   SamplingFrequencyParameters_ClockSpeed = 4
)

// Enum value maps for SamplingFrequencyParameters_ClockSpeed.
var (
	SamplingFrequencyParameters_ClockSpeed_name = map[int32]string{
		0: "CLOCK_128MHz",
		1: "CLOCK_64MHz",
		2: "CLOCK_32MHz",
		3: "CLOCK_16MHz",
		4: "CLOCK_8MHz",
	}
	SamplingFrequencyParameters_ClockSpeed_value = map[string]int32{
		"CLOCK_128MHz": 0,
		"CLOCK_64MHz":  1,
		"CLOCK_32MHz":  2,
		"CLOCK_16MHz":  3,
		"CLOCK_8MHz":   4,
	}
)

func (x SamplingFrequencyParameters_ClockSpeed) Enum() *SamplingFrequencyParameters_ClockSpeed {
	p := new(SamplingFrequencyParameters_ClockSpeed)
	*p = x
	return p
}

func (x SamplingFrequencyParameters_ClockSpeed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SamplingFrequencyParameters_ClockSpeed) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[0].Descriptor()
}

func (SamplingFrequencyParameters_ClockSpeed) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[0]
}

func (x SamplingFrequencyParameters_ClockSpeed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MinionDeviceSettings_Gain int32

const (
	MinionDeviceSettings_GAIN_KEEP MinionDeviceSettings_Gain = 0
	MinionDeviceSettings_GAIN_1    MinionDeviceSettings_Gain = 1
	MinionDeviceSettings_GAIN_5    MinionDeviceSettings_Gain = 2
)

// Enum value maps for MinionDeviceSettings_Gain.
var (
	MinionDeviceSettings_Gain_name = map[int32]string{
		0: "GAIN_KEEP",
		1: "GAIN_1",
		2: "GAIN_5",
	}
	MinionDeviceSettings_Gain_value = map[string]int32{
		"GAIN_KEEP": 0,
		"GAIN_1":    1,
		"GAIN_5":    2,
	}
)

func (x MinionDeviceSettings_Gain) Enum() *MinionDeviceSettings_Gain {
	p := new(MinionDeviceSettings_Gain)
	*p = x
	return p
}

func (x MinionDeviceSettings_Gain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_Gain) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[1].Descriptor()
}

func (MinionDeviceSettings_Gain) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[1]
}

func (x MinionDeviceSettings_Gain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MinionDeviceSettings_Decimation int32

const (
	MinionDeviceSettings_DECIMATION_KEEP MinionDeviceSettings_Decimation = 0
	MinionDeviceSettings_DECIMATION_32   MinionDeviceSettings_Decimation = 1
	MinionDeviceSettings_DECIMATION_64   MinionDeviceSettings_Decimation = 2
)

// Enum value maps for MinionDeviceSettings_Decimation.
var (
	MinionDeviceSettings_Decimation_name = map[int32]string{
		0: "DECIMATION_KEEP",
		1: "DECIMATION_32",
		2: "DECIMATION_64",
	}
	MinionDeviceSettings_Decimation_value = map[string]int32{
		"DECIMATION_KEEP": 0,
		"DECIMATION_32":   1,
		"DECIMATION_64":   2,
	}
)

func (x MinionDeviceSettings_Decimation) Enum() *MinionDeviceSettings_Decimation {
	p := new(MinionDeviceSettings_Decimation)
	*p = x
	return p
}

func (x MinionDeviceSettings_Decimation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_Decimation) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[2].Descriptor()
}

func (MinionDeviceSettings_Decimation) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[2]
}

func (x MinionDeviceSettings_Decimation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Linting ignored for historical reasons.
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
type MinionDeviceSettings_LowPassFilter int32

const (
	MinionDeviceSettings_LPF_KEEP     MinionDeviceSettings_LowPassFilter = 0
	MinionDeviceSettings_LPF_5kHz     MinionDeviceSettings_LowPassFilter = 1
	MinionDeviceSettings_LPF_10kHz    MinionDeviceSettings_LowPassFilter = 2
	MinionDeviceSettings_LPF_20kHz    MinionDeviceSettings_LowPassFilter = 3
	MinionDeviceSettings_LPF_40kHz    MinionDeviceSettings_LowPassFilter = 4
	MinionDeviceSettings_LPF_80kHz    MinionDeviceSettings_LowPassFilter = 5
	MinionDeviceSettings_LPF_DISABLED MinionDeviceSettings_LowPassFilter = 6
)

// Enum value maps for MinionDeviceSettings_LowPassFilter.
var (
	MinionDeviceSettings_LowPassFilter_name = map[int32]string{
		0: "LPF_KEEP",
		1: "LPF_5kHz",
		2: "LPF_10kHz",
		3: "LPF_20kHz",
		4: "LPF_40kHz",
		5: "LPF_80kHz",
		6: "LPF_DISABLED",
	}
	MinionDeviceSettings_LowPassFilter_value = map[string]int32{
		"LPF_KEEP":     0,
		"LPF_5kHz":     1,
		"LPF_10kHz":    2,
		"LPF_20kHz":    3,
		"LPF_40kHz":    4,
		"LPF_80kHz":    5,
		"LPF_DISABLED": 6,
	}
)

func (x MinionDeviceSettings_LowPassFilter) Enum() *MinionDeviceSettings_LowPassFilter {
	p := new(MinionDeviceSettings_LowPassFilter)
	*p = x
	return p
}

func (x MinionDeviceSettings_LowPassFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_LowPassFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[3].Descriptor()
}

func (MinionDeviceSettings_LowPassFilter) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[3]
}

func (x MinionDeviceSettings_LowPassFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MinionDeviceSettings_NonOverlapClock int32

const (
	MinionDeviceSettings_NOC_KEEP       MinionDeviceSettings_NonOverlapClock = 0
	MinionDeviceSettings_NOC_1_HS_CLOCK MinionDeviceSettings_NonOverlapClock = 1
	MinionDeviceSettings_NOC_2_HS_CLOCK MinionDeviceSettings_NonOverlapClock = 2
)

// Enum value maps for MinionDeviceSettings_NonOverlapClock.
var (
	MinionDeviceSettings_NonOverlapClock_name = map[int32]string{
		0: "NOC_KEEP",
		1: "NOC_1_HS_CLOCK",
		2: "NOC_2_HS_CLOCK",
	}
	MinionDeviceSettings_NonOverlapClock_value = map[string]int32{
		"NOC_KEEP":       0,
		"NOC_1_HS_CLOCK": 1,
		"NOC_2_HS_CLOCK": 2,
	}
)

func (x MinionDeviceSettings_NonOverlapClock) Enum() *MinionDeviceSettings_NonOverlapClock {
	p := new(MinionDeviceSettings_NonOverlapClock)
	*p = x
	return p
}

func (x MinionDeviceSettings_NonOverlapClock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_NonOverlapClock) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[4].Descriptor()
}

func (MinionDeviceSettings_NonOverlapClock) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[4]
}

func (x MinionDeviceSettings_NonOverlapClock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Linting ignored for historical reasons.
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
type MinionDeviceSettings_IntegrationCapacitor int32

const (
	MinionDeviceSettings_INTCAP_KEEP     MinionDeviceSettings_IntegrationCapacitor = 0
	MinionDeviceSettings_INTCAP_62_5fF   MinionDeviceSettings_IntegrationCapacitor = 1
	MinionDeviceSettings_INTCAP_250fF    MinionDeviceSettings_IntegrationCapacitor = 2
	MinionDeviceSettings_INTCAP_1pF      MinionDeviceSettings_IntegrationCapacitor = 3
	MinionDeviceSettings_INTCAP_1_1875pF MinionDeviceSettings_IntegrationCapacitor = 4
)

// Enum value maps for MinionDeviceSettings_IntegrationCapacitor.
var (
	MinionDeviceSettings_IntegrationCapacitor_name = map[int32]string{
		0: "INTCAP_KEEP",
		1: "INTCAP_62_5fF",
		2: "INTCAP_250fF",
		3: "INTCAP_1pF",
		4: "INTCAP_1_1875pF",
	}
	MinionDeviceSettings_IntegrationCapacitor_value = map[string]int32{
		"INTCAP_KEEP":     0,
		"INTCAP_62_5fF":   1,
		"INTCAP_250fF":    2,
		"INTCAP_1pF":      3,
		"INTCAP_1_1875pF": 4,
	}
)

func (x MinionDeviceSettings_IntegrationCapacitor) Enum() *MinionDeviceSettings_IntegrationCapacitor {
	p := new(MinionDeviceSettings_IntegrationCapacitor)
	*p = x
	return p
}

func (x MinionDeviceSettings_IntegrationCapacitor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_IntegrationCapacitor) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[5].Descriptor()
}

func (MinionDeviceSettings_IntegrationCapacitor) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[5]
}

func (x MinionDeviceSettings_IntegrationCapacitor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MinionDeviceSettings_FanSpeed int32

const (
	MinionDeviceSettings_FANSPEED_KEEP MinionDeviceSettings_FanSpeed = 0
	MinionDeviceSettings_FANSPEED_OFF  MinionDeviceSettings_FanSpeed = 1
	MinionDeviceSettings_FANSPEED_LOW  MinionDeviceSettings_FanSpeed = 2
	MinionDeviceSettings_FANSPEED_HIGH MinionDeviceSettings_FanSpeed = 3
	MinionDeviceSettings_FANSPEED_MAX  MinionDeviceSettings_FanSpeed = 4
)

// Enum value maps for MinionDeviceSettings_FanSpeed.
var (
	MinionDeviceSettings_FanSpeed_name = map[int32]string{
		0: "FANSPEED_KEEP",
		1: "FANSPEED_OFF",
		2: "FANSPEED_LOW",
		3: "FANSPEED_HIGH",
		4: "FANSPEED_MAX",
	}
	MinionDeviceSettings_FanSpeed_value = map[string]int32{
		"FANSPEED_KEEP": 0,
		"FANSPEED_OFF":  1,
		"FANSPEED_LOW":  2,
		"FANSPEED_HIGH": 3,
		"FANSPEED_MAX":  4,
	}
)

func (x MinionDeviceSettings_FanSpeed) Enum() *MinionDeviceSettings_FanSpeed {
	p := new(MinionDeviceSettings_FanSpeed)
	*p = x
	return p
}

func (x MinionDeviceSettings_FanSpeed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_FanSpeed) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[6].Descriptor()
}

func (MinionDeviceSettings_FanSpeed) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[6]
}

func (x MinionDeviceSettings_FanSpeed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The configuration for a channel.
type MinionDeviceSettings_ChannelConfig int32

const (
	// Keep the existing channel configuration.
	MinionDeviceSettings_CHANNEL_CONFIG_KEEP MinionDeviceSettings_ChannelConfig = 0
	// Disconnect the channel completely.
	MinionDeviceSettings_DISCONNECTED MinionDeviceSettings_ChannelConfig = 1
	// Normal measurement through well 1.
	//
	// The voltage level can be adjusted with the bias_voltage setting.
	MinionDeviceSettings_WELL_1_BIAS_VOLTAGE MinionDeviceSettings_ChannelConfig = 2
	// Normal measurement through well 2.
	//
	// The voltage level can be adjusted with the bias_voltage setting.
	MinionDeviceSettings_WELL_2_BIAS_VOLTAGE MinionDeviceSettings_ChannelConfig = 3
	// Normal measurement through well 3.
	//
	// The voltage level can be adjusted with the bias_voltage setting.
	MinionDeviceSettings_WELL_3_BIAS_VOLTAGE MinionDeviceSettings_ChannelConfig = 4
	// Normal measurement through well 4.
	//
	// The voltage level can be adjusted with the bias_voltage setting.
	MinionDeviceSettings_WELL_4_BIAS_VOLTAGE MinionDeviceSettings_ChannelConfig = 5
	// Send a test current through the channel.
	//
	// This is an electronics-only connection: the channel is otherwise disconnected. It can be
	// used for calibrating the measurement circuitry.
	//
	// The current level can be adjusted with the test_current setting.
	MinionDeviceSettings_TEST_CURRENT MinionDeviceSettings_ChannelConfig = 6
	// Reverse voltage through well 1.
	//
	// This can be used to clear the well.
	MinionDeviceSettings_WELL_1_UNBLOCK_VOLTAGE MinionDeviceSettings_ChannelConfig = 7
	// Reverse voltage through well 2.
	//
	// This can be used to clear the well.
	MinionDeviceSettings_WELL_2_UNBLOCK_VOLTAGE MinionDeviceSettings_ChannelConfig = 8
	// Reverse voltage through well 3.
	//
	// This can be used to clear the well.
	MinionDeviceSettings_WELL_3_UNBLOCK_VOLTAGE MinionDeviceSettings_ChannelConfig = 9
	// Reverse voltage through well 4.
	//
	// This can be used to clear the well.
	MinionDeviceSettings_WELL_4_UNBLOCK_VOLTAGE MinionDeviceSettings_ChannelConfig = 10
	// Send a test current via the switch circuit for well 1.
	//
	// This is only necessary for testing the chip electronics. It should not normally be used.
	//
	// The current level can be adjusted with the test_current setting.
	MinionDeviceSettings_TEST_CURRENT_VIA_WELL_1 MinionDeviceSettings_ChannelConfig = 11
	// Send a test current via the switch circuit for well 2.
	//
	// This is only necessary for testing the chip electronics. It should not normally be used.
	//
	// The current level can be adjusted with the test_current setting.
	MinionDeviceSettings_TEST_CURRENT_VIA_WELL_2 MinionDeviceSettings_ChannelConfig = 12
	// Send a test current via the switch circuit for well 3.
	//
	// This is only necessary for testing the chip electronics. It should not normally be used.
	//
	// The current level can be adjusted with the test_current setting.
	MinionDeviceSettings_TEST_CURRENT_VIA_WELL_3 MinionDeviceSettings_ChannelConfig = 13
	// Send a test current via the switch circuit for well 4.
	//
	// This is only necessary for testing the chip electronics. It should not normally be used.
	//
	// The current level can be adjusted with the test_current setting.
	MinionDeviceSettings_TEST_CURRENT_VIA_WELL_4 MinionDeviceSettings_ChannelConfig = 14
	// Connect the channel sensors to ground via a 4MOhm resistor.
	//
	// This is only necessary for testing the chip electronics. It should not normally be used.
	MinionDeviceSettings_GROUND_THROUGH_RESISTOR MinionDeviceSettings_ChannelConfig = 15
	// Connect the channel sensors to ground.
	//
	// This is only necessary for testing the chip electronics. It should not normally be used.
	MinionDeviceSettings_GROUND MinionDeviceSettings_ChannelConfig = 16
)

// Enum value maps for MinionDeviceSettings_ChannelConfig.
var (
	MinionDeviceSettings_ChannelConfig_name = map[int32]string{
		0:  "CHANNEL_CONFIG_KEEP",
		1:  "DISCONNECTED",
		2:  "WELL_1_BIAS_VOLTAGE",
		3:  "WELL_2_BIAS_VOLTAGE",
		4:  "WELL_3_BIAS_VOLTAGE",
		5:  "WELL_4_BIAS_VOLTAGE",
		6:  "TEST_CURRENT",
		7:  "WELL_1_UNBLOCK_VOLTAGE",
		8:  "WELL_2_UNBLOCK_VOLTAGE",
		9:  "WELL_3_UNBLOCK_VOLTAGE",
		10: "WELL_4_UNBLOCK_VOLTAGE",
		11: "TEST_CURRENT_VIA_WELL_1",
		12: "TEST_CURRENT_VIA_WELL_2",
		13: "TEST_CURRENT_VIA_WELL_3",
		14: "TEST_CURRENT_VIA_WELL_4",
		15: "GROUND_THROUGH_RESISTOR",
		16: "GROUND",
	}
	MinionDeviceSettings_ChannelConfig_value = map[string]int32{
		"CHANNEL_CONFIG_KEEP":     0,
		"DISCONNECTED":            1,
		"WELL_1_BIAS_VOLTAGE":     2,
		"WELL_2_BIAS_VOLTAGE":     3,
		"WELL_3_BIAS_VOLTAGE":     4,
		"WELL_4_BIAS_VOLTAGE":     5,
		"TEST_CURRENT":            6,
		"WELL_1_UNBLOCK_VOLTAGE":  7,
		"WELL_2_UNBLOCK_VOLTAGE":  8,
		"WELL_3_UNBLOCK_VOLTAGE":  9,
		"WELL_4_UNBLOCK_VOLTAGE":  10,
		"TEST_CURRENT_VIA_WELL_1": 11,
		"TEST_CURRENT_VIA_WELL_2": 12,
		"TEST_CURRENT_VIA_WELL_3": 13,
		"TEST_CURRENT_VIA_WELL_4": 14,
		"GROUND_THROUGH_RESISTOR": 15,
		"GROUND":                  16,
	}
)

func (x MinionDeviceSettings_ChannelConfig) Enum() *MinionDeviceSettings_ChannelConfig {
	p := new(MinionDeviceSettings_ChannelConfig)
	*p = x
	return p
}

func (x MinionDeviceSettings_ChannelConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinionDeviceSettings_ChannelConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_minion_device_proto_enumTypes[7].Descriptor()
}

func (MinionDeviceSettings_ChannelConfig) Type() protoreflect.EnumType {
	return &file_minknow_api_minion_device_proto_enumTypes[7]
}

func (x MinionDeviceSettings_ChannelConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Temperature range.
type TemperatureRange struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Min         float32                `protobuf:"fixed32,5,opt,name=min"`
	xxx_hidden_Max         float32                `protobuf:"fixed32,6,opt,name=max"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TemperatureRange) Reset() {
	*x = TemperatureRange{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureRange) ProtoMessage() {}

func (x *TemperatureRange) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TemperatureRange) GetMin() float32 {
	if x != nil {
		return x.xxx_hidden_Min
	}
	return 0
}

func (x *TemperatureRange) GetMax() float32 {
	if x != nil {
		return x.xxx_hidden_Max
	}
	return 0
}

func (x *TemperatureRange) SetMin(v float32) {
	x.xxx_hidden_Min = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TemperatureRange) SetMax(v float32) {
	x.xxx_hidden_Max = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TemperatureRange) HasMin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TemperatureRange) HasMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TemperatureRange) ClearMin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Min = 0
}

func (x *TemperatureRange) ClearMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Max = 0
}

type TemperatureRange_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The minimum temperature in degrees Celsius.
	//
	// If temperature control is enabled, the device will attempt to keep its temperature at or
	// above this value.
	//
	// Must be less than or equal to max.
	//
	// When soft temperature control is enabled, this value is not used.
	Min *float32
	// The maximum temperature in degrees Celsius.
	//
	// If temperature control is enabled, the device will attempt to keep its temperature at or
	// below this value.
	//
	// Must be less than or equal to min.
	//
	// When soft temperature control is enabled, this is used as the target temperature, and “min“
	// is not used.
	Max *float32
}

func (b0 TemperatureRange_builder) Build() *TemperatureRange {
	m0 := &TemperatureRange{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Min != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Min = *b.Min
	}
	if b.Max != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Max = *b.Max
	}
	return m0
}

// These values control the sampling frequency.
type SamplingFrequencyParameters struct {
	state                      protoimpl.MessageState                 `protogen:"opaque.v1"`
	xxx_hidden_ClockDivider    uint32                                 `protobuf:"varint,1,opt,name=clock_divider,json=clockDivider"`
	xxx_hidden_IntegrationTime uint32                                 `protobuf:"varint,2,opt,name=integration_time,json=integrationTime"`
	xxx_hidden_ClockSpeed      SamplingFrequencyParameters_ClockSpeed `protobuf:"varint,3,opt,name=clock_speed,json=clockSpeed,enum=minknow_api.minion_device.SamplingFrequencyParameters_ClockSpeed"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SamplingFrequencyParameters) Reset() {
	*x = SamplingFrequencyParameters{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingFrequencyParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingFrequencyParameters) ProtoMessage() {}

func (x *SamplingFrequencyParameters) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SamplingFrequencyParameters) GetClockDivider() uint32 {
	if x != nil {
		return x.xxx_hidden_ClockDivider
	}
	return 0
}

func (x *SamplingFrequencyParameters) GetIntegrationTime() uint32 {
	if x != nil {
		return x.xxx_hidden_IntegrationTime
	}
	return 0
}

func (x *SamplingFrequencyParameters) GetClockSpeed() SamplingFrequencyParameters_ClockSpeed {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_ClockSpeed
		}
	}
	return SamplingFrequencyParameters_CLOCK_128MHz
}

func (x *SamplingFrequencyParameters) SetClockDivider(v uint32) {
	x.xxx_hidden_ClockDivider = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SamplingFrequencyParameters) SetIntegrationTime(v uint32) {
	x.xxx_hidden_IntegrationTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SamplingFrequencyParameters) SetClockSpeed(v SamplingFrequencyParameters_ClockSpeed) {
	x.xxx_hidden_ClockSpeed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SamplingFrequencyParameters) HasClockDivider() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SamplingFrequencyParameters) HasIntegrationTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SamplingFrequencyParameters) HasClockSpeed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SamplingFrequencyParameters) ClearClockDivider() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ClockDivider = 0
}

func (x *SamplingFrequencyParameters) ClearIntegrationTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IntegrationTime = 0
}

func (x *SamplingFrequencyParameters) ClearClockSpeed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ClockSpeed = SamplingFrequencyParameters_CLOCK_128MHz
}

type SamplingFrequencyParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Clock divider.
	//
	// Values over 31 cannot be set.
	ClockDivider *uint32
	// The time spent sampling a data point, in microseconds.
	//
	// Must be between 30 and 1023 (inclusive).
	//
	// Note that setting the integration_time to less than 50 will force the sinc_decimation value
	// to 32.
	IntegrationTime *uint32
	// The speed of the high-speed clock.
	ClockSpeed *SamplingFrequencyParameters_ClockSpeed
}

func (b0 SamplingFrequencyParameters_builder) Build() *SamplingFrequencyParameters {
	m0 := &SamplingFrequencyParameters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ClockDivider != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ClockDivider = *b.ClockDivider
	}
	if b.IntegrationTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_IntegrationTime = *b.IntegrationTime
	}
	if b.ClockSpeed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ClockSpeed = *b.ClockSpeed
	}
	return m0
}

// Describes the MinION device settings.
//
// Both unset structures and *_KEEP values in enums indicate "no change". When changing settings,
// these are the default values.
type MinionDeviceSettings struct {
	state                                   protoimpl.MessageState                        `protogen:"opaque.v1"`
	xxx_hidden_BiasVoltage                  *wrapperspb.Int32Value                        `protobuf:"bytes,1,opt,name=bias_voltage,json=biasVoltage"`
	xxx_hidden_SamplingFrequency            *wrapperspb.UInt32Value                       `protobuf:"bytes,2,opt,name=sampling_frequency,json=samplingFrequency"`
	xxx_hidden_ChannelConfig                map[uint32]MinionDeviceSettings_ChannelConfig `protobuf:"bytes,3,rep,name=channel_config,json=channelConfig" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=minknow_api.minion_device.MinionDeviceSettings_ChannelConfig"`
	xxx_hidden_EnableTemperatureControl     *wrapperspb.BoolValue                         `protobuf:"bytes,4,opt,name=enable_temperature_control,json=enableTemperatureControl"`
	xxx_hidden_TemperatureTarget            *TemperatureRange                             `protobuf:"bytes,5,opt,name=temperature_target,json=temperatureTarget"`
	xxx_hidden_IntCapacitor                 MinionDeviceSettings_IntegrationCapacitor     `protobuf:"varint,6,opt,name=int_capacitor,json=intCapacitor,enum=minknow_api.minion_device.MinionDeviceSettings_IntegrationCapacitor"`
	xxx_hidden_TestCurrent                  *wrapperspb.UInt32Value                       `protobuf:"bytes,7,opt,name=test_current,json=testCurrent"`
	xxx_hidden_UnblockVoltage               *wrapperspb.Int32Value                        `protobuf:"bytes,8,opt,name=unblock_voltage,json=unblockVoltage"`
	xxx_hidden_OvercurrentLimit             *wrapperspb.BoolValue                         `protobuf:"bytes,10,opt,name=overcurrent_limit,json=overcurrentLimit"`
	xxx_hidden_SamplesToReset               *wrapperspb.UInt32Value                       `protobuf:"bytes,11,opt,name=samples_to_reset,json=samplesToReset"`
	xxx_hidden_ThGain                       MinionDeviceSettings_Gain                     `protobuf:"varint,12,opt,name=th_gain,json=thGain,enum=minknow_api.minion_device.MinionDeviceSettings_Gain"`
	xxx_hidden_SincDelay                    *wrapperspb.UInt32Value                       `protobuf:"bytes,13,opt,name=sinc_delay,json=sincDelay"`
	xxx_hidden_ThSampleTime                 *wrapperspb.FloatValue                        `protobuf:"bytes,14,opt,name=th_sample_time,json=thSampleTime"`
	xxx_hidden_IntResetTime                 *wrapperspb.FloatValue                        `protobuf:"bytes,15,opt,name=int_reset_time,json=intResetTime"`
	xxx_hidden_SincDecimation               MinionDeviceSettings_Decimation               `protobuf:"varint,16,opt,name=sinc_decimation,json=sincDecimation,enum=minknow_api.minion_device.MinionDeviceSettings_Decimation"`
	xxx_hidden_LowPassFilter                MinionDeviceSettings_LowPassFilter            `protobuf:"varint,17,opt,name=low_pass_filter,json=lowPassFilter,enum=minknow_api.minion_device.MinionDeviceSettings_LowPassFilter"`
	xxx_hidden_NonOverlapClock              MinionDeviceSettings_NonOverlapClock          `protobuf:"varint,18,opt,name=non_overlap_clock,json=nonOverlapClock,enum=minknow_api.minion_device.MinionDeviceSettings_NonOverlapClock"`
	xxx_hidden_BiasCurrent                  *wrapperspb.UInt32Value                       `protobuf:"bytes,19,opt,name=bias_current,json=biasCurrent"`
	xxx_hidden_CompensationCapacitor        *wrapperspb.UInt32Value                       `protobuf:"bytes,20,opt,name=compensation_capacitor,json=compensationCapacitor"`
	xxx_hidden_SamplingFrequencyParams      *SamplingFrequencyParameters                  `protobuf:"bytes,21,opt,name=sampling_frequency_params,json=samplingFrequencyParams"`
	xxx_hidden_EnableAsicPower              *wrapperspb.BoolValue                         `protobuf:"bytes,22,opt,name=enable_asic_power,json=enableAsicPower"`
	xxx_hidden_FanSpeed                     MinionDeviceSettings_FanSpeed                 `protobuf:"varint,23,opt,name=fan_speed,json=fanSpeed,enum=minknow_api.minion_device.MinionDeviceSettings_FanSpeed"`
	xxx_hidden_AllowFullFanStop             *wrapperspb.BoolValue                         `protobuf:"bytes,24,opt,name=allow_full_fan_stop,json=allowFullFanStop"`
	xxx_hidden_EnableSoftTemperatureControl *wrapperspb.BoolValue                         `protobuf:"bytes,25,opt,name=enable_soft_temperature_control,json=enableSoftTemperatureControl"`
	xxx_hidden_EnableBiasVoltageLookup      *wrapperspb.BoolValue                         `protobuf:"bytes,26,opt,name=enable_bias_voltage_lookup,json=enableBiasVoltageLookup"`
	xxx_hidden_BiasVoltageLookupTable       []int32                                       `protobuf:"varint,27,rep,packed,name=bias_voltage_lookup_table,json=biasVoltageLookupTable"`
	xxx_hidden_SamplesPerLut                *wrapperspb.UInt32Value                       `protobuf:"bytes,28,opt,name=samples_per_lut,json=samplesPerLut"`
	XXX_raceDetectHookData                  protoimpl.RaceDetectHookData
	XXX_presence                            [1]uint32
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *MinionDeviceSettings) Reset() {
	*x = MinionDeviceSettings{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinionDeviceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionDeviceSettings) ProtoMessage() {}

func (x *MinionDeviceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MinionDeviceSettings) GetBiasVoltage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_BiasVoltage
	}
	return nil
}

func (x *MinionDeviceSettings) GetSamplingFrequency() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_SamplingFrequency
	}
	return nil
}

func (x *MinionDeviceSettings) GetChannelConfig() map[uint32]MinionDeviceSettings_ChannelConfig {
	if x != nil {
		return x.xxx_hidden_ChannelConfig
	}
	return nil
}

func (x *MinionDeviceSettings) GetEnableTemperatureControl() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_EnableTemperatureControl
	}
	return nil
}

func (x *MinionDeviceSettings) GetTemperatureTarget() *TemperatureRange {
	if x != nil {
		return x.xxx_hidden_TemperatureTarget
	}
	return nil
}

func (x *MinionDeviceSettings) GetIntCapacitor() MinionDeviceSettings_IntegrationCapacitor {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_IntCapacitor
		}
	}
	return MinionDeviceSettings_INTCAP_KEEP
}

func (x *MinionDeviceSettings) GetTestCurrent() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_TestCurrent
	}
	return nil
}

func (x *MinionDeviceSettings) GetUnblockVoltage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_UnblockVoltage
	}
	return nil
}

func (x *MinionDeviceSettings) GetOvercurrentLimit() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_OvercurrentLimit
	}
	return nil
}

func (x *MinionDeviceSettings) GetSamplesToReset() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_SamplesToReset
	}
	return nil
}

func (x *MinionDeviceSettings) GetThGain() MinionDeviceSettings_Gain {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 10) {
			return x.xxx_hidden_ThGain
		}
	}
	return MinionDeviceSettings_GAIN_KEEP
}

func (x *MinionDeviceSettings) GetSincDelay() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_SincDelay
	}
	return nil
}

func (x *MinionDeviceSettings) GetThSampleTime() *wrapperspb.FloatValue {
	if x != nil {
		return x.xxx_hidden_ThSampleTime
	}
	return nil
}

func (x *MinionDeviceSettings) GetIntResetTime() *wrapperspb.FloatValue {
	if x != nil {
		return x.xxx_hidden_IntResetTime
	}
	return nil
}

func (x *MinionDeviceSettings) GetSincDecimation() MinionDeviceSettings_Decimation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 14) {
			return x.xxx_hidden_SincDecimation
		}
	}
	return MinionDeviceSettings_DECIMATION_KEEP
}

func (x *MinionDeviceSettings) GetLowPassFilter() MinionDeviceSettings_LowPassFilter {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 15) {
			return x.xxx_hidden_LowPassFilter
		}
	}
	return MinionDeviceSettings_LPF_KEEP
}

func (x *MinionDeviceSettings) GetNonOverlapClock() MinionDeviceSettings_NonOverlapClock {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 16) {
			return x.xxx_hidden_NonOverlapClock
		}
	}
	return MinionDeviceSettings_NOC_KEEP
}

func (x *MinionDeviceSettings) GetBiasCurrent() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_BiasCurrent
	}
	return nil
}

func (x *MinionDeviceSettings) GetCompensationCapacitor() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_CompensationCapacitor
	}
	return nil
}

func (x *MinionDeviceSettings) GetSamplingFrequencyParams() *SamplingFrequencyParameters {
	if x != nil {
		return x.xxx_hidden_SamplingFrequencyParams
	}
	return nil
}

func (x *MinionDeviceSettings) GetEnableAsicPower() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_EnableAsicPower
	}
	return nil
}

func (x *MinionDeviceSettings) GetFanSpeed() MinionDeviceSettings_FanSpeed {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 21) {
			return x.xxx_hidden_FanSpeed
		}
	}
	return MinionDeviceSettings_FANSPEED_KEEP
}

func (x *MinionDeviceSettings) GetAllowFullFanStop() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_AllowFullFanStop
	}
	return nil
}

func (x *MinionDeviceSettings) GetEnableSoftTemperatureControl() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_EnableSoftTemperatureControl
	}
	return nil
}

func (x *MinionDeviceSettings) GetEnableBiasVoltageLookup() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_EnableBiasVoltageLookup
	}
	return nil
}

func (x *MinionDeviceSettings) GetBiasVoltageLookupTable() []int32 {
	if x != nil {
		return x.xxx_hidden_BiasVoltageLookupTable
	}
	return nil
}

func (x *MinionDeviceSettings) GetSamplesPerLut() *wrapperspb.UInt32Value {
	if x != nil {
		return x.xxx_hidden_SamplesPerLut
	}
	return nil
}

func (x *MinionDeviceSettings) SetBiasVoltage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_BiasVoltage = v
}

func (x *MinionDeviceSettings) SetSamplingFrequency(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_SamplingFrequency = v
}

func (x *MinionDeviceSettings) SetChannelConfig(v map[uint32]MinionDeviceSettings_ChannelConfig) {
	x.xxx_hidden_ChannelConfig = v
}

func (x *MinionDeviceSettings) SetEnableTemperatureControl(v *wrapperspb.BoolValue) {
	x.xxx_hidden_EnableTemperatureControl = v
}

func (x *MinionDeviceSettings) SetTemperatureTarget(v *TemperatureRange) {
	x.xxx_hidden_TemperatureTarget = v
}

func (x *MinionDeviceSettings) SetIntCapacitor(v MinionDeviceSettings_IntegrationCapacitor) {
	x.xxx_hidden_IntCapacitor = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 27)
}

func (x *MinionDeviceSettings) SetTestCurrent(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_TestCurrent = v
}

func (x *MinionDeviceSettings) SetUnblockVoltage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_UnblockVoltage = v
}

func (x *MinionDeviceSettings) SetOvercurrentLimit(v *wrapperspb.BoolValue) {
	x.xxx_hidden_OvercurrentLimit = v
}

func (x *MinionDeviceSettings) SetSamplesToReset(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_SamplesToReset = v
}

func (x *MinionDeviceSettings) SetThGain(v MinionDeviceSettings_Gain) {
	x.xxx_hidden_ThGain = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 27)
}

func (x *MinionDeviceSettings) SetSincDelay(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_SincDelay = v
}

func (x *MinionDeviceSettings) SetThSampleTime(v *wrapperspb.FloatValue) {
	x.xxx_hidden_ThSampleTime = v
}

func (x *MinionDeviceSettings) SetIntResetTime(v *wrapperspb.FloatValue) {
	x.xxx_hidden_IntResetTime = v
}

func (x *MinionDeviceSettings) SetSincDecimation(v MinionDeviceSettings_Decimation) {
	x.xxx_hidden_SincDecimation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 27)
}

func (x *MinionDeviceSettings) SetLowPassFilter(v MinionDeviceSettings_LowPassFilter) {
	x.xxx_hidden_LowPassFilter = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 27)
}

func (x *MinionDeviceSettings) SetNonOverlapClock(v MinionDeviceSettings_NonOverlapClock) {
	x.xxx_hidden_NonOverlapClock = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 27)
}

func (x *MinionDeviceSettings) SetBiasCurrent(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_BiasCurrent = v
}

func (x *MinionDeviceSettings) SetCompensationCapacitor(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_CompensationCapacitor = v
}

func (x *MinionDeviceSettings) SetSamplingFrequencyParams(v *SamplingFrequencyParameters) {
	x.xxx_hidden_SamplingFrequencyParams = v
}

func (x *MinionDeviceSettings) SetEnableAsicPower(v *wrapperspb.BoolValue) {
	x.xxx_hidden_EnableAsicPower = v
}

func (x *MinionDeviceSettings) SetFanSpeed(v MinionDeviceSettings_FanSpeed) {
	x.xxx_hidden_FanSpeed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 27)
}

func (x *MinionDeviceSettings) SetAllowFullFanStop(v *wrapperspb.BoolValue) {
	x.xxx_hidden_AllowFullFanStop = v
}

func (x *MinionDeviceSettings) SetEnableSoftTemperatureControl(v *wrapperspb.BoolValue) {
	x.xxx_hidden_EnableSoftTemperatureControl = v
}

func (x *MinionDeviceSettings) SetEnableBiasVoltageLookup(v *wrapperspb.BoolValue) {
	x.xxx_hidden_EnableBiasVoltageLookup = v
}

func (x *MinionDeviceSettings) SetBiasVoltageLookupTable(v []int32) {
	x.xxx_hidden_BiasVoltageLookupTable = v
}

func (x *MinionDeviceSettings) SetSamplesPerLut(v *wrapperspb.UInt32Value) {
	x.xxx_hidden_SamplesPerLut = v
}

func (x *MinionDeviceSettings) HasBiasVoltage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BiasVoltage != nil
}

func (x *MinionDeviceSettings) HasSamplingFrequency() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SamplingFrequency != nil
}

func (x *MinionDeviceSettings) HasEnableTemperatureControl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EnableTemperatureControl != nil
}

func (x *MinionDeviceSettings) HasTemperatureTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TemperatureTarget != nil
}

func (x *MinionDeviceSettings) HasIntCapacitor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *MinionDeviceSettings) HasTestCurrent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TestCurrent != nil
}

func (x *MinionDeviceSettings) HasUnblockVoltage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UnblockVoltage != nil
}

func (x *MinionDeviceSettings) HasOvercurrentLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OvercurrentLimit != nil
}

func (x *MinionDeviceSettings) HasSamplesToReset() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SamplesToReset != nil
}

func (x *MinionDeviceSettings) HasThGain() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *MinionDeviceSettings) HasSincDelay() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SincDelay != nil
}

func (x *MinionDeviceSettings) HasThSampleTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ThSampleTime != nil
}

func (x *MinionDeviceSettings) HasIntResetTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_IntResetTime != nil
}

func (x *MinionDeviceSettings) HasSincDecimation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *MinionDeviceSettings) HasLowPassFilter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *MinionDeviceSettings) HasNonOverlapClock() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *MinionDeviceSettings) HasBiasCurrent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BiasCurrent != nil
}

func (x *MinionDeviceSettings) HasCompensationCapacitor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CompensationCapacitor != nil
}

func (x *MinionDeviceSettings) HasSamplingFrequencyParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SamplingFrequencyParams != nil
}

func (x *MinionDeviceSettings) HasEnableAsicPower() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EnableAsicPower != nil
}

func (x *MinionDeviceSettings) HasFanSpeed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *MinionDeviceSettings) HasAllowFullFanStop() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AllowFullFanStop != nil
}

func (x *MinionDeviceSettings) HasEnableSoftTemperatureControl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EnableSoftTemperatureControl != nil
}

func (x *MinionDeviceSettings) HasEnableBiasVoltageLookup() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EnableBiasVoltageLookup != nil
}

func (x *MinionDeviceSettings) HasSamplesPerLut() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SamplesPerLut != nil
}

func (x *MinionDeviceSettings) ClearBiasVoltage() {
	x.xxx_hidden_BiasVoltage = nil
}

func (x *MinionDeviceSettings) ClearSamplingFrequency() {
	x.xxx_hidden_SamplingFrequency = nil
}

func (x *MinionDeviceSettings) ClearEnableTemperatureControl() {
	x.xxx_hidden_EnableTemperatureControl = nil
}

func (x *MinionDeviceSettings) ClearTemperatureTarget() {
	x.xxx_hidden_TemperatureTarget = nil
}

func (x *MinionDeviceSettings) ClearIntCapacitor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_IntCapacitor = MinionDeviceSettings_INTCAP_KEEP
}

func (x *MinionDeviceSettings) ClearTestCurrent() {
	x.xxx_hidden_TestCurrent = nil
}

func (x *MinionDeviceSettings) ClearUnblockVoltage() {
	x.xxx_hidden_UnblockVoltage = nil
}

func (x *MinionDeviceSettings) ClearOvercurrentLimit() {
	x.xxx_hidden_OvercurrentLimit = nil
}

func (x *MinionDeviceSettings) ClearSamplesToReset() {
	x.xxx_hidden_SamplesToReset = nil
}

func (x *MinionDeviceSettings) ClearThGain() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_ThGain = MinionDeviceSettings_GAIN_KEEP
}

func (x *MinionDeviceSettings) ClearSincDelay() {
	x.xxx_hidden_SincDelay = nil
}

func (x *MinionDeviceSettings) ClearThSampleTime() {
	x.xxx_hidden_ThSampleTime = nil
}

func (x *MinionDeviceSettings) ClearIntResetTime() {
	x.xxx_hidden_IntResetTime = nil
}

func (x *MinionDeviceSettings) ClearSincDecimation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_SincDecimation = MinionDeviceSettings_DECIMATION_KEEP
}

func (x *MinionDeviceSettings) ClearLowPassFilter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_LowPassFilter = MinionDeviceSettings_LPF_KEEP
}

func (x *MinionDeviceSettings) ClearNonOverlapClock() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_NonOverlapClock = MinionDeviceSettings_NOC_KEEP
}

func (x *MinionDeviceSettings) ClearBiasCurrent() {
	x.xxx_hidden_BiasCurrent = nil
}

func (x *MinionDeviceSettings) ClearCompensationCapacitor() {
	x.xxx_hidden_CompensationCapacitor = nil
}

func (x *MinionDeviceSettings) ClearSamplingFrequencyParams() {
	x.xxx_hidden_SamplingFrequencyParams = nil
}

func (x *MinionDeviceSettings) ClearEnableAsicPower() {
	x.xxx_hidden_EnableAsicPower = nil
}

func (x *MinionDeviceSettings) ClearFanSpeed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_FanSpeed = MinionDeviceSettings_FANSPEED_KEEP
}

func (x *MinionDeviceSettings) ClearAllowFullFanStop() {
	x.xxx_hidden_AllowFullFanStop = nil
}

func (x *MinionDeviceSettings) ClearEnableSoftTemperatureControl() {
	x.xxx_hidden_EnableSoftTemperatureControl = nil
}

func (x *MinionDeviceSettings) ClearEnableBiasVoltageLookup() {
	x.xxx_hidden_EnableBiasVoltageLookup = nil
}

func (x *MinionDeviceSettings) ClearSamplesPerLut() {
	x.xxx_hidden_SamplesPerLut = nil
}

type MinionDeviceSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The voltage potential to be applied across the wells (in millivolts).
	//
	// This voltage drives the process of forcing molecules through the nanopores.
	//
	// The range of possible values is -1275 to 1275 inclusive, in 5mv steps.
	//
	// When setting this value, if the provided value is not a multiple of 5, an error will be
	// returned.
	BiasVoltage *wrapperspb.Int32Value
	// The number of measurements to take each second.
	//
	// This value is derived from the sampling_frequency_params values, and so not all values are
	// possible.
	//
	// When changing the sampling frequency, either this value can be provided, or the values in
	// sampling_frequency_params can be provided (attempting to provide both will cause the RPC to
	// fail with an error). If this value is provided, the nearest admissible value will be used
	// (eg: if 3000Hz is requested, 3012Hz will be applied).
	//
	// This value cannot be changed during acquisition, and changing it will invalidate the current
	// calibration.
	//
	// Note that setting the sampling frequency to over 20000Hz (20KHz) will force the
	// sinc_decimation value to 32.
	SamplingFrequency *wrapperspb.UInt32Value
	// The per-channel configuration.
	//
	// Each channel can be set to one of 16 states, which specifies the set of electrical
	// connections to make. This includes which, if any, of the four wells linked to the channel to
	// use.
	//
	// Note that channel names start at 1. If you pass 0 as a key in this map, it will result in
	// an error.
	//
	// When changing the device settings, any omitted channels (or channels set to
	// CHANNEL_CONFIG_KEEP) will use the default value set in
	// ChangeSettingsRequest.channel_config_default.
	ChannelConfig map[uint32]MinionDeviceSettings_ChannelConfig
	// Whether to enable temperature control.
	//
	// If true, the device will attempt to keep its temperature within the bounds given by
	// “temperature_lower_bound“ and “temperature_upper_bound“. If false, it will not do any
	// temperature control.
	//
	// Default is enabled.
	//
	// It is recommended that this is enabled. If temperature control is disabled, the device may
	// overheat. In this case, it will turn itself off, and must be unplugged and allowed to cool
	// before using again.
	EnableTemperatureControl *wrapperspb.BoolValue
	// The target temperature range for the device.
	//
	// If enable_temperature_control is set to true, the device will attempt to keep its temperature
	// between the min and max values provided here.
	//
	// Default is defined in application config.
	//
	// Note that if soft temperature control is enabled, only the “max“ temperature is used.
	TemperatureTarget *TemperatureRange
	// Integration capacitor value.
	//
	// This affects the sensitivity of the measurement: lower capacitor values give more
	// sensitive measurements (but also more noise). Changing this will invalidate the current
	// calibration.
	//
	// Default is 250.0
	IntCapacitor *MinionDeviceSettings_IntegrationCapacitor
	// The level of current used in the TEST_CURRENT channel configuration.
	//
	// This can be set in the range 0pA to 350pA in 50pA intervals, default is 100.0
	TestCurrent *wrapperspb.UInt32Value
	// The unblock voltage potential (in millivolts).
	//
	// When a channel is set to one of the UNBLOCK configurations, the specified well will have this
	// voltage applied across it, rather than bias_voltage.
	//
	// The range of possible values is -372 to 0 inclusive, in 12mv steps,  default is 0.
	//
	// When setting this value, if the provided value is not a multiple of 12, an error will be
	// returned.
	UnblockVoltage *wrapperspb.Int32Value
	// Whether to enable detection of excessive current.
	//
	// The ADC output of a channel that trips the over-current depends on what track and hold gain
	// has been set to.
	//
	// Default is enabled.
	OvercurrentLimit *wrapperspb.BoolValue
	// The the number of integrator resets per sample.
	//
	// The range of possible values is 0 to 255, default is 1
	SamplesToReset *wrapperspb.UInt32Value
	// Track/Hold gain.
	//
	// Default is 5.0
	ThGain *MinionDeviceSettings_Gain
	// Delay from 2:1 mux switch to sinc filter enable in ADC clocks.
	//
	// The range of possible values is 0 to 15, default is 4.0
	SincDelay *wrapperspb.UInt32Value
	// Track/Hold sample time in microseconds (us).
	//
	// The range of possible values is 0.5us to 7.5us in steps of 0.5us, default is 0.5.
	ThSampleTime *wrapperspb.FloatValue
	// Integrator reset time in microseconds (us).
	//
	// This value forms a part of the integration time specified in the sampling frequency
	// parameters.
	//
	// The range of possible values is 1us to 16us in steps of 0.5us, default is 3.5.
	IntResetTime *wrapperspb.FloatValue
	// Decimation.
	//
	// If the integration time is set to less than 50us (or, equivalently, the sampling frequency is
	// set to greater than 20KHz), this value will be forced to 32.
	//
	// Default is 64.0.
	SincDecimation *MinionDeviceSettings_Decimation
	// Low pass filter that should be applied.
	//
	// Default is 40kHz
	LowPassFilter *MinionDeviceSettings_LowPassFilter
	// Amount of non-overlap for non-overlapping clocks.
	//
	// Default is NOC_1_HS_CLOCK.
	NonOverlapClock *MinionDeviceSettings_NonOverlapClock
	// Bias current.
	//
	// This can be set in the range 0 to 15 in intervals of 5, default is 5.
	BiasCurrent *wrapperspb.UInt32Value
	// Compensation capacitor value.
	//
	// This can be set in the range 0 to 49 in intervals of 7, default is 14.
	CompensationCapacitor *wrapperspb.UInt32Value
	// Sampling frequency parameters.
	//
	// The sampling_frequency value is calculated from these settings.
	//
	// When changing the sampling frequency, either the values here can be provided, or a
	// sampling_frequency can be provided (attempting to provide both will cause the RPC to fail
	// with an error).
	//
	// WARNING: This should not be used in a change_settings call without consulting the hardware
	// documentation for permissible combinations of values. MinKNOW will only do minimal checking
	// of the values given here; if you use invalid combinations of settings, the device will be
	// unable to acquire data, and may even be permanently damaged.
	//
	// This value cannot be changed during acquisition.
	SamplingFrequencyParams *SamplingFrequencyParameters
	// Enable ASIC analogue supply voltage.
	//
	// This must be enabled to heat and acquire data from the ASIC. It can be disabled to save
	// power, but doing so will allow the ASIC to cool down, and it will take time to heat it up
	// again.
	//
	// Default is true.
	EnableAsicPower *wrapperspb.BoolValue
	// The speed of the fan when temperature control is off.
	//
	// If “enable_temperature_control“ is false, this setting will be ignored, as the temperature
	// control routines on the device will control the speed of the fan.
	//
	// Note that this setting does not apply to GridIONs.
	//
	// Default is FANSPEED_MAX.
	FanSpeed *MinionDeviceSettings_FanSpeed
	// Whether to allow the fan to completely stop.
	//
	// Allowing the fan to stop causes issues on some old MinION models.
	//
	// Note that this setting does not apply to GridIONs.
	//
	// Default is false.
	AllowFullFanStop *wrapperspb.BoolValue
	// Enable soft temperature control.
	//
	// "Soft" temperature control is a more intelligent temperature control algorithm. It works on a
	// single target temperature, and dynamically adjusts the fan speed to reach that temperature
	// quickly, and then maintains the target temperature with high precision.
	//
	// If this is disabled, "hard" temperature control is used instead. This is a naive algorithm
	// that simply turns the fan up when dropping below the minimum temperature and turns it down
	// when going above the maximum temperature.
	//
	// If “enable_temperature_control“ is false, this setting is ignored.
	//
	// It is recommended that this is enabled.
	//
	// Default is true.
	EnableSoftTemperatureControl *wrapperspb.BoolValue
	// Use the bias voltage lookup table to set the bias voltage.
	//
	// If this is enabled, the bias voltage will be updated every 1.25ms (ie: at 800Hz) with each
	// entry in the bias voltage lookup table (see “bias_voltage_lookup_table“) in turn, cycling
	// through when the end of the table is reached.
	//
	// This has the effect of producing a bias voltage waveform.
	//
	// When enabling this, it is required to either provide the lookup table entries at the same
	// time, or to have already provided them in a previous call.
	//
	// Default is false.
	EnableBiasVoltageLookup *wrapperspb.BoolValue
	// The bias voltage lookup table.
	//
	// If no entries are provided, the existing lookup table (if any) is preserved.
	//
	// See “enable_bias_voltage_lookup“.
	//
	// Up to 128 values can be provided. The values have the same constraints as “bias_voltage“.
	BiasVoltageLookupTable []int32
	// The number of samples each lookup table entry is valid for.
	//
	// If this value is valid then precise waveform will be enabled for the values in the bias
	// lookup table (must contain at least 2 entries). Set to zero if you want to disable this
	// feature later - if left blank this property will remain unchanged.
	//
	// Must contain a value in the range [2, 64]
	SamplesPerLut *wrapperspb.UInt32Value
}

func (b0 MinionDeviceSettings_builder) Build() *MinionDeviceSettings {
	m0 := &MinionDeviceSettings{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BiasVoltage = b.BiasVoltage
	x.xxx_hidden_SamplingFrequency = b.SamplingFrequency
	x.xxx_hidden_ChannelConfig = b.ChannelConfig
	x.xxx_hidden_EnableTemperatureControl = b.EnableTemperatureControl
	x.xxx_hidden_TemperatureTarget = b.TemperatureTarget
	if b.IntCapacitor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 27)
		x.xxx_hidden_IntCapacitor = *b.IntCapacitor
	}
	x.xxx_hidden_TestCurrent = b.TestCurrent
	x.xxx_hidden_UnblockVoltage = b.UnblockVoltage
	x.xxx_hidden_OvercurrentLimit = b.OvercurrentLimit
	x.xxx_hidden_SamplesToReset = b.SamplesToReset
	if b.ThGain != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 27)
		x.xxx_hidden_ThGain = *b.ThGain
	}
	x.xxx_hidden_SincDelay = b.SincDelay
	x.xxx_hidden_ThSampleTime = b.ThSampleTime
	x.xxx_hidden_IntResetTime = b.IntResetTime
	if b.SincDecimation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 27)
		x.xxx_hidden_SincDecimation = *b.SincDecimation
	}
	if b.LowPassFilter != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 27)
		x.xxx_hidden_LowPassFilter = *b.LowPassFilter
	}
	if b.NonOverlapClock != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 27)
		x.xxx_hidden_NonOverlapClock = *b.NonOverlapClock
	}
	x.xxx_hidden_BiasCurrent = b.BiasCurrent
	x.xxx_hidden_CompensationCapacitor = b.CompensationCapacitor
	x.xxx_hidden_SamplingFrequencyParams = b.SamplingFrequencyParams
	x.xxx_hidden_EnableAsicPower = b.EnableAsicPower
	if b.FanSpeed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 27)
		x.xxx_hidden_FanSpeed = *b.FanSpeed
	}
	x.xxx_hidden_AllowFullFanStop = b.AllowFullFanStop
	x.xxx_hidden_EnableSoftTemperatureControl = b.EnableSoftTemperatureControl
	x.xxx_hidden_EnableBiasVoltageLookup = b.EnableBiasVoltageLookup
	x.xxx_hidden_BiasVoltageLookupTable = b.BiasVoltageLookupTable
	x.xxx_hidden_SamplesPerLut = b.SamplesPerLut
	return m0
}

type ChangeSettingsRequest struct {
	state                           protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Settings             *MinionDeviceSettings              `protobuf:"bytes,1,opt,name=settings"`
	xxx_hidden_ChannelConfigDefault MinionDeviceSettings_ChannelConfig `protobuf:"varint,2,opt,name=channel_config_default,json=channelConfigDefault,enum=minknow_api.minion_device.MinionDeviceSettings_ChannelConfig"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ChangeSettingsRequest) Reset() {
	*x = ChangeSettingsRequest{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsRequest) ProtoMessage() {}

func (x *ChangeSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangeSettingsRequest) GetSettings() *MinionDeviceSettings {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *ChangeSettingsRequest) GetChannelConfigDefault() MinionDeviceSettings_ChannelConfig {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_ChannelConfigDefault
		}
	}
	return MinionDeviceSettings_CHANNEL_CONFIG_KEEP
}

func (x *ChangeSettingsRequest) SetSettings(v *MinionDeviceSettings) {
	x.xxx_hidden_Settings = v
}

func (x *ChangeSettingsRequest) SetChannelConfigDefault(v MinionDeviceSettings_ChannelConfig) {
	x.xxx_hidden_ChannelConfigDefault = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ChangeSettingsRequest) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *ChangeSettingsRequest) HasChannelConfigDefault() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChangeSettingsRequest) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

func (x *ChangeSettingsRequest) ClearChannelConfigDefault() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ChannelConfigDefault = MinionDeviceSettings_CHANNEL_CONFIG_KEEP
}

type ChangeSettingsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// MinION device settings
	Settings *MinionDeviceSettings
	// The default channel configuration.
	//
	// This provides the default configuration to apply to any channels not listed in
	// settings.channel_config.
	ChannelConfigDefault *MinionDeviceSettings_ChannelConfig
}

func (b0 ChangeSettingsRequest_builder) Build() *ChangeSettingsRequest {
	m0 := &ChangeSettingsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Settings = b.Settings
	if b.ChannelConfigDefault != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ChannelConfigDefault = *b.ChannelConfigDefault
	}
	return m0
}

type ChangeSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSettingsResponse) Reset() {
	*x = ChangeSettingsResponse{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsResponse) ProtoMessage() {}

func (x *ChangeSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ChangeSettingsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ChangeSettingsResponse_builder) Build() *ChangeSettingsResponse {
	m0 := &ChangeSettingsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Request for MinionDeviceService.get_settings
type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetSettingsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetSettingsRequest_builder) Build() *GetSettingsRequest {
	m0 := &GetSettingsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Response for MinionDeviceService.get_settings
type GetSettingsResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Settings *MinionDeviceSettings  `protobuf:"bytes,1,opt,name=settings"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSettingsResponse) GetSettings() *MinionDeviceSettings {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *GetSettingsResponse) SetSettings(v *MinionDeviceSettings) {
	x.xxx_hidden_Settings = v
}

func (x *GetSettingsResponse) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *GetSettingsResponse) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

type GetSettingsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// MinION device settings
	Settings *MinionDeviceSettings
}

func (b0 GetSettingsResponse_builder) Build() *GetSettingsResponse {
	m0 := &GetSettingsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Settings = b.Settings
	return m0
}

type GetFanSpeedRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFanSpeedRequest) Reset() {
	*x = GetFanSpeedRequest{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFanSpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFanSpeedRequest) ProtoMessage() {}

func (x *GetFanSpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetFanSpeedRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetFanSpeedRequest_builder) Build() *GetFanSpeedRequest {
	m0 := &GetFanSpeedRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetFanSpeedResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Rpm         uint32                 `protobuf:"varint,1,opt,name=rpm"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetFanSpeedResponse) Reset() {
	*x = GetFanSpeedResponse{}
	mi := &file_minknow_api_minion_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFanSpeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFanSpeedResponse) ProtoMessage() {}

func (x *GetFanSpeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_minion_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetFanSpeedResponse) GetRpm() uint32 {
	if x != nil {
		return x.xxx_hidden_Rpm
	}
	return 0
}

func (x *GetFanSpeedResponse) SetRpm(v uint32) {
	x.xxx_hidden_Rpm = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetFanSpeedResponse) HasRpm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetFanSpeedResponse) ClearRpm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Rpm = 0
}

type GetFanSpeedResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Rpm *uint32
}

func (b0 GetFanSpeedResponse_builder) Build() *GetFanSpeedResponse {
	m0 := &GetFanSpeedResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Rpm != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Rpm = *b.Rpm
	}
	return m0
}

var File_minknow_api_minion_device_proto protoreflect.FileDescriptor

const file_minknow_api_minion_device_proto_rawDesc = "" +
	"\n" +
	"\x1fminknow_api/minion_device.proto\x12\x19minknow_api.minion_device\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dminknow_api/rpc_options.proto\"6\n" +
	"\x10TemperatureRange\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x06 \x01(\x02R\x03max\"\xb4\x02\n" +
	"\x1bSamplingFrequencyParameters\x12#\n" +
	"\rclock_divider\x18\x01 \x01(\rR\fclockDivider\x12)\n" +
	"\x10integration_time\x18\x02 \x01(\rR\x0fintegrationTime\x12b\n" +
	"\vclock_speed\x18\x03 \x01(\x0e2A.minknow_api.minion_device.SamplingFrequencyParameters.ClockSpeedR\n" +
	"clockSpeed\"a\n" +
	"\n" +
	"ClockSpeed\x12\x10\n" +
	"\fCLOCK_128MHz\x10\x00\x12\x0f\n" +
	"\vCLOCK_64MHz\x10\x01\x12\x0f\n" +
	"\vCLOCK_32MHz\x10\x02\x12\x0f\n" +
	"\vCLOCK_16MHz\x10\x03\x12\x0e\n" +
	"\n" +
	"CLOCK_8MHz\x10\x04\"\x9b\x1a\n" +
	"\x14MinionDeviceSettings\x12>\n" +
	"\fbias_voltage\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\vbiasVoltage\x12K\n" +
	"\x12sampling_frequency\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x11samplingFrequency\x12i\n" +
	"\x0echannel_config\x18\x03 \x03(\v2B.minknow_api.minion_device.MinionDeviceSettings.ChannelConfigEntryR\rchannelConfig\x12X\n" +
	"\x1aenable_temperature_control\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x18enableTemperatureControl\x12Z\n" +
	"\x12temperature_target\x18\x05 \x01(\v2+.minknow_api.minion_device.TemperatureRangeR\x11temperatureTarget\x12i\n" +
	"\rint_capacitor\x18\x06 \x01(\x0e2D.minknow_api.minion_device.MinionDeviceSettings.IntegrationCapacitorR\fintCapacitor\x12?\n" +
	"\ftest_current\x18\a \x01(\v2\x1c.google.protobuf.UInt32ValueR\vtestCurrent\x12D\n" +
	"\x0funblock_voltage\x18\b \x01(\v2\x1b.google.protobuf.Int32ValueR\x0eunblockVoltage\x12G\n" +
	"\x11overcurrent_limit\x18\n" +
	" \x01(\v2\x1a.google.protobuf.BoolValueR\x10overcurrentLimit\x12F\n" +
	"\x10samples_to_reset\x18\v \x01(\v2\x1c.google.protobuf.UInt32ValueR\x0esamplesToReset\x12M\n" +
	"\ath_gain\x18\f \x01(\x0e24.minknow_api.minion_device.MinionDeviceSettings.GainR\x06thGain\x12;\n" +
	"\n" +
	"sinc_delay\x18\r \x01(\v2\x1c.google.protobuf.UInt32ValueR\tsincDelay\x12A\n" +
	"\x0eth_sample_time\x18\x0e \x01(\v2\x1b.google.protobuf.FloatValueR\fthSampleTime\x12A\n" +
	"\x0eint_reset_time\x18\x0f \x01(\v2\x1b.google.protobuf.FloatValueR\fintResetTime\x12c\n" +
	"\x0fsinc_decimation\x18\x10 \x01(\x0e2:.minknow_api.minion_device.MinionDeviceSettings.DecimationR\x0esincDecimation\x12e\n" +
	"\x0flow_pass_filter\x18\x11 \x01(\x0e2=.minknow_api.minion_device.MinionDeviceSettings.LowPassFilterR\rlowPassFilter\x12k\n" +
	"\x11non_overlap_clock\x18\x12 \x01(\x0e2?.minknow_api.minion_device.MinionDeviceSettings.NonOverlapClockR\x0fnonOverlapClock\x12?\n" +
	"\fbias_current\x18\x13 \x01(\v2\x1c.google.protobuf.UInt32ValueR\vbiasCurrent\x12S\n" +
	"\x16compensation_capacitor\x18\x14 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x15compensationCapacitor\x12r\n" +
	"\x19sampling_frequency_params\x18\x15 \x01(\v26.minknow_api.minion_device.SamplingFrequencyParametersR\x17samplingFrequencyParams\x12F\n" +
	"\x11enable_asic_power\x18\x16 \x01(\v2\x1a.google.protobuf.BoolValueR\x0fenableAsicPower\x12U\n" +
	"\tfan_speed\x18\x17 \x01(\x0e28.minknow_api.minion_device.MinionDeviceSettings.FanSpeedR\bfanSpeed\x12I\n" +
	"\x13allow_full_fan_stop\x18\x18 \x01(\v2\x1a.google.protobuf.BoolValueR\x10allowFullFanStop\x12a\n" +
	"\x1fenable_soft_temperature_control\x18\x19 \x01(\v2\x1a.google.protobuf.BoolValueR\x1cenableSoftTemperatureControl\x12W\n" +
	"\x1aenable_bias_voltage_lookup\x18\x1a \x01(\v2\x1a.google.protobuf.BoolValueR\x17enableBiasVoltageLookup\x129\n" +
	"\x19bias_voltage_lookup_table\x18\x1b \x03(\x05R\x16biasVoltageLookupTable\x12D\n" +
	"\x0fsamples_per_lut\x18\x1c \x01(\v2\x1c.google.protobuf.UInt32ValueR\rsamplesPerLut\x1a\x7f\n" +
	"\x12ChannelConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12S\n" +
	"\x05value\x18\x02 \x01(\x0e2=.minknow_api.minion_device.MinionDeviceSettings.ChannelConfigR\x05value:\x028\x01\"-\n" +
	"\x04Gain\x12\r\n" +
	"\tGAIN_KEEP\x10\x00\x12\n" +
	"\n" +
	"\x06GAIN_1\x10\x01\x12\n" +
	"\n" +
	"\x06GAIN_5\x10\x02\"G\n" +
	"\n" +
	"Decimation\x12\x13\n" +
	"\x0fDECIMATION_KEEP\x10\x00\x12\x11\n" +
	"\rDECIMATION_32\x10\x01\x12\x11\n" +
	"\rDECIMATION_64\x10\x02\"y\n" +
	"\rLowPassFilter\x12\f\n" +
	"\bLPF_KEEP\x10\x00\x12\f\n" +
	"\bLPF_5kHz\x10\x01\x12\r\n" +
	"\tLPF_10kHz\x10\x02\x12\r\n" +
	"\tLPF_20kHz\x10\x03\x12\r\n" +
	"\tLPF_40kHz\x10\x04\x12\r\n" +
	"\tLPF_80kHz\x10\x05\x12\x10\n" +
	"\fLPF_DISABLED\x10\x06\"G\n" +
	"\x0fNonOverlapClock\x12\f\n" +
	"\bNOC_KEEP\x10\x00\x12\x12\n" +
	"\x0eNOC_1_HS_CLOCK\x10\x01\x12\x12\n" +
	"\x0eNOC_2_HS_CLOCK\x10\x02\"q\n" +
	"\x14IntegrationCapacitor\x12\x0f\n" +
	"\vINTCAP_KEEP\x10\x00\x12\x11\n" +
	"\rINTCAP_62_5fF\x10\x01\x12\x10\n" +
	"\fINTCAP_250fF\x10\x02\x12\x0e\n" +
	"\n" +
	"INTCAP_1pF\x10\x03\x12\x13\n" +
	"\x0fINTCAP_1_1875pF\x10\x04\"f\n" +
	"\bFanSpeed\x12\x11\n" +
	"\rFANSPEED_KEEP\x10\x00\x12\x10\n" +
	"\fFANSPEED_OFF\x10\x01\x12\x10\n" +
	"\fFANSPEED_LOW\x10\x02\x12\x11\n" +
	"\rFANSPEED_HIGH\x10\x03\x12\x10\n" +
	"\fFANSPEED_MAX\x10\x04\"\xbd\x03\n" +
	"\rChannelConfig\x12\x17\n" +
	"\x13CHANNEL_CONFIG_KEEP\x10\x00\x12\x10\n" +
	"\fDISCONNECTED\x10\x01\x12\x17\n" +
	"\x13WELL_1_BIAS_VOLTAGE\x10\x02\x12\x17\n" +
	"\x13WELL_2_BIAS_VOLTAGE\x10\x03\x12\x17\n" +
	"\x13WELL_3_BIAS_VOLTAGE\x10\x04\x12\x17\n" +
	"\x13WELL_4_BIAS_VOLTAGE\x10\x05\x12\x10\n" +
	"\fTEST_CURRENT\x10\x06\x12\x1a\n" +
	"\x16WELL_1_UNBLOCK_VOLTAGE\x10\a\x12\x1a\n" +
	"\x16WELL_2_UNBLOCK_VOLTAGE\x10\b\x12\x1a\n" +
	"\x16WELL_3_UNBLOCK_VOLTAGE\x10\t\x12\x1a\n" +
	"\x16WELL_4_UNBLOCK_VOLTAGE\x10\n" +
	"\x12\x1b\n" +
	"\x17TEST_CURRENT_VIA_WELL_1\x10\v\x12\x1b\n" +
	"\x17TEST_CURRENT_VIA_WELL_2\x10\f\x12\x1b\n" +
	"\x17TEST_CURRENT_VIA_WELL_3\x10\r\x12\x1b\n" +
	"\x17TEST_CURRENT_VIA_WELL_4\x10\x0e\x12\x1b\n" +
	"\x17GROUND_THROUGH_RESISTOR\x10\x0f\x12\n" +
	"\n" +
	"\x06GROUND\x10\x10\"\xdf\x01\n" +
	"\x15ChangeSettingsRequest\x12Q\n" +
	"\bsettings\x18\x01 \x01(\v2/.minknow_api.minion_device.MinionDeviceSettingsB\x04\x90\xb5\x18\x01R\bsettings\x12s\n" +
	"\x16channel_config_default\x18\x02 \x01(\x0e2=.minknow_api.minion_device.MinionDeviceSettings.ChannelConfigR\x14channelConfigDefault\"\x18\n" +
	"\x16ChangeSettingsResponse\"\x14\n" +
	"\x12GetSettingsRequest\"h\n" +
	"\x13GetSettingsResponse\x12Q\n" +
	"\bsettings\x18\x01 \x01(\v2/.minknow_api.minion_device.MinionDeviceSettingsB\x04\x90\xb5\x18\x01R\bsettings\"\x14\n" +
	"\x12GetFanSpeedRequest\"'\n" +
	"\x13GetFanSpeedResponse\x12\x10\n" +
	"\x03rpm\x18\x01 \x01(\rR\x03rpm2\xfb\x02\n" +
	"\x13MinionDeviceService\x12{\n" +
	"\x0fchange_settings\x120.minknow_api.minion_device.ChangeSettingsRequest\x1a1.minknow_api.minion_device.ChangeSettingsResponse\"\x03\x90\x02\x02\x12r\n" +
	"\fget_settings\x12-.minknow_api.minion_device.GetSettingsRequest\x1a..minknow_api.minion_device.GetSettingsResponse\"\x03\x90\x02\x01\x12s\n" +
	"\rget_fan_speed\x12-.minknow_api.minion_device.GetFanSpeedRequest\x1a..minknow_api.minion_device.GetFanSpeedResponse\"\x03\x90\x02\x01Bc\n" +
	"\x1ccom.nanoporetech.minknow_apiZ8github.com/nanoporetech/minknow_api/go/gen/minion_device\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_minion_device_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_minknow_api_minion_device_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_minknow_api_minion_device_proto_goTypes = []any{
	(SamplingFrequencyParameters_ClockSpeed)(0),    // 0: minknow_api.minion_device.SamplingFrequencyParameters.ClockSpeed
	(MinionDeviceSettings_Gain)(0),                 // 1: minknow_api.minion_device.MinionDeviceSettings.Gain
	(MinionDeviceSettings_Decimation)(0),           // 2: minknow_api.minion_device.MinionDeviceSettings.Decimation
	(MinionDeviceSettings_LowPassFilter)(0),        // 3: minknow_api.minion_device.MinionDeviceSettings.LowPassFilter
	(MinionDeviceSettings_NonOverlapClock)(0),      // 4: minknow_api.minion_device.MinionDeviceSettings.NonOverlapClock
	(MinionDeviceSettings_IntegrationCapacitor)(0), // 5: minknow_api.minion_device.MinionDeviceSettings.IntegrationCapacitor
	(MinionDeviceSettings_FanSpeed)(0),             // 6: minknow_api.minion_device.MinionDeviceSettings.FanSpeed
	(MinionDeviceSettings_ChannelConfig)(0),        // 7: minknow_api.minion_device.MinionDeviceSettings.ChannelConfig
	(*TemperatureRange)(nil),                       // 8: minknow_api.minion_device.TemperatureRange
	(*SamplingFrequencyParameters)(nil),            // 9: minknow_api.minion_device.SamplingFrequencyParameters
	(*MinionDeviceSettings)(nil),                   // 10: minknow_api.minion_device.MinionDeviceSettings
	(*ChangeSettingsRequest)(nil),                  // 11: minknow_api.minion_device.ChangeSettingsRequest
	(*ChangeSettingsResponse)(nil),                 // 12: minknow_api.minion_device.ChangeSettingsResponse
	(*GetSettingsRequest)(nil),                     // 13: minknow_api.minion_device.GetSettingsRequest
	(*GetSettingsResponse)(nil),                    // 14: minknow_api.minion_device.GetSettingsResponse
	(*GetFanSpeedRequest)(nil),                     // 15: minknow_api.minion_device.GetFanSpeedRequest
	(*GetFanSpeedResponse)(nil),                    // 16: minknow_api.minion_device.GetFanSpeedResponse
	nil,                                            // 17: minknow_api.minion_device.MinionDeviceSettings.ChannelConfigEntry
	(*wrapperspb.Int32Value)(nil),                  // 18: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil),                 // 19: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),                   // 20: google.protobuf.BoolValue
	(*wrapperspb.FloatValue)(nil),                  // 21: google.protobuf.FloatValue
}
var file_minknow_api_minion_device_proto_depIdxs = []int32{
	0,  // 0: minknow_api.minion_device.SamplingFrequencyParameters.clock_speed:type_name -> minknow_api.minion_device.SamplingFrequencyParameters.ClockSpeed
	18, // 1: minknow_api.minion_device.MinionDeviceSettings.bias_voltage:type_name -> google.protobuf.Int32Value
	19, // 2: minknow_api.minion_device.MinionDeviceSettings.sampling_frequency:type_name -> google.protobuf.UInt32Value
	17, // 3: minknow_api.minion_device.MinionDeviceSettings.channel_config:type_name -> minknow_api.minion_device.MinionDeviceSettings.ChannelConfigEntry
	20, // 4: minknow_api.minion_device.MinionDeviceSettings.enable_temperature_control:type_name -> google.protobuf.BoolValue
	8,  // 5: minknow_api.minion_device.MinionDeviceSettings.temperature_target:type_name -> minknow_api.minion_device.TemperatureRange
	5,  // 6: minknow_api.minion_device.MinionDeviceSettings.int_capacitor:type_name -> minknow_api.minion_device.MinionDeviceSettings.IntegrationCapacitor
	19, // 7: minknow_api.minion_device.MinionDeviceSettings.test_current:type_name -> google.protobuf.UInt32Value
	18, // 8: minknow_api.minion_device.MinionDeviceSettings.unblock_voltage:type_name -> google.protobuf.Int32Value
	20, // 9: minknow_api.minion_device.MinionDeviceSettings.overcurrent_limit:type_name -> google.protobuf.BoolValue
	19, // 10: minknow_api.minion_device.MinionDeviceSettings.samples_to_reset:type_name -> google.protobuf.UInt32Value
	1,  // 11: minknow_api.minion_device.MinionDeviceSettings.th_gain:type_name -> minknow_api.minion_device.MinionDeviceSettings.Gain
	19, // 12: minknow_api.minion_device.MinionDeviceSettings.sinc_delay:type_name -> google.protobuf.UInt32Value
	21, // 13: minknow_api.minion_device.MinionDeviceSettings.th_sample_time:type_name -> google.protobuf.FloatValue
	21, // 14: minknow_api.minion_device.MinionDeviceSettings.int_reset_time:type_name -> google.protobuf.FloatValue
	2,  // 15: minknow_api.minion_device.MinionDeviceSettings.sinc_decimation:type_name -> minknow_api.minion_device.MinionDeviceSettings.Decimation
	3,  // 16: minknow_api.minion_device.MinionDeviceSettings.low_pass_filter:type_name -> minknow_api.minion_device.MinionDeviceSettings.LowPassFilter
	4,  // 17: minknow_api.minion_device.MinionDeviceSettings.non_overlap_clock:type_name -> minknow_api.minion_device.MinionDeviceSettings.NonOverlapClock
	19, // 18: minknow_api.minion_device.MinionDeviceSettings.bias_current:type_name -> google.protobuf.UInt32Value
	19, // 19: minknow_api.minion_device.MinionDeviceSettings.compensation_capacitor:type_name -> google.protobuf.UInt32Value
	9,  // 20: minknow_api.minion_device.MinionDeviceSettings.sampling_frequency_params:type_name -> minknow_api.minion_device.SamplingFrequencyParameters
	20, // 21: minknow_api.minion_device.MinionDeviceSettings.enable_asic_power:type_name -> google.protobuf.BoolValue
	6,  // 22: minknow_api.minion_device.MinionDeviceSettings.fan_speed:type_name -> minknow_api.minion_device.MinionDeviceSettings.FanSpeed
	20, // 23: minknow_api.minion_device.MinionDeviceSettings.allow_full_fan_stop:type_name -> google.protobuf.BoolValue
	20, // 24: minknow_api.minion_device.MinionDeviceSettings.enable_soft_temperature_control:type_name -> google.protobuf.BoolValue
	20, // 25: minknow_api.minion_device.MinionDeviceSettings.enable_bias_voltage_lookup:type_name -> google.protobuf.BoolValue
	19, // 26: minknow_api.minion_device.MinionDeviceSettings.samples_per_lut:type_name -> google.protobuf.UInt32Value
	10, // 27: minknow_api.minion_device.ChangeSettingsRequest.settings:type_name -> minknow_api.minion_device.MinionDeviceSettings
	7,  // 28: minknow_api.minion_device.ChangeSettingsRequest.channel_config_default:type_name -> minknow_api.minion_device.MinionDeviceSettings.ChannelConfig
	10, // 29: minknow_api.minion_device.GetSettingsResponse.settings:type_name -> minknow_api.minion_device.MinionDeviceSettings
	7,  // 30: minknow_api.minion_device.MinionDeviceSettings.ChannelConfigEntry.value:type_name -> minknow_api.minion_device.MinionDeviceSettings.ChannelConfig
	11, // 31: minknow_api.minion_device.MinionDeviceService.change_settings:input_type -> minknow_api.minion_device.ChangeSettingsRequest
	13, // 32: minknow_api.minion_device.MinionDeviceService.get_settings:input_type -> minknow_api.minion_device.GetSettingsRequest
	15, // 33: minknow_api.minion_device.MinionDeviceService.get_fan_speed:input_type -> minknow_api.minion_device.GetFanSpeedRequest
	12, // 34: minknow_api.minion_device.MinionDeviceService.change_settings:output_type -> minknow_api.minion_device.ChangeSettingsResponse
	14, // 35: minknow_api.minion_device.MinionDeviceService.get_settings:output_type -> minknow_api.minion_device.GetSettingsResponse
	16, // 36: minknow_api.minion_device.MinionDeviceService.get_fan_speed:output_type -> minknow_api.minion_device.GetFanSpeedResponse
	34, // [34:37] is the sub-list for method output_type
	31, // [31:34] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_minknow_api_minion_device_proto_init() }
func file_minknow_api_minion_device_proto_init() {
	if File_minknow_api_minion_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_minion_device_proto_rawDesc), len(file_minknow_api_minion_device_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_minion_device_proto_goTypes,
		DependencyIndexes: file_minknow_api_minion_device_proto_depIdxs,
		EnumInfos:         file_minknow_api_minion_device_proto_enumTypes,
		MessageInfos:      file_minknow_api_minion_device_proto_msgTypes,
	}.Build()
	File_minknow_api_minion_device_proto = out.File
	file_minknow_api_minion_device_proto_goTypes = nil
	file_minknow_api_minion_device_proto_depIdxs = nil
}
