// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/notifications.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationContent_Type int32

const (
	// A notification that doesn't require immediate user intervention,
	// or no user intervention at all
	NotificationContent_NOTIFICATION_TYPE_INFO NotificationContent_Type = 0
	// A notification that may require more immediate user intervention,
	// but is not time critical
	NotificationContent_NOTIFICATION_TYPE_WARNING NotificationContent_Type = 1
	// A notification that requires user intervention, and may be
	// time critical
	NotificationContent_NOTIFICATION_TYPE_ERROR NotificationContent_Type = 2
)

// Enum value maps for NotificationContent_Type.
var (
	NotificationContent_Type_name = map[int32]string{
		0: "NOTIFICATION_TYPE_INFO",
		1: "NOTIFICATION_TYPE_WARNING",
		2: "NOTIFICATION_TYPE_ERROR",
	}
	NotificationContent_Type_value = map[string]int32{
		"NOTIFICATION_TYPE_INFO":    0,
		"NOTIFICATION_TYPE_WARNING": 1,
		"NOTIFICATION_TYPE_ERROR":   2,
	}
)

func (x NotificationContent_Type) Enum() *NotificationContent_Type {
	p := new(NotificationContent_Type)
	*p = x
	return p
}

func (x NotificationContent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationContent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_minknow_api_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationContent_Type) Type() protoreflect.EnumType {
	return &file_minknow_api_notifications_proto_enumTypes[0]
}

func (x NotificationContent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NotificationContent struct {
	state                       protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Type             NotificationContent_Type `protobuf:"varint,1,opt,name=type,enum=minknow_api.notifications.NotificationContent_Type"`
	xxx_hidden_NotificationText *string                  `protobuf:"bytes,2,opt,name=notification_text,json=notificationText"`
	xxx_hidden_NotificationCode *string                  `protobuf:"bytes,3,opt,name=notification_code,json=notificationCode"`
	xxx_hidden_ExtraData        map[string]string        `protobuf:"bytes,4,rep,name=extra_data,json=extraData" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *NotificationContent) Reset() {
	*x = NotificationContent{}
	mi := &file_minknow_api_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationContent) ProtoMessage() {}

func (x *NotificationContent) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotificationContent) GetType() NotificationContent_Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return NotificationContent_NOTIFICATION_TYPE_INFO
}

func (x *NotificationContent) GetNotificationText() string {
	if x != nil {
		if x.xxx_hidden_NotificationText != nil {
			return *x.xxx_hidden_NotificationText
		}
		return ""
	}
	return ""
}

func (x *NotificationContent) GetNotificationCode() string {
	if x != nil {
		if x.xxx_hidden_NotificationCode != nil {
			return *x.xxx_hidden_NotificationCode
		}
		return ""
	}
	return ""
}

func (x *NotificationContent) GetExtraData() map[string]string {
	if x != nil {
		return x.xxx_hidden_ExtraData
	}
	return nil
}

func (x *NotificationContent) SetType(v NotificationContent_Type) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *NotificationContent) SetNotificationText(v string) {
	x.xxx_hidden_NotificationText = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *NotificationContent) SetNotificationCode(v string) {
	x.xxx_hidden_NotificationCode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *NotificationContent) SetExtraData(v map[string]string) {
	x.xxx_hidden_ExtraData = v
}

func (x *NotificationContent) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NotificationContent) HasNotificationText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NotificationContent) HasNotificationCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *NotificationContent) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = NotificationContent_NOTIFICATION_TYPE_INFO
}

func (x *NotificationContent) ClearNotificationText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NotificationText = nil
}

func (x *NotificationContent) ClearNotificationCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NotificationCode = nil
}

type NotificationContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type *NotificationContent_Type
	// Text relating to a specific notification
	NotificationText *string
	// A code unique to each notification. This enables the client to handle the
	// text to display, which can then be translated or operated on separately. If
	// an unknown notification_code is sent the client may fall-back to using
	// `notification_text`
	NotificationCode *string
	// Any extra data associated with the notification, as a map from key to data.
	ExtraData map[string]string
}

func (b0 NotificationContent_builder) Build() *NotificationContent {
	m0 := &NotificationContent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.NotificationText != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_NotificationText = b.NotificationText
	}
	if b.NotificationCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_NotificationCode = b.NotificationCode
	}
	x.xxx_hidden_ExtraData = b.ExtraData
	return m0
}

type Notification struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt"`
	xxx_hidden_LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated_at,json=lastUpdatedAt"`
	xxx_hidden_Read          bool                   `protobuf:"varint,4,opt,name=read"`
	xxx_hidden_Content       *NotificationContent   `protobuf:"bytes,5,opt,name=content"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_minknow_api_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Notification) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Notification) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastUpdatedAt
	}
	return nil
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.xxx_hidden_Read
	}
	return false
}

func (x *Notification) GetContent() *NotificationContent {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *Notification) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Notification) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Notification) SetLastUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastUpdatedAt = v
}

func (x *Notification) SetRead(v bool) {
	x.xxx_hidden_Read = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Notification) SetContent(v *NotificationContent) {
	x.xxx_hidden_Content = v
}

func (x *Notification) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Notification) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Notification) HasLastUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastUpdatedAt != nil
}

func (x *Notification) HasRead() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Notification) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *Notification) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Notification) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Notification) ClearLastUpdatedAt() {
	x.xxx_hidden_LastUpdatedAt = nil
}

func (x *Notification) ClearRead() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Read = false
}

func (x *Notification) ClearContent() {
	x.xxx_hidden_Content = nil
}

type Notification_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique auto-generated ID for the message
	Id *string
	// Timestamp for when the notification was created
	CreatedAt *timestamppb.Timestamp
	// Timestamp for when the notification was last updated this will be
	// the same as `created_at` if there has been no update
	LastUpdatedAt *timestamppb.Timestamp
	// Whether the notification has been marked as read or not
	Read *bool
	// Content attached to the notification
	Content *NotificationContent
}

func (b0 Notification_builder) Build() *Notification {
	m0 := &Notification{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_LastUpdatedAt = b.LastUpdatedAt
	if b.Read != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Read = *b.Read
	}
	x.xxx_hidden_Content = b.Content
	return m0
}

type StreamNotificationsRequest struct {
	state                                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IncludeUpdatesForExisting bool                   `protobuf:"varint,1,opt,name=include_updates_for_existing,json=includeUpdatesForExisting"`
	XXX_raceDetectHookData               protoimpl.RaceDetectHookData
	XXX_presence                         [1]uint32
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *StreamNotificationsRequest) Reset() {
	*x = StreamNotificationsRequest{}
	mi := &file_minknow_api_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsRequest) ProtoMessage() {}

func (x *StreamNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamNotificationsRequest) GetIncludeUpdatesForExisting() bool {
	if x != nil {
		return x.xxx_hidden_IncludeUpdatesForExisting
	}
	return false
}

func (x *StreamNotificationsRequest) SetIncludeUpdatesForExisting(v bool) {
	x.xxx_hidden_IncludeUpdatesForExisting = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StreamNotificationsRequest) HasIncludeUpdatesForExisting() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamNotificationsRequest) ClearIncludeUpdatesForExisting() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_IncludeUpdatesForExisting = false
}

type StreamNotificationsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether updates to existing notifications (e.g., marking as read) should be included in the stream.
	// Defaults to false
	IncludeUpdatesForExisting *bool
}

func (b0 StreamNotificationsRequest_builder) Build() *StreamNotificationsRequest {
	m0 := &StreamNotificationsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.IncludeUpdatesForExisting != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_IncludeUpdatesForExisting = *b.IncludeUpdatesForExisting
	}
	return m0
}

type StreamNotificationsResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Notifications *[]*Notification       `protobuf:"bytes,1,rep,name=notifications"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StreamNotificationsResponse) Reset() {
	*x = StreamNotificationsResponse{}
	mi := &file_minknow_api_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsResponse) ProtoMessage() {}

func (x *StreamNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		if x.xxx_hidden_Notifications != nil {
			return *x.xxx_hidden_Notifications
		}
	}
	return nil
}

func (x *StreamNotificationsResponse) SetNotifications(v []*Notification) {
	x.xxx_hidden_Notifications = &v
}

type StreamNotificationsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of notifications. If new notifications are generated they may be streamed as single
	// values in the list.
	// A delay of 1 second is set prior to notifications being sent, to prevent multiple updates
	// potentially spamming the stream in quick succession
	Notifications []*Notification
}

func (b0 StreamNotificationsResponse_builder) Build() *StreamNotificationsResponse {
	m0 := &StreamNotificationsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Notifications = &b.Notifications
	return m0
}

type MarkNotificationsAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ids []string               `protobuf:"bytes,1,rep,name=ids"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationsAsReadRequest) Reset() {
	*x = MarkNotificationsAsReadRequest{}
	mi := &file_minknow_api_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationsAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationsAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationsAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MarkNotificationsAsReadRequest) GetIds() []string {
	if x != nil {
		return x.xxx_hidden_Ids
	}
	return nil
}

func (x *MarkNotificationsAsReadRequest) SetIds(v []string) {
	x.xxx_hidden_Ids = v
}

type MarkNotificationsAsReadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of IDs for the notifications to mark as read. This will set the `read` attribute
	// to `true`. If `read` is already `true` for a specific ID then it is not updated.
	Ids []string
}

func (b0 MarkNotificationsAsReadRequest_builder) Build() *MarkNotificationsAsReadRequest {
	m0 := &MarkNotificationsAsReadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ids = b.Ids
	return m0
}

type MarkNotificationsAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationsAsReadResponse) Reset() {
	*x = MarkNotificationsAsReadResponse{}
	mi := &file_minknow_api_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationsAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationsAsReadResponse) ProtoMessage() {}

func (x *MarkNotificationsAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MarkNotificationsAsReadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MarkNotificationsAsReadResponse_builder) Build() *MarkNotificationsAsReadResponse {
	m0 := &MarkNotificationsAsReadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CreateNotificationRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Content *NotificationContent   `protobuf:"bytes,1,opt,name=content"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_minknow_api_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateNotificationRequest) GetContent() *NotificationContent {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *CreateNotificationRequest) SetContent(v *NotificationContent) {
	x.xxx_hidden_Content = v
}

func (x *CreateNotificationRequest) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *CreateNotificationRequest) ClearContent() {
	x.xxx_hidden_Content = nil
}

type CreateNotificationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Content to set for a new notification
	Content *NotificationContent
}

func (b0 CreateNotificationRequest_builder) Build() *CreateNotificationRequest {
	m0 := &CreateNotificationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Content = b.Content
	return m0
}

type CreateNotificationResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Notification *Notification          `protobuf:"bytes,1,opt,name=notification"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_minknow_api_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.xxx_hidden_Notification
	}
	return nil
}

func (x *CreateNotificationResponse) SetNotification(v *Notification) {
	x.xxx_hidden_Notification = v
}

func (x *CreateNotificationResponse) HasNotification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Notification != nil
}

func (x *CreateNotificationResponse) ClearNotification() {
	x.xxx_hidden_Notification = nil
}

type CreateNotificationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The created notification
	Notification *Notification
}

func (b0 CreateNotificationResponse_builder) Build() *CreateNotificationResponse {
	m0 := &CreateNotificationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Notification = b.Notification
	return m0
}

var File_minknow_api_notifications_proto protoreflect.FileDescriptor

const file_minknow_api_notifications_proto_rawDesc = "" +
	"\n" +
	"\x1fminknow_api/notifications.proto\x12\x19minknow_api.notifications\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x03\n" +
	"\x13NotificationContent\x12G\n" +
	"\x04type\x18\x01 \x01(\x0e23.minknow_api.notifications.NotificationContent.TypeR\x04type\x12+\n" +
	"\x11notification_text\x18\x02 \x01(\tR\x10notificationText\x12+\n" +
	"\x11notification_code\x18\x03 \x01(\tR\x10notificationCode\x12\\\n" +
	"\n" +
	"extra_data\x18\x04 \x03(\v2=.minknow_api.notifications.NotificationContent.ExtraDataEntryR\textraData\x1a<\n" +
	"\x0eExtraDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x04Type\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_INFO\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_WARNING\x10\x01\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_ERROR\x10\x02\"\xfb\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0flast_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12H\n" +
	"\acontent\x18\x05 \x01(\v2..minknow_api.notifications.NotificationContentR\acontent\"]\n" +
	"\x1aStreamNotificationsRequest\x12?\n" +
	"\x1cinclude_updates_for_existing\x18\x01 \x01(\bR\x19includeUpdatesForExisting\"l\n" +
	"\x1bStreamNotificationsResponse\x12M\n" +
	"\rnotifications\x18\x01 \x03(\v2'.minknow_api.notifications.NotificationR\rnotifications\"2\n" +
	"\x1eMarkNotificationsAsReadRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"!\n" +
	"\x1fMarkNotificationsAsReadResponse\"e\n" +
	"\x19CreateNotificationRequest\x12H\n" +
	"\acontent\x18\x01 \x01(\v2..minknow_api.notifications.NotificationContentR\acontent\"i\n" +
	"\x1aCreateNotificationResponse\x12K\n" +
	"\fnotification\x18\x01 \x01(\v2'.minknow_api.notifications.NotificationR\fnotification2\xc1\x03\n" +
	"\x14NotificationsService\x12\x89\x01\n" +
	"\x14stream_notifications\x125.minknow_api.notifications.StreamNotificationsRequest\x1a6.minknow_api.notifications.StreamNotificationsResponse\"\x000\x01\x12\x95\x01\n" +
	"\x1amark_notifications_as_read\x129.minknow_api.notifications.MarkNotificationsAsReadRequest\x1a:.minknow_api.notifications.MarkNotificationsAsReadResponse\"\x00\x12\x84\x01\n" +
	"\x13create_notification\x124.minknow_api.notifications.CreateNotificationRequest\x1a5.minknow_api.notifications.CreateNotificationResponse\"\x00Bc\n" +
	"\x1ccom.nanoporetech.minknow_apiZ8github.com/nanoporetech/minknow_api/go/gen/notifications\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minknow_api_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_minknow_api_notifications_proto_goTypes = []any{
	(NotificationContent_Type)(0),           // 0: minknow_api.notifications.NotificationContent.Type
	(*NotificationContent)(nil),             // 1: minknow_api.notifications.NotificationContent
	(*Notification)(nil),                    // 2: minknow_api.notifications.Notification
	(*StreamNotificationsRequest)(nil),      // 3: minknow_api.notifications.StreamNotificationsRequest
	(*StreamNotificationsResponse)(nil),     // 4: minknow_api.notifications.StreamNotificationsResponse
	(*MarkNotificationsAsReadRequest)(nil),  // 5: minknow_api.notifications.MarkNotificationsAsReadRequest
	(*MarkNotificationsAsReadResponse)(nil), // 6: minknow_api.notifications.MarkNotificationsAsReadResponse
	(*CreateNotificationRequest)(nil),       // 7: minknow_api.notifications.CreateNotificationRequest
	(*CreateNotificationResponse)(nil),      // 8: minknow_api.notifications.CreateNotificationResponse
	nil,                                     // 9: minknow_api.notifications.NotificationContent.ExtraDataEntry
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
}
var file_minknow_api_notifications_proto_depIdxs = []int32{
	0,  // 0: minknow_api.notifications.NotificationContent.type:type_name -> minknow_api.notifications.NotificationContent.Type
	9,  // 1: minknow_api.notifications.NotificationContent.extra_data:type_name -> minknow_api.notifications.NotificationContent.ExtraDataEntry
	10, // 2: minknow_api.notifications.Notification.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: minknow_api.notifications.Notification.last_updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: minknow_api.notifications.Notification.content:type_name -> minknow_api.notifications.NotificationContent
	2,  // 5: minknow_api.notifications.StreamNotificationsResponse.notifications:type_name -> minknow_api.notifications.Notification
	1,  // 6: minknow_api.notifications.CreateNotificationRequest.content:type_name -> minknow_api.notifications.NotificationContent
	2,  // 7: minknow_api.notifications.CreateNotificationResponse.notification:type_name -> minknow_api.notifications.Notification
	3,  // 8: minknow_api.notifications.NotificationsService.stream_notifications:input_type -> minknow_api.notifications.StreamNotificationsRequest
	5,  // 9: minknow_api.notifications.NotificationsService.mark_notifications_as_read:input_type -> minknow_api.notifications.MarkNotificationsAsReadRequest
	7,  // 10: minknow_api.notifications.NotificationsService.create_notification:input_type -> minknow_api.notifications.CreateNotificationRequest
	4,  // 11: minknow_api.notifications.NotificationsService.stream_notifications:output_type -> minknow_api.notifications.StreamNotificationsResponse
	6,  // 12: minknow_api.notifications.NotificationsService.mark_notifications_as_read:output_type -> minknow_api.notifications.MarkNotificationsAsReadResponse
	8,  // 13: minknow_api.notifications.NotificationsService.create_notification:output_type -> minknow_api.notifications.CreateNotificationResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_minknow_api_notifications_proto_init() }
func file_minknow_api_notifications_proto_init() {
	if File_minknow_api_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_notifications_proto_rawDesc), len(file_minknow_api_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_notifications_proto_goTypes,
		DependencyIndexes: file_minknow_api_notifications_proto_depIdxs,
		EnumInfos:         file_minknow_api_notifications_proto_enumTypes,
		MessageInfos:      file_minknow_api_notifications_proto_msgTypes,
	}.Build()
	File_minknow_api_notifications_proto = out.File
	file_minknow_api_notifications_proto_goTypes = nil
	file_minknow_api_notifications_proto_depIdxs = nil
}
