// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: minknow_api/v2/protocols.proto

package protocol

import (
	acquisition "github.com/nanoporetech/minknow_api/go/gen/acquisition"
	protocol "github.com/nanoporetech/minknow_api/go/gen/protocol"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginProtocolsRequest struct {
	state               protoimpl.MessageState                      `protogen:"opaque.v1"`
	xxx_hidden_Requests *[]*BeginProtocolsRequest_IndividualRequest `protobuf:"bytes,1,rep,name=requests"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BeginProtocolsRequest) Reset() {
	*x = BeginProtocolsRequest{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginProtocolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginProtocolsRequest) ProtoMessage() {}

func (x *BeginProtocolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BeginProtocolsRequest) GetRequests() []*BeginProtocolsRequest_IndividualRequest {
	if x != nil {
		if x.xxx_hidden_Requests != nil {
			return *x.xxx_hidden_Requests
		}
	}
	return nil
}

func (x *BeginProtocolsRequest) SetRequests(v []*BeginProtocolsRequest_IndividualRequest) {
	x.xxx_hidden_Requests = &v
}

type BeginProtocolsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Requests []*BeginProtocolsRequest_IndividualRequest
}

func (b0 BeginProtocolsRequest_builder) Build() *BeginProtocolsRequest {
	m0 := &BeginProtocolsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Requests = &b.Requests
	return m0
}

type BeginProtocolsResponse struct {
	state                protoimpl.MessageState                        `protogen:"opaque.v1"`
	xxx_hidden_Responses *[]*BeginProtocolsResponse_IndividualResponse `protobuf:"bytes,1,rep,name=responses"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BeginProtocolsResponse) Reset() {
	*x = BeginProtocolsResponse{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginProtocolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginProtocolsResponse) ProtoMessage() {}

func (x *BeginProtocolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BeginProtocolsResponse) GetResponses() []*BeginProtocolsResponse_IndividualResponse {
	if x != nil {
		if x.xxx_hidden_Responses != nil {
			return *x.xxx_hidden_Responses
		}
	}
	return nil
}

func (x *BeginProtocolsResponse) SetResponses(v []*BeginProtocolsResponse_IndividualResponse) {
	x.xxx_hidden_Responses = &v
}

type BeginProtocolsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Responses []*BeginProtocolsResponse_IndividualResponse
}

func (b0 BeginProtocolsResponse_builder) Build() *BeginProtocolsResponse {
	m0 := &BeginProtocolsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Responses = &b.Responses
	return m0
}

type StartProtocolsRequest struct {
	state               protoimpl.MessageState                      `protogen:"opaque.v1"`
	xxx_hidden_Requests *[]*StartProtocolsRequest_IndividualRequest `protobuf:"bytes,1,rep,name=requests"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartProtocolsRequest) Reset() {
	*x = StartProtocolsRequest{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProtocolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProtocolsRequest) ProtoMessage() {}

func (x *StartProtocolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartProtocolsRequest) GetRequests() []*StartProtocolsRequest_IndividualRequest {
	if x != nil {
		if x.xxx_hidden_Requests != nil {
			return *x.xxx_hidden_Requests
		}
	}
	return nil
}

func (x *StartProtocolsRequest) SetRequests(v []*StartProtocolsRequest_IndividualRequest) {
	x.xxx_hidden_Requests = &v
}

type StartProtocolsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Requests []*StartProtocolsRequest_IndividualRequest
}

func (b0 StartProtocolsRequest_builder) Build() *StartProtocolsRequest {
	m0 := &StartProtocolsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Requests = &b.Requests
	return m0
}

type StartProtocolsResponse struct {
	state                protoimpl.MessageState                        `protogen:"opaque.v1"`
	xxx_hidden_Responses *[]*StartProtocolsResponse_IndividualResponse `protobuf:"bytes,1,rep,name=responses"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartProtocolsResponse) Reset() {
	*x = StartProtocolsResponse{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProtocolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProtocolsResponse) ProtoMessage() {}

func (x *StartProtocolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartProtocolsResponse) GetResponses() []*StartProtocolsResponse_IndividualResponse {
	if x != nil {
		if x.xxx_hidden_Responses != nil {
			return *x.xxx_hidden_Responses
		}
	}
	return nil
}

func (x *StartProtocolsResponse) SetResponses(v []*StartProtocolsResponse_IndividualResponse) {
	x.xxx_hidden_Responses = &v
}

type StartProtocolsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Responses []*StartProtocolsResponse_IndividualResponse
}

func (b0 StartProtocolsResponse_builder) Build() *StartProtocolsResponse {
	m0 := &StartProtocolsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Responses = &b.Responses
	return m0
}

type StopProtocolsRequest struct {
	state               protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Requests *[]*protocol.StopProtocolRequest `protobuf:"bytes,1,rep,name=requests"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StopProtocolsRequest) Reset() {
	*x = StopProtocolsRequest{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProtocolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProtocolsRequest) ProtoMessage() {}

func (x *StopProtocolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopProtocolsRequest) GetRequests() []*protocol.StopProtocolRequest {
	if x != nil {
		if x.xxx_hidden_Requests != nil {
			return *x.xxx_hidden_Requests
		}
	}
	return nil
}

func (x *StopProtocolsRequest) SetRequests(v []*protocol.StopProtocolRequest) {
	x.xxx_hidden_Requests = &v
}

type StopProtocolsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Requests []*protocol.StopProtocolRequest
}

func (b0 StopProtocolsRequest_builder) Build() *StopProtocolsRequest {
	m0 := &StopProtocolsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Requests = &b.Requests
	return m0
}

type StopProtocolsResponse struct {
	state                protoimpl.MessageState                       `protogen:"opaque.v1"`
	xxx_hidden_Responses *[]*StopProtocolsResponse_IndividualResponse `protobuf:"bytes,1,rep,name=responses"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StopProtocolsResponse) Reset() {
	*x = StopProtocolsResponse{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProtocolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProtocolsResponse) ProtoMessage() {}

func (x *StopProtocolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopProtocolsResponse) GetResponses() []*StopProtocolsResponse_IndividualResponse {
	if x != nil {
		if x.xxx_hidden_Responses != nil {
			return *x.xxx_hidden_Responses
		}
	}
	return nil
}

func (x *StopProtocolsResponse) SetResponses(v []*StopProtocolsResponse_IndividualResponse) {
	x.xxx_hidden_Responses = &v
}

type StopProtocolsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Responses []*StopProtocolsResponse_IndividualResponse
}

func (b0 StopProtocolsResponse_builder) Build() *StopProtocolsResponse {
	m0 := &StopProtocolsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Responses = &b.Responses
	return m0
}

// Limit the filtering to time-related filters only.
type GroupFilteringInfo struct {
	state                          protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_ExperimentStartTime *protocol.FilteringInfo_TimeFilter    `protobuf:"bytes,1,opt,name=experiment_start_time,json=experimentStartTime"`
	xxx_hidden_OrderDirection      protocol.FilteringInfo_OrderDirection `protobuf:"varint,2,opt,name=order_direction,json=orderDirection,enum=minknow_api.protocol.FilteringInfo_OrderDirection"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GroupFilteringInfo) Reset() {
	*x = GroupFilteringInfo{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupFilteringInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFilteringInfo) ProtoMessage() {}

func (x *GroupFilteringInfo) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupFilteringInfo) GetExperimentStartTime() *protocol.FilteringInfo_TimeFilter {
	if x != nil {
		return x.xxx_hidden_ExperimentStartTime
	}
	return nil
}

func (x *GroupFilteringInfo) GetOrderDirection() protocol.FilteringInfo_OrderDirection {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_OrderDirection
		}
	}
	return protocol.FilteringInfo_OrderDirection(0)
}

func (x *GroupFilteringInfo) SetExperimentStartTime(v *protocol.FilteringInfo_TimeFilter) {
	x.xxx_hidden_ExperimentStartTime = v
}

func (x *GroupFilteringInfo) SetOrderDirection(v protocol.FilteringInfo_OrderDirection) {
	x.xxx_hidden_OrderDirection = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GroupFilteringInfo) HasExperimentStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExperimentStartTime != nil
}

func (x *GroupFilteringInfo) HasOrderDirection() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GroupFilteringInfo) ClearExperimentStartTime() {
	x.xxx_hidden_ExperimentStartTime = nil
}

func (x *GroupFilteringInfo) ClearOrderDirection() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OrderDirection = protocol.FilteringInfo_DESCENDING
}

type GroupFilteringInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ExperimentStartTime *protocol.FilteringInfo_TimeFilter
	// Default of DESCENDING
	OrderDirection *protocol.FilteringInfo_OrderDirection
}

func (b0 GroupFilteringInfo_builder) Build() *GroupFilteringInfo {
	m0 := &GroupFilteringInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ExperimentStartTime = b.ExperimentStartTime
	if b.OrderDirection != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_OrderDirection = *b.OrderDirection
	}
	return m0
}

type ListGroupIdsRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FilterInfo *GroupFilteringInfo    `protobuf:"bytes,1,opt,name=filter_info,json=filterInfo"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListGroupIdsRequest) Reset() {
	*x = ListGroupIdsRequest{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupIdsRequest) ProtoMessage() {}

func (x *ListGroupIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListGroupIdsRequest) GetFilterInfo() *GroupFilteringInfo {
	if x != nil {
		return x.xxx_hidden_FilterInfo
	}
	return nil
}

func (x *ListGroupIdsRequest) SetFilterInfo(v *GroupFilteringInfo) {
	x.xxx_hidden_FilterInfo = v
}

func (x *ListGroupIdsRequest) HasFilterInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FilterInfo != nil
}

func (x *ListGroupIdsRequest) ClearFilterInfo() {
	x.xxx_hidden_FilterInfo = nil
}

type ListGroupIdsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FilterInfo *GroupFilteringInfo
}

func (b0 ListGroupIdsRequest_builder) Build() *ListGroupIdsRequest {
	m0 := &ListGroupIdsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FilterInfo = b.FilterInfo
	return m0
}

type BeginProtocolsRequest_IndividualRequest struct {
	state                           protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_FlowCellPositionName *string                        `protobuf:"bytes,1,opt,name=flow_cell_position_name,json=flowCellPositionName"`
	xxx_hidden_Settings             *protocol.BeginProtocolRequest `protobuf:"bytes,2,opt,name=settings"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *BeginProtocolsRequest_IndividualRequest) Reset() {
	*x = BeginProtocolsRequest_IndividualRequest{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginProtocolsRequest_IndividualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginProtocolsRequest_IndividualRequest) ProtoMessage() {}

func (x *BeginProtocolsRequest_IndividualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BeginProtocolsRequest_IndividualRequest) GetFlowCellPositionName() string {
	if x != nil {
		if x.xxx_hidden_FlowCellPositionName != nil {
			return *x.xxx_hidden_FlowCellPositionName
		}
		return ""
	}
	return ""
}

func (x *BeginProtocolsRequest_IndividualRequest) GetSettings() *protocol.BeginProtocolRequest {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *BeginProtocolsRequest_IndividualRequest) SetFlowCellPositionName(v string) {
	x.xxx_hidden_FlowCellPositionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *BeginProtocolsRequest_IndividualRequest) SetSettings(v *protocol.BeginProtocolRequest) {
	x.xxx_hidden_Settings = v
}

func (x *BeginProtocolsRequest_IndividualRequest) HasFlowCellPositionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BeginProtocolsRequest_IndividualRequest) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *BeginProtocolsRequest_IndividualRequest) ClearFlowCellPositionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FlowCellPositionName = nil
}

func (x *BeginProtocolsRequest_IndividualRequest) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

type BeginProtocolsRequest_IndividualRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The position on which to start this protocol.
	FlowCellPositionName *string
	Settings             *protocol.BeginProtocolRequest
}

func (b0 BeginProtocolsRequest_IndividualRequest_builder) Build() *BeginProtocolsRequest_IndividualRequest {
	m0 := &BeginProtocolsRequest_IndividualRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FlowCellPositionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FlowCellPositionName = b.FlowCellPositionName
	}
	x.xxx_hidden_Settings = b.Settings
	return m0
}

// Represents the response from the proxied call to 'begin_protocol'
// on a specific flow cell.
type BeginProtocolsResponse_IndividualResponse struct {
	state                           protoimpl.MessageState                              `protogen:"opaque.v1"`
	xxx_hidden_FlowCellPositionName *string                                             `protobuf:"bytes,1,opt,name=flow_cell_position_name,json=flowCellPositionName"`
	xxx_hidden_Payload              isBeginProtocolsResponse_IndividualResponse_Payload `protobuf_oneof:"payload"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *BeginProtocolsResponse_IndividualResponse) Reset() {
	*x = BeginProtocolsResponse_IndividualResponse{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginProtocolsResponse_IndividualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginProtocolsResponse_IndividualResponse) ProtoMessage() {}

func (x *BeginProtocolsResponse_IndividualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BeginProtocolsResponse_IndividualResponse) GetFlowCellPositionName() string {
	if x != nil {
		if x.xxx_hidden_FlowCellPositionName != nil {
			return *x.xxx_hidden_FlowCellPositionName
		}
		return ""
	}
	return ""
}

func (x *BeginProtocolsResponse_IndividualResponse) GetResponse() *protocol.BeginProtocolResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*beginProtocolsResponse_IndividualResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *BeginProtocolsResponse_IndividualResponse) GetStatus() *status.Status {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*beginProtocolsResponse_IndividualResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *BeginProtocolsResponse_IndividualResponse) SetFlowCellPositionName(v string) {
	x.xxx_hidden_FlowCellPositionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *BeginProtocolsResponse_IndividualResponse) SetResponse(v *protocol.BeginProtocolResponse) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &beginProtocolsResponse_IndividualResponse_Response{v}
}

func (x *BeginProtocolsResponse_IndividualResponse) SetStatus(v *status.Status) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &beginProtocolsResponse_IndividualResponse_Status{v}
}

func (x *BeginProtocolsResponse_IndividualResponse) HasFlowCellPositionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BeginProtocolsResponse_IndividualResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *BeginProtocolsResponse_IndividualResponse) HasResponse() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*beginProtocolsResponse_IndividualResponse_Response)
	return ok
}

func (x *BeginProtocolsResponse_IndividualResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*beginProtocolsResponse_IndividualResponse_Status)
	return ok
}

func (x *BeginProtocolsResponse_IndividualResponse) ClearFlowCellPositionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FlowCellPositionName = nil
}

func (x *BeginProtocolsResponse_IndividualResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *BeginProtocolsResponse_IndividualResponse) ClearResponse() {
	if _, ok := x.xxx_hidden_Payload.(*beginProtocolsResponse_IndividualResponse_Response); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *BeginProtocolsResponse_IndividualResponse) ClearStatus() {
	if _, ok := x.xxx_hidden_Payload.(*beginProtocolsResponse_IndividualResponse_Status); ok {
		x.xxx_hidden_Payload = nil
	}
}

const BeginProtocolsResponse_IndividualResponse_Payload_not_set_case case_BeginProtocolsResponse_IndividualResponse_Payload = 0
const BeginProtocolsResponse_IndividualResponse_Response_case case_BeginProtocolsResponse_IndividualResponse_Payload = 2
const BeginProtocolsResponse_IndividualResponse_Status_case case_BeginProtocolsResponse_IndividualResponse_Payload = 3

func (x *BeginProtocolsResponse_IndividualResponse) WhichPayload() case_BeginProtocolsResponse_IndividualResponse_Payload {
	if x == nil {
		return BeginProtocolsResponse_IndividualResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *beginProtocolsResponse_IndividualResponse_Response:
		return BeginProtocolsResponse_IndividualResponse_Response_case
	case *beginProtocolsResponse_IndividualResponse_Status:
		return BeginProtocolsResponse_IndividualResponse_Status_case
	default:
		return BeginProtocolsResponse_IndividualResponse_Payload_not_set_case
	}
}

type BeginProtocolsResponse_IndividualResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FlowCellPositionName *string
	// Fields of oneof xxx_hidden_Payload:
	Response *protocol.BeginProtocolResponse
	Status   *status.Status
	// -- end of xxx_hidden_Payload
}

func (b0 BeginProtocolsResponse_IndividualResponse_builder) Build() *BeginProtocolsResponse_IndividualResponse {
	m0 := &BeginProtocolsResponse_IndividualResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FlowCellPositionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FlowCellPositionName = b.FlowCellPositionName
	}
	if b.Response != nil {
		x.xxx_hidden_Payload = &beginProtocolsResponse_IndividualResponse_Response{b.Response}
	}
	if b.Status != nil {
		x.xxx_hidden_Payload = &beginProtocolsResponse_IndividualResponse_Status{b.Status}
	}
	return m0
}

type case_BeginProtocolsResponse_IndividualResponse_Payload protoreflect.FieldNumber

func (x case_BeginProtocolsResponse_IndividualResponse_Payload) String() string {
	md := file_minknow_api_v2_protocols_proto_msgTypes[9].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isBeginProtocolsResponse_IndividualResponse_Payload interface {
	isBeginProtocolsResponse_IndividualResponse_Payload()
}

type beginProtocolsResponse_IndividualResponse_Response struct {
	Response *protocol.BeginProtocolResponse `protobuf:"bytes,2,opt,name=response,oneof"`
}

type beginProtocolsResponse_IndividualResponse_Status struct {
	Status *status.Status `protobuf:"bytes,3,opt,name=status,oneof"`
}

func (*beginProtocolsResponse_IndividualResponse_Response) isBeginProtocolsResponse_IndividualResponse_Payload() {
}

func (*beginProtocolsResponse_IndividualResponse_Status) isBeginProtocolsResponse_IndividualResponse_Payload() {
}

type StartProtocolsRequest_IndividualRequest struct {
	state                           protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_FlowCellPositionName *string                        `protobuf:"bytes,1,opt,name=flow_cell_position_name,json=flowCellPositionName"`
	xxx_hidden_Settings             *protocol.StartProtocolRequest `protobuf:"bytes,2,opt,name=settings"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *StartProtocolsRequest_IndividualRequest) Reset() {
	*x = StartProtocolsRequest_IndividualRequest{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProtocolsRequest_IndividualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProtocolsRequest_IndividualRequest) ProtoMessage() {}

func (x *StartProtocolsRequest_IndividualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartProtocolsRequest_IndividualRequest) GetFlowCellPositionName() string {
	if x != nil {
		if x.xxx_hidden_FlowCellPositionName != nil {
			return *x.xxx_hidden_FlowCellPositionName
		}
		return ""
	}
	return ""
}

func (x *StartProtocolsRequest_IndividualRequest) GetSettings() *protocol.StartProtocolRequest {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *StartProtocolsRequest_IndividualRequest) SetFlowCellPositionName(v string) {
	x.xxx_hidden_FlowCellPositionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StartProtocolsRequest_IndividualRequest) SetSettings(v *protocol.StartProtocolRequest) {
	x.xxx_hidden_Settings = v
}

func (x *StartProtocolsRequest_IndividualRequest) HasFlowCellPositionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartProtocolsRequest_IndividualRequest) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *StartProtocolsRequest_IndividualRequest) ClearFlowCellPositionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FlowCellPositionName = nil
}

func (x *StartProtocolsRequest_IndividualRequest) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

type StartProtocolsRequest_IndividualRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The position on which to start this protocol.
	FlowCellPositionName *string
	Settings             *protocol.StartProtocolRequest
}

func (b0 StartProtocolsRequest_IndividualRequest_builder) Build() *StartProtocolsRequest_IndividualRequest {
	m0 := &StartProtocolsRequest_IndividualRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FlowCellPositionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FlowCellPositionName = b.FlowCellPositionName
	}
	x.xxx_hidden_Settings = b.Settings
	return m0
}

type StartProtocolsResponse_IndividualResponse struct {
	state                           protoimpl.MessageState                              `protogen:"opaque.v1"`
	xxx_hidden_FlowCellPositionName *string                                             `protobuf:"bytes,1,opt,name=flow_cell_position_name,json=flowCellPositionName"`
	xxx_hidden_Payload              isStartProtocolsResponse_IndividualResponse_Payload `protobuf_oneof:"payload"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *StartProtocolsResponse_IndividualResponse) Reset() {
	*x = StartProtocolsResponse_IndividualResponse{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProtocolsResponse_IndividualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProtocolsResponse_IndividualResponse) ProtoMessage() {}

func (x *StartProtocolsResponse_IndividualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartProtocolsResponse_IndividualResponse) GetFlowCellPositionName() string {
	if x != nil {
		if x.xxx_hidden_FlowCellPositionName != nil {
			return *x.xxx_hidden_FlowCellPositionName
		}
		return ""
	}
	return ""
}

func (x *StartProtocolsResponse_IndividualResponse) GetResponse() *protocol.StartProtocolResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*startProtocolsResponse_IndividualResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *StartProtocolsResponse_IndividualResponse) GetStatus() *status.Status {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*startProtocolsResponse_IndividualResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StartProtocolsResponse_IndividualResponse) SetFlowCellPositionName(v string) {
	x.xxx_hidden_FlowCellPositionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StartProtocolsResponse_IndividualResponse) SetResponse(v *protocol.StartProtocolResponse) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &startProtocolsResponse_IndividualResponse_Response{v}
}

func (x *StartProtocolsResponse_IndividualResponse) SetStatus(v *status.Status) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &startProtocolsResponse_IndividualResponse_Status{v}
}

func (x *StartProtocolsResponse_IndividualResponse) HasFlowCellPositionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartProtocolsResponse_IndividualResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *StartProtocolsResponse_IndividualResponse) HasResponse() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*startProtocolsResponse_IndividualResponse_Response)
	return ok
}

func (x *StartProtocolsResponse_IndividualResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*startProtocolsResponse_IndividualResponse_Status)
	return ok
}

func (x *StartProtocolsResponse_IndividualResponse) ClearFlowCellPositionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FlowCellPositionName = nil
}

func (x *StartProtocolsResponse_IndividualResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *StartProtocolsResponse_IndividualResponse) ClearResponse() {
	if _, ok := x.xxx_hidden_Payload.(*startProtocolsResponse_IndividualResponse_Response); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *StartProtocolsResponse_IndividualResponse) ClearStatus() {
	if _, ok := x.xxx_hidden_Payload.(*startProtocolsResponse_IndividualResponse_Status); ok {
		x.xxx_hidden_Payload = nil
	}
}

const StartProtocolsResponse_IndividualResponse_Payload_not_set_case case_StartProtocolsResponse_IndividualResponse_Payload = 0
const StartProtocolsResponse_IndividualResponse_Response_case case_StartProtocolsResponse_IndividualResponse_Payload = 2
const StartProtocolsResponse_IndividualResponse_Status_case case_StartProtocolsResponse_IndividualResponse_Payload = 3

func (x *StartProtocolsResponse_IndividualResponse) WhichPayload() case_StartProtocolsResponse_IndividualResponse_Payload {
	if x == nil {
		return StartProtocolsResponse_IndividualResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *startProtocolsResponse_IndividualResponse_Response:
		return StartProtocolsResponse_IndividualResponse_Response_case
	case *startProtocolsResponse_IndividualResponse_Status:
		return StartProtocolsResponse_IndividualResponse_Status_case
	default:
		return StartProtocolsResponse_IndividualResponse_Payload_not_set_case
	}
}

type StartProtocolsResponse_IndividualResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FlowCellPositionName *string
	// Fields of oneof xxx_hidden_Payload:
	Response *protocol.StartProtocolResponse
	Status   *status.Status
	// -- end of xxx_hidden_Payload
}

func (b0 StartProtocolsResponse_IndividualResponse_builder) Build() *StartProtocolsResponse_IndividualResponse {
	m0 := &StartProtocolsResponse_IndividualResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FlowCellPositionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FlowCellPositionName = b.FlowCellPositionName
	}
	if b.Response != nil {
		x.xxx_hidden_Payload = &startProtocolsResponse_IndividualResponse_Response{b.Response}
	}
	if b.Status != nil {
		x.xxx_hidden_Payload = &startProtocolsResponse_IndividualResponse_Status{b.Status}
	}
	return m0
}

type case_StartProtocolsResponse_IndividualResponse_Payload protoreflect.FieldNumber

func (x case_StartProtocolsResponse_IndividualResponse_Payload) String() string {
	md := file_minknow_api_v2_protocols_proto_msgTypes[11].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStartProtocolsResponse_IndividualResponse_Payload interface {
	isStartProtocolsResponse_IndividualResponse_Payload()
}

type startProtocolsResponse_IndividualResponse_Response struct {
	Response *protocol.StartProtocolResponse `protobuf:"bytes,2,opt,name=response,oneof"`
}

type startProtocolsResponse_IndividualResponse_Status struct {
	Status *status.Status `protobuf:"bytes,3,opt,name=status,oneof"`
}

func (*startProtocolsResponse_IndividualResponse_Response) isStartProtocolsResponse_IndividualResponse_Payload() {
}

func (*startProtocolsResponse_IndividualResponse_Status) isStartProtocolsResponse_IndividualResponse_Payload() {
}

type StopProtocolsResponse_IndividualResponse struct {
	state                  protoimpl.MessageState                             `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                                            `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_Payload     isStopProtocolsResponse_IndividualResponse_Payload `protobuf_oneof:"payload"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StopProtocolsResponse_IndividualResponse) Reset() {
	*x = StopProtocolsResponse_IndividualResponse{}
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProtocolsResponse_IndividualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProtocolsResponse_IndividualResponse) ProtoMessage() {}

func (x *StopProtocolsResponse_IndividualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minknow_api_v2_protocols_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopProtocolsResponse_IndividualResponse) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *StopProtocolsResponse_IndividualResponse) GetResponse() *protocol.StopProtocolResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*stopProtocolsResponse_IndividualResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *StopProtocolsResponse_IndividualResponse) GetStatus() *status.Status {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*stopProtocolsResponse_IndividualResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StopProtocolsResponse_IndividualResponse) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StopProtocolsResponse_IndividualResponse) SetResponse(v *protocol.StopProtocolResponse) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &stopProtocolsResponse_IndividualResponse_Response{v}
}

func (x *StopProtocolsResponse_IndividualResponse) SetStatus(v *status.Status) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &stopProtocolsResponse_IndividualResponse_Status{v}
}

func (x *StopProtocolsResponse_IndividualResponse) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StopProtocolsResponse_IndividualResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *StopProtocolsResponse_IndividualResponse) HasResponse() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*stopProtocolsResponse_IndividualResponse_Response)
	return ok
}

func (x *StopProtocolsResponse_IndividualResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*stopProtocolsResponse_IndividualResponse_Status)
	return ok
}

func (x *StopProtocolsResponse_IndividualResponse) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *StopProtocolsResponse_IndividualResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *StopProtocolsResponse_IndividualResponse) ClearResponse() {
	if _, ok := x.xxx_hidden_Payload.(*stopProtocolsResponse_IndividualResponse_Response); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *StopProtocolsResponse_IndividualResponse) ClearStatus() {
	if _, ok := x.xxx_hidden_Payload.(*stopProtocolsResponse_IndividualResponse_Status); ok {
		x.xxx_hidden_Payload = nil
	}
}

const StopProtocolsResponse_IndividualResponse_Payload_not_set_case case_StopProtocolsResponse_IndividualResponse_Payload = 0
const StopProtocolsResponse_IndividualResponse_Response_case case_StopProtocolsResponse_IndividualResponse_Payload = 2
const StopProtocolsResponse_IndividualResponse_Status_case case_StopProtocolsResponse_IndividualResponse_Payload = 3

func (x *StopProtocolsResponse_IndividualResponse) WhichPayload() case_StopProtocolsResponse_IndividualResponse_Payload {
	if x == nil {
		return StopProtocolsResponse_IndividualResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *stopProtocolsResponse_IndividualResponse_Response:
		return StopProtocolsResponse_IndividualResponse_Response_case
	case *stopProtocolsResponse_IndividualResponse_Status:
		return StopProtocolsResponse_IndividualResponse_Status_case
	default:
		return StopProtocolsResponse_IndividualResponse_Payload_not_set_case
	}
}

type StopProtocolsResponse_IndividualResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RunId *string
	// Fields of oneof xxx_hidden_Payload:
	Response *protocol.StopProtocolResponse
	Status   *status.Status
	// -- end of xxx_hidden_Payload
}

func (b0 StopProtocolsResponse_IndividualResponse_builder) Build() *StopProtocolsResponse_IndividualResponse {
	m0 := &StopProtocolsResponse_IndividualResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.Response != nil {
		x.xxx_hidden_Payload = &stopProtocolsResponse_IndividualResponse_Response{b.Response}
	}
	if b.Status != nil {
		x.xxx_hidden_Payload = &stopProtocolsResponse_IndividualResponse_Status{b.Status}
	}
	return m0
}

type case_StopProtocolsResponse_IndividualResponse_Payload protoreflect.FieldNumber

func (x case_StopProtocolsResponse_IndividualResponse_Payload) String() string {
	md := file_minknow_api_v2_protocols_proto_msgTypes[12].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStopProtocolsResponse_IndividualResponse_Payload interface {
	isStopProtocolsResponse_IndividualResponse_Payload()
}

type stopProtocolsResponse_IndividualResponse_Response struct {
	Response *protocol.StopProtocolResponse `protobuf:"bytes,2,opt,name=response,oneof"`
}

type stopProtocolsResponse_IndividualResponse_Status struct {
	Status *status.Status `protobuf:"bytes,3,opt,name=status,oneof"`
}

func (*stopProtocolsResponse_IndividualResponse_Response) isStopProtocolsResponse_IndividualResponse_Payload() {
}

func (*stopProtocolsResponse_IndividualResponse_Status) isStopProtocolsResponse_IndividualResponse_Payload() {
}

var File_minknow_api_v2_protocols_proto protoreflect.FileDescriptor

const file_minknow_api_v2_protocols_proto_rawDesc = "" +
	"\n" +
	"\x1eminknow_api/v2/protocols.proto\x12\x17minknow_api.v2.protocol\x1a\x1dminknow_api/acquisition.proto\x1a\x1aminknow_api/protocol.proto\x1a\x11util/status.proto\"\x8a\x02\n" +
	"\x15BeginProtocolsRequest\x12\\\n" +
	"\brequests\x18\x01 \x03(\v2@.minknow_api.v2.protocol.BeginProtocolsRequest.IndividualRequestR\brequests\x1a\x92\x01\n" +
	"\x11IndividualRequest\x125\n" +
	"\x17flow_cell_position_name\x18\x01 \x01(\tR\x14flowCellPositionName\x12F\n" +
	"\bsettings\x18\x02 \x01(\v2*.minknow_api.protocol.BeginProtocolRequestR\bsettings\"\xcc\x02\n" +
	"\x16BeginProtocolsResponse\x12`\n" +
	"\tresponses\x18\x01 \x03(\v2B.minknow_api.v2.protocol.BeginProtocolsResponse.IndividualResponseR\tresponses\x1a\xcf\x01\n" +
	"\x12IndividualResponse\x125\n" +
	"\x17flow_cell_position_name\x18\x01 \x01(\tR\x14flowCellPositionName\x12I\n" +
	"\bresponse\x18\x02 \x01(\v2+.minknow_api.protocol.BeginProtocolResponseH\x00R\bresponse\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusH\x00R\x06statusB\t\n" +
	"\apayload\"\x8a\x02\n" +
	"\x15StartProtocolsRequest\x12\\\n" +
	"\brequests\x18\x01 \x03(\v2@.minknow_api.v2.protocol.StartProtocolsRequest.IndividualRequestR\brequests\x1a\x92\x01\n" +
	"\x11IndividualRequest\x125\n" +
	"\x17flow_cell_position_name\x18\x01 \x01(\tR\x14flowCellPositionName\x12F\n" +
	"\bsettings\x18\x02 \x01(\v2*.minknow_api.protocol.StartProtocolRequestR\bsettings\"\xcc\x02\n" +
	"\x16StartProtocolsResponse\x12`\n" +
	"\tresponses\x18\x01 \x03(\v2B.minknow_api.v2.protocol.StartProtocolsResponse.IndividualResponseR\tresponses\x1a\xcf\x01\n" +
	"\x12IndividualResponse\x125\n" +
	"\x17flow_cell_position_name\x18\x01 \x01(\tR\x14flowCellPositionName\x12I\n" +
	"\bresponse\x18\x02 \x01(\v2+.minknow_api.protocol.StartProtocolResponseH\x00R\bresponse\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusH\x00R\x06statusB\t\n" +
	"\apayload\"]\n" +
	"\x14StopProtocolsRequest\x12E\n" +
	"\brequests\x18\x01 \x03(\v2).minknow_api.protocol.StopProtocolRequestR\brequests\"\xa9\x02\n" +
	"\x15StopProtocolsResponse\x12_\n" +
	"\tresponses\x18\x01 \x03(\v2A.minknow_api.v2.protocol.StopProtocolsResponse.IndividualResponseR\tresponses\x1a\xae\x01\n" +
	"\x12IndividualResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12H\n" +
	"\bresponse\x18\x02 \x01(\v2*.minknow_api.protocol.StopProtocolResponseH\x00R\bresponse\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusH\x00R\x06statusB\t\n" +
	"\apayload\"\xd5\x01\n" +
	"\x12GroupFilteringInfo\x12b\n" +
	"\x15experiment_start_time\x18\x01 \x01(\v2..minknow_api.protocol.FilteringInfo.TimeFilterR\x13experimentStartTime\x12[\n" +
	"\x0forder_direction\x18\x02 \x01(\x0e22.minknow_api.protocol.FilteringInfo.OrderDirectionR\x0eorderDirection\"c\n" +
	"\x13ListGroupIdsRequest\x12L\n" +
	"\vfilter_info\x18\x01 \x01(\v2+.minknow_api.v2.protocol.GroupFilteringInfoR\n" +
	"filterInfo2\xe2\b\n" +
	"\x10ProtocolsService\x12t\n" +
	"\x0fbegin_protocols\x12..minknow_api.v2.protocol.BeginProtocolsRequest\x1a/.minknow_api.v2.protocol.BeginProtocolsResponse\"\x00\x12t\n" +
	"\x0fstart_protocols\x12..minknow_api.v2.protocol.StartProtocolsRequest\x1a/.minknow_api.v2.protocol.StartProtocolsResponse\"\x00\x12q\n" +
	"\x0estop_protocols\x12-.minknow_api.v2.protocol.StopProtocolsRequest\x1a..minknow_api.v2.protocol.StopProtocolsResponse\"\x00\x12c\n" +
	"\fget_run_info\x12'.minknow_api.protocol.GetRunInfoRequest\x1a%.minknow_api.protocol.ProtocolRunInfo\"\x03\x90\x02\x01\x12x\n" +
	"\x12list_protocol_runs\x12-.minknow_api.protocol.ListProtocolRunsRequest\x1a..minknow_api.protocol.ListProtocolRunsResponse\"\x03\x90\x02\x01\x12\x8f\x01\n" +
	"\x1cclear_protocols_history_data\x125.minknow_api.protocol.ClearProtocolHistoryDataRequest\x1a6.minknow_api.protocol.ClearProtocolHistoryDataResponse\"\x00\x12z\n" +
	"\x13generate_run_report\x12..minknow_api.protocol.GenerateRunReportRequest\x1a/.minknow_api.protocol.GenerateRunReportResponse\"\x000\x01\x12\x7f\n" +
	"\x14get_acquisition_info\x125.minknow_api.acquisition.GetAcquisitionRunInfoRequest\x1a+.minknow_api.acquisition.AcquisitionRunInfo\"\x03\x90\x02\x01\x12\x80\x01\n" +
	"\x17list_protocol_group_ids\x12,.minknow_api.v2.protocol.ListGroupIdsRequest\x1a2.minknow_api.protocol.ListProtocolGroupIdsResponse\"\x03\x90\x02\x01Bd\n" +
	"\x1fcom.nanoporetech.minknow_api.v2Z6github.com/nanoporetech/minknow_api/go/gen/v2/protocol\xa2\x02\x05MKAPI\x92\x03\x00b\beditionsp\xe9\a"

var file_minknow_api_v2_protocols_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_minknow_api_v2_protocols_proto_goTypes = []any{
	(*BeginProtocolsRequest)(nil),                     // 0: minknow_api.v2.protocol.BeginProtocolsRequest
	(*BeginProtocolsResponse)(nil),                    // 1: minknow_api.v2.protocol.BeginProtocolsResponse
	(*StartProtocolsRequest)(nil),                     // 2: minknow_api.v2.protocol.StartProtocolsRequest
	(*StartProtocolsResponse)(nil),                    // 3: minknow_api.v2.protocol.StartProtocolsResponse
	(*StopProtocolsRequest)(nil),                      // 4: minknow_api.v2.protocol.StopProtocolsRequest
	(*StopProtocolsResponse)(nil),                     // 5: minknow_api.v2.protocol.StopProtocolsResponse
	(*GroupFilteringInfo)(nil),                        // 6: minknow_api.v2.protocol.GroupFilteringInfo
	(*ListGroupIdsRequest)(nil),                       // 7: minknow_api.v2.protocol.ListGroupIdsRequest
	(*BeginProtocolsRequest_IndividualRequest)(nil),   // 8: minknow_api.v2.protocol.BeginProtocolsRequest.IndividualRequest
	(*BeginProtocolsResponse_IndividualResponse)(nil), // 9: minknow_api.v2.protocol.BeginProtocolsResponse.IndividualResponse
	(*StartProtocolsRequest_IndividualRequest)(nil),   // 10: minknow_api.v2.protocol.StartProtocolsRequest.IndividualRequest
	(*StartProtocolsResponse_IndividualResponse)(nil), // 11: minknow_api.v2.protocol.StartProtocolsResponse.IndividualResponse
	(*StopProtocolsResponse_IndividualResponse)(nil),  // 12: minknow_api.v2.protocol.StopProtocolsResponse.IndividualResponse
	(*protocol.StopProtocolRequest)(nil),              // 13: minknow_api.protocol.StopProtocolRequest
	(*protocol.FilteringInfo_TimeFilter)(nil),         // 14: minknow_api.protocol.FilteringInfo.TimeFilter
	(protocol.FilteringInfo_OrderDirection)(0),        // 15: minknow_api.protocol.FilteringInfo.OrderDirection
	(*protocol.BeginProtocolRequest)(nil),             // 16: minknow_api.protocol.BeginProtocolRequest
	(*protocol.BeginProtocolResponse)(nil),            // 17: minknow_api.protocol.BeginProtocolResponse
	(*status.Status)(nil),                             // 18: google.rpc.Status
	(*protocol.StartProtocolRequest)(nil),             // 19: minknow_api.protocol.StartProtocolRequest
	(*protocol.StartProtocolResponse)(nil),            // 20: minknow_api.protocol.StartProtocolResponse
	(*protocol.StopProtocolResponse)(nil),             // 21: minknow_api.protocol.StopProtocolResponse
	(*protocol.GetRunInfoRequest)(nil),                // 22: minknow_api.protocol.GetRunInfoRequest
	(*protocol.ListProtocolRunsRequest)(nil),          // 23: minknow_api.protocol.ListProtocolRunsRequest
	(*protocol.ClearProtocolHistoryDataRequest)(nil),  // 24: minknow_api.protocol.ClearProtocolHistoryDataRequest
	(*protocol.GenerateRunReportRequest)(nil),         // 25: minknow_api.protocol.GenerateRunReportRequest
	(*acquisition.GetAcquisitionRunInfoRequest)(nil),  // 26: minknow_api.acquisition.GetAcquisitionRunInfoRequest
	(*protocol.ProtocolRunInfo)(nil),                  // 27: minknow_api.protocol.ProtocolRunInfo
	(*protocol.ListProtocolRunsResponse)(nil),         // 28: minknow_api.protocol.ListProtocolRunsResponse
	(*protocol.ClearProtocolHistoryDataResponse)(nil), // 29: minknow_api.protocol.ClearProtocolHistoryDataResponse
	(*protocol.GenerateRunReportResponse)(nil),        // 30: minknow_api.protocol.GenerateRunReportResponse
	(*acquisition.AcquisitionRunInfo)(nil),            // 31: minknow_api.acquisition.AcquisitionRunInfo
	(*protocol.ListProtocolGroupIdsResponse)(nil),     // 32: minknow_api.protocol.ListProtocolGroupIdsResponse
}
var file_minknow_api_v2_protocols_proto_depIdxs = []int32{
	8,  // 0: minknow_api.v2.protocol.BeginProtocolsRequest.requests:type_name -> minknow_api.v2.protocol.BeginProtocolsRequest.IndividualRequest
	9,  // 1: minknow_api.v2.protocol.BeginProtocolsResponse.responses:type_name -> minknow_api.v2.protocol.BeginProtocolsResponse.IndividualResponse
	10, // 2: minknow_api.v2.protocol.StartProtocolsRequest.requests:type_name -> minknow_api.v2.protocol.StartProtocolsRequest.IndividualRequest
	11, // 3: minknow_api.v2.protocol.StartProtocolsResponse.responses:type_name -> minknow_api.v2.protocol.StartProtocolsResponse.IndividualResponse
	13, // 4: minknow_api.v2.protocol.StopProtocolsRequest.requests:type_name -> minknow_api.protocol.StopProtocolRequest
	12, // 5: minknow_api.v2.protocol.StopProtocolsResponse.responses:type_name -> minknow_api.v2.protocol.StopProtocolsResponse.IndividualResponse
	14, // 6: minknow_api.v2.protocol.GroupFilteringInfo.experiment_start_time:type_name -> minknow_api.protocol.FilteringInfo.TimeFilter
	15, // 7: minknow_api.v2.protocol.GroupFilteringInfo.order_direction:type_name -> minknow_api.protocol.FilteringInfo.OrderDirection
	6,  // 8: minknow_api.v2.protocol.ListGroupIdsRequest.filter_info:type_name -> minknow_api.v2.protocol.GroupFilteringInfo
	16, // 9: minknow_api.v2.protocol.BeginProtocolsRequest.IndividualRequest.settings:type_name -> minknow_api.protocol.BeginProtocolRequest
	17, // 10: minknow_api.v2.protocol.BeginProtocolsResponse.IndividualResponse.response:type_name -> minknow_api.protocol.BeginProtocolResponse
	18, // 11: minknow_api.v2.protocol.BeginProtocolsResponse.IndividualResponse.status:type_name -> google.rpc.Status
	19, // 12: minknow_api.v2.protocol.StartProtocolsRequest.IndividualRequest.settings:type_name -> minknow_api.protocol.StartProtocolRequest
	20, // 13: minknow_api.v2.protocol.StartProtocolsResponse.IndividualResponse.response:type_name -> minknow_api.protocol.StartProtocolResponse
	18, // 14: minknow_api.v2.protocol.StartProtocolsResponse.IndividualResponse.status:type_name -> google.rpc.Status
	21, // 15: minknow_api.v2.protocol.StopProtocolsResponse.IndividualResponse.response:type_name -> minknow_api.protocol.StopProtocolResponse
	18, // 16: minknow_api.v2.protocol.StopProtocolsResponse.IndividualResponse.status:type_name -> google.rpc.Status
	0,  // 17: minknow_api.v2.protocol.ProtocolsService.begin_protocols:input_type -> minknow_api.v2.protocol.BeginProtocolsRequest
	2,  // 18: minknow_api.v2.protocol.ProtocolsService.start_protocols:input_type -> minknow_api.v2.protocol.StartProtocolsRequest
	4,  // 19: minknow_api.v2.protocol.ProtocolsService.stop_protocols:input_type -> minknow_api.v2.protocol.StopProtocolsRequest
	22, // 20: minknow_api.v2.protocol.ProtocolsService.get_run_info:input_type -> minknow_api.protocol.GetRunInfoRequest
	23, // 21: minknow_api.v2.protocol.ProtocolsService.list_protocol_runs:input_type -> minknow_api.protocol.ListProtocolRunsRequest
	24, // 22: minknow_api.v2.protocol.ProtocolsService.clear_protocols_history_data:input_type -> minknow_api.protocol.ClearProtocolHistoryDataRequest
	25, // 23: minknow_api.v2.protocol.ProtocolsService.generate_run_report:input_type -> minknow_api.protocol.GenerateRunReportRequest
	26, // 24: minknow_api.v2.protocol.ProtocolsService.get_acquisition_info:input_type -> minknow_api.acquisition.GetAcquisitionRunInfoRequest
	7,  // 25: minknow_api.v2.protocol.ProtocolsService.list_protocol_group_ids:input_type -> minknow_api.v2.protocol.ListGroupIdsRequest
	1,  // 26: minknow_api.v2.protocol.ProtocolsService.begin_protocols:output_type -> minknow_api.v2.protocol.BeginProtocolsResponse
	3,  // 27: minknow_api.v2.protocol.ProtocolsService.start_protocols:output_type -> minknow_api.v2.protocol.StartProtocolsResponse
	5,  // 28: minknow_api.v2.protocol.ProtocolsService.stop_protocols:output_type -> minknow_api.v2.protocol.StopProtocolsResponse
	27, // 29: minknow_api.v2.protocol.ProtocolsService.get_run_info:output_type -> minknow_api.protocol.ProtocolRunInfo
	28, // 30: minknow_api.v2.protocol.ProtocolsService.list_protocol_runs:output_type -> minknow_api.protocol.ListProtocolRunsResponse
	29, // 31: minknow_api.v2.protocol.ProtocolsService.clear_protocols_history_data:output_type -> minknow_api.protocol.ClearProtocolHistoryDataResponse
	30, // 32: minknow_api.v2.protocol.ProtocolsService.generate_run_report:output_type -> minknow_api.protocol.GenerateRunReportResponse
	31, // 33: minknow_api.v2.protocol.ProtocolsService.get_acquisition_info:output_type -> minknow_api.acquisition.AcquisitionRunInfo
	32, // 34: minknow_api.v2.protocol.ProtocolsService.list_protocol_group_ids:output_type -> minknow_api.protocol.ListProtocolGroupIdsResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_minknow_api_v2_protocols_proto_init() }
func file_minknow_api_v2_protocols_proto_init() {
	if File_minknow_api_v2_protocols_proto != nil {
		return
	}
	file_minknow_api_v2_protocols_proto_msgTypes[9].OneofWrappers = []any{
		(*beginProtocolsResponse_IndividualResponse_Response)(nil),
		(*beginProtocolsResponse_IndividualResponse_Status)(nil),
	}
	file_minknow_api_v2_protocols_proto_msgTypes[11].OneofWrappers = []any{
		(*startProtocolsResponse_IndividualResponse_Response)(nil),
		(*startProtocolsResponse_IndividualResponse_Status)(nil),
	}
	file_minknow_api_v2_protocols_proto_msgTypes[12].OneofWrappers = []any{
		(*stopProtocolsResponse_IndividualResponse_Response)(nil),
		(*stopProtocolsResponse_IndividualResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minknow_api_v2_protocols_proto_rawDesc), len(file_minknow_api_v2_protocols_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minknow_api_v2_protocols_proto_goTypes,
		DependencyIndexes: file_minknow_api_v2_protocols_proto_depIdxs,
		MessageInfos:      file_minknow_api_v2_protocols_proto_msgTypes,
	}.Build()
	File_minknow_api_v2_protocols_proto = out.File
	file_minknow_api_v2_protocols_proto_goTypes = nil
	file_minknow_api_v2_protocols_proto_depIdxs = nil
}
